### PR TITLE
etc/kubernetes: remove dedup

### PR DESCRIPTION
**Pull request by miekg**
Don't think this is actually needed and slows things down.

### CODE REVIEW

**Comment by miekg** [comment]
Nice, this fails the exact thing it should prevent. Good chance to clean that up

**Comment by chrisohaver** [comment]
Probably need to avoid adding duplicates in backend type funcs (e.g. A(), AAAA(), etc...)

**Comment by miekg** [comment]
hmm I wonder if kubernetes is affected though, etcd def. is

**Comment by chrisohaver** [comment]
k8s failed 15 tests... most look to be duplicates issues.

**Comment by miekg** [comment]
ah thanks. We can choose to do a AppendUnique (or something). Might be a matter of benchmarking though; think dedup might be a tad smarter as well.

**Comment by miekg** [comment]
abandoning this effort :)

**Comment by miekg** [comment]
looking at dns.Dedup we should probably not add dups in the first place. Find a dup is tricky though as we need to compare rdata and miekg/dns doesn't really have a function for that.

**Comment by chrisohaver** [comment]
The reason k8s add dups is because the record retrieval funcs (e.g. findServices) are unaware of the query type.  They will for example pull a service multiple times if it has more than one port.  The extra records are duplicates from an `A` response POV... but they are needed for an `SRV` response.

IMO, I think the fact that the record retrieval funcs are unaware of record they need to build doesn't help us that much.  It may reduce some code slightly ... but at the expense of doing extra work most of the time (most queries are not `SRV`).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] etc/kubernete..." ]
>The reason k8s add dups is because the record retrieval funcs (e.g. findServices) are unaware of the query type.  They will for example pull a service multiple times if it has more than one port.  The extra records are duplicates from an `A` record POV... but they are needed for an `SRV` record.
>
>IMO, I think the fact that the record retrieval funcs are unaware of record they need to build doesn't help us that much.  It may reduce some code slightly ... but at the expense of doing extra work most of the time (most queries are not `SRV`).

Ack.

Note dedup was added because multiple identical RRs are a protocol violation.

**Comment by miekg** [comment]
https://github.com/miekg/dns/issues/679 filed

**Comment by jameshartig** [comment]
Somewhat related, I was added as a reviewer but I'm not in the OWNERS file for the kubernetes plugin. Any idea why it chose me?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] etc/kubernete..." ]
>Somewhat related, I was added as a reviewer but I'm not in the OWNERS file for the kubernetes plugin. Any idea why it chose me?

my guess (don't log this in corbot, i should), dnstest -> pkg -> plugin -> 
coredns only has an owner on the top level.

**Pull request closed without merging**
