### PR TITLE
modules: fix datadog/dd-trace-go problem

### PR DESCRIPTION
**Pull request by lopezator**
### 1. Why is this pull request needed and what does it do?

* Fix the `lowercasegate` issue with the https://github.com/DataDog/dd-trace-go package by introducing the replace directive on `go.mod`
* Run `go mod tidy` which should be run before any build.

`lowercasegate` info:

https://github.com/golang/go/issues/26904  
https://github.com/golang/go/issues/28489  
https://github.com/golang/go/issues/28489  

`go mod tidy info`:

https://github.com/golang/go/wiki/Modules#how-to-prepare-for-a-release
https://github.com/golang/go/wiki/Modules#why-does-go-mod-tidy-record-indirect-and-test-dependencies-in-my-gomod

### 2. Which issues (if any) are related?

This pull request is affected by this problem and would benefit by merging this:

https://github.com/coredns/coredns/pull/2667

### CODE REVIEW

**Comment by miekg** [comment]
don't understand why CI now barfs with
~~~
get "gopkg.in/inf.v0": found meta tag get.metaImport{Prefix:"gopkg.in/inf.v0", VCS:"git", RepoRoot:"https://gopkg.in/inf.v0"} at https://gopkg.in/inf.v0?go-get=1
go: finding github.com/DataDog/dd-trace-go/tracer latest
Fetching https://github.com?go-get=1
go: finding github.com/apache/thrift/lib/go/thrift latest
go: finding github.com/apache/thrift/lib/go latest
go: finding github.com/apache/thrift/lib latest
go: finding github.com/modern-go/concurrent latest
Parsing meta tags from https://github.com?go-get=1 (status code 200)
build github.com/coredns/coredns: cannot find module for path github.com/DataDog/dd-trace-go/tracer
Makefile:17: recipe for target 'coredns' failed
make[1]: *** [coredns] Error 1
make[1]: Leaving directory '/tmp/tmp.DFq3P4awmV/src/github.com/coredns/coredns'
Makefile:59: recipe for target 'build-docker' failed
make: *** [build-docker] Error 2
~~~

**Comment by chrisohaver** [comment]
go version difference? Doesn't seem like that would cause this error ...  but I'll update go on drone to be sure...

**Comment by lopezator** [comment]
me neither @miekg what's exactly that `coredns/ci`? an internal DroneCI? Maybe there is an issue on it's internal config? 

It's that CI also using go1.12? Looks like it's ignoring the newly introduced replace directive.

**Comment by miekg** [comment]
ah, that's prolly it, esp if travis is OK.

then 
/lgtm

**Pull request merged**
