### PR TITLE
plugin/errors: 'consolidate' option

### PR DESCRIPTION
**Pull request by rdrozhdzh**
### 1. Why is this pull request needed and what does it do?
add 'consolidate' option
see more details at https://github.com/infobloxopen/coredns-plugin-errors/pull/3
### 2. Which issues (if any) are related?
#2168
### 3. Which documentation changes (if any) need to be made?
updated README.md

### CODE REVIEW

**Comment by fturib** [comment]
@rdrozhdzh : thanks for putting all that together !

**Comment by fturib** [comment]
@miekg : is that ok to merge this PR ?

**Comment by miekg** [comment]
sorry, I'm late reviewing this. Gave it a quick glance, will proper review later today.

One question on all the atomic use, isn't there some nice package we can use to do the ratelimiting and if not, are we sure we've aligned all the structure used correctly for atomic use?

**Comment by rdrozhdzh** [comment]
Hi @miekg, I guess your concern is about the bug mentioned at https://golang.org/pkg/sync/atomic/ , i.e. 

> On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned. 

In my change three fields are accessed atomically - `pattern.ptimer`, `pattern.count`, `errorHandler.stopFlag`. The last two are 32-bit values, so they should not be affected by the mentioned bug. The `pattern.ptimer` is a pointer and it could be 64-bit value, but anyway it is the first field in an allocated structure.

Tests use more atomically accessed data fields, but they all are 32-bit data.

So, I don't expect any issues regarding data alignment.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/errors..." ]
>Hi @miekg, I guess your concern is about the bug mentioned at https://golang.org/pkg/sync/atomic/ , i.e.
>
>> On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.
>
>In my change three fields are accessed atomically - `pattern.ptimer`, `pattern.count`, `errorHandler.stopFlag`. The last two are 32-bit values, so they should not be affected by the mentioned bug. The `pattern.ptimer` is a pointer and it could be 64-bit value, but anyway it is the first field in an allocated structure.
>
>Tests use more atomically accessed data fields, but they all are 32-bit data.
>
>So, I don't expect any issues regarding data alignment.

Good. Good to see you thought about it. :-)

**Review by miekg — APPROVED** [review]

**Pull request merged**
