### PR TITLE
pkg: add dnstest

### PR DESCRIPTION
**Pull request by miekg**
Add a full test server impl in this new package + tests. Move
dnsrecorder into this package as well and finish up the commented out
tests that were left in the old dnsrecorder package.

Update all callers.

### CODE REVIEW

**Comment by miekg** [comment]
The only bit again this change requires to include dnsstest even though you're not testing; upside is this mimics httptest package a bit.

**Comment by johnbelamaric** [comment]
Can you explain the big picture of why we need this?

**Comment by miekg** [comment]
https://github.com/coredns/coredns/blob/master/plugin/proxy/proxy_test.go#L44

can just use this. If I'm going to move it to dns healthcheck pings (closed PR #1093 used this already)

**Comment by johnbelamaric** [comment]
Ok, I see. thanks.

**Comment by miekg** [comment]
cool. This might also make sense in loads of other tests (instead of having a full blown coredns running on the other side)

**Pull request merged**
