### PR TITLE
WIP: set nsAddress

### PR DESCRIPTION
**Pull request by miekg**
Resolve the NS Record IP on startup.

### CODE REVIEW

**Comment by miekg** [comment]
@chrisohaver so the problem with this PR will be that we don't when exactly to get `k.nsAddr`? Mostly because the setup function are async.

**Comment by chrisohaver** [comment]
The initial seed of the cache may not be async.
Periodic refresh of cache is async, and so are incremental updates via watchers.

As the PR is now, the code will look up the name in the service list every time an `NS` or `SOA`  is requested.  This incurs a penalty because the service cache is not indexed. The penalty greater for deployments with a larger number of services.
I have opened an issue to add indexing for services and endpoints (#814), and currently working on implementing it. I didnt open the issue for this `NS` record reason, rather for general performance improvement at scale in k8s.
Once it's indexed though, it's less of an penalty to look up every time (but still not as efficient as if we just stashed the result somewhere).

Still - it depends on your concern for performance of `NS` and `SOA` records.  If this isn't a concern, then none of this matters - We can look it up every time.  When the indexing comes along later, it will be a welcome (but not critical) improvement.

**Comment by miekg** [comment]
Thanks for the write up. We should def. cache this.

**Comment by miekg** [comment]
Looking through the kube-dns code it has "waitForResourceSyncedOrDie()" which seems to exactly what we need before setting this or letting queries through.

**Pull request closed without merging**
