### PR TITLE
plugins/auto: allow fallthrough if no zone match

### PR DESCRIPTION
**Pull request by imacks**
### 1. Why is this pull request needed and what does it do?
auto plugin currently responds to client with a failure if non of the zonefiles match the query zone. right now the only way for it to fallthrough to the next plugin is by explicitly naming the authoritative zones for this plugin, e.g. `auto example.com example.org`. This is not ideal if there are a lot of zones, or the zonefiles directory changes dynamically. This PR makes the auto plugin pass the query to the next plugin if the query zone doesn't match any of the loaded zonefiles.

### 2. Which issues (if any) are related?
this is a solution to #3033

### 3. Which documentation changes (if any) need to be made?
current doc is silent on the issue. 

### 4. Does this introduce a backward incompatible change or deprecation?
no.

### CODE REVIEW

**Comment by miekg** [comment]
can you sign the commit? git -s or just manually adding 'Signed-off-by: <your name>', can't merge otherwise

ta

**Comment by imacks** [comment]
done :)

**Comment by miekg** [comment]
argh, you need to rebase, picking up changes in another plugin

**Comment by imacks** [comment]
i created a new pr that should be cleaner. #4166. feel free to close this one.

**Pull request closed without merging**
