### PR TITLE
readme: fixed typos

### PR DESCRIPTION
**Pull request by michael-k**

### CODE REVIEW

**Comment by miekg** [comment]
Thanks. It seems the last lines got some extra spaces on the end though.

**Comment by michael-k** [comment]
Yeah, exactly 2 per line.  That's a feature of markdown to enforce line breaks.  Compare https://github.com/coredns/coredns#blog-and-contact with https://github.com/michael-k/coredns/blob/patch-1/README.md#blog-and-contact

I can simply remove them or convert the section to a list if you want.

**Comment by miekg** [comment]
Hmmm, using that technique is a bit of an anti-pattern and I probably won't survive the next round of "trim-all-eol-whitespace". Is there nothing else you can use? Or maybe make it a bullet list?

**Comment by michael-k** [comment]
converted to a list

https://github.com/michael-k/coredns/blob/patch-1/README.md#blog-and-contact

**Pull request merged**
