### PR TITLE
Forward

### PR DESCRIPTION
**Pull request by miekg**

### CODE REVIEW

**Comment by miekg** [comment]
still fails ci with an unrelated error
~~~
############### Integration Test REPO:github.com/coredns COMMIT:f93b631d400a530242a13a7db18aa75c879a4330 Workdir: /tmp/tmp.F3GDo6z9Ys #######################
mkdir -p /tmp/tmp.F3GDo6z9Ys/src/github.com/coredns
cd /tmp/tmp.F3GDo6z9Ys/src/github.com/coredns && \
  git clone https://github.com/coredns/coredns.git && \
  cd coredns && \
  git fetch --depth 1 origin pull/1444/head:pr-1444 && \
  git checkout pr-1444 && \
  go get
Cloning into 'coredns'...
From https://github.com/coredns/coredns
 * [new ref]           refs/pull/1444/head -> pr-1444
Switched to branch 'pr-1444'
# Start local docker image repo (k8s must pull images from a repo)
docker run -d -p 5000:5000 --restart=always --name registry registry:2.6.2 || true
9fa30ff0dd09dac99d15448e2265a848d4d83d19f94c0904193ff5603a32e5db
# Build coredns docker image, and push to local repo
cd /tmp/tmp.F3GDo6z9Ys/src/github.com/coredns/coredns && \
  make coredns SYSTEM="GOOS=linux" && \
  docker build -t coredns . && \
  docker tag coredns localhost:5000/coredns && \
  docker push localhost:5000/coredns
make[1]: Entering directory '/tmp/tmp.F3GDo6z9Ys/src/github.com/coredns/coredns'
go get -u github.com/alecthomas/gometalinter
gometalinter --install golint
Installing:
  aligncheck
  deadcode
  dupl
  errcheck
  gas
  goconst
  gocyclo
  goimports
  golint
  gosimple
  gotype
  gotypex
  ineffassign
  interfacer
  lll
  megacheck
  misspell
  safesql
  staticcheck
  structcheck
  unconvert
  unparam
  unused
  varcheck
gometalinter --deadline=1m --disable-all --enable=gofmt --enable=golint --enable=vet --exclude=^vendor/ --exclude=^pb/ ./...
go generate coredns.go
(cd /tmp/tmp.F3GDo6z9Ys/src/github.com/mholt/caddy 2>/dev/null              && git checkout -q master 2>/dev/null || true)
(cd /tmp/tmp.F3GDo6z9Ys/src/github.com/miekg/dns 2>/dev/null                && git checkout -q master 2>/dev/null || true)
(cd /tmp/tmp.F3GDo6z9Ys/src/github.com/prometheus/client_golang 2>/dev/null && git checkout -q master 2>/dev/null || true)
(cd /tmp/tmp.F3GDo6z9Ys/src/golang.org/x/net 2>/dev/null                    && git checkout -q master 2>/dev/null || true)
(cd /tmp/tmp.F3GDo6z9Ys/src/golang.org/x/text 2>/dev/null                   && git checkout -q master 2>/dev/null || true)
(cd /tmp/tmp.F3GDo6z9Ys/src/github.com/coredns/forward 2>/dev/null          && git checkout -q master 2>/dev/null || true)
go get -u github.com/mholt/caddy
go get -u github.com/miekg/dns
go get -u github.com/prometheus/client_golang/prometheus/promhttp
go get -u github.com/prometheus/client_golang/prometheus
go get -u golang.org/x/net/context
go get -u golang.org/x/text
go get -u github.com/coredns/forward
# cd /tmp/tmp.F3GDo6z9Ys/src/github.com/coredns/coredns; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull  

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/ pr-1444

package github.com/coredns/coredns/core/dnsserver: exit status 1
Makefile:27: recipe for target 'godeps' failed
make[1]: *** [godeps] Error 1
make[1]: Leaving directory '/tmp/tmp.F3GDo6z9Ys/src/github.com/coredns/coredns'
Makefile:34: recipe for target 'build-docker' failed
make: *** [build-docker] Error 2
# Clean up
sh ./build/kubernetes/minikube_teardown.sh
./build/kubernetes/minikube_teardown.sh: 6: kill: No such process

Deleting local Kubernetes cluster...
~~~

**Comment by fturib** [comment]
The fix of the ci (and the local build in branch) issue is not merged yet #1435 
it is related to add of 'forward" plugin in the build.

Can you have a look at that PR ? and merge if ok ? 
Thanks!

**Comment by miekg** [comment]
That doesn't make sense. And this works fine on travis?

**Comment by johnbelamaric** [comment]
Issue is that go get -u tries to pull in coredns/coredns since it is a dependency for forward. But it also checks if the coredns/coredns is from the right repo (and I think branch but not sure), which it isn't because it's already there after being checked out as part of the PR. All Chris's change did was remove that check.

**Comment by johnbelamaric** [comment]
ok, hope you don't mind I rebased on master and pushed it up. should be able to run integration tests now.

**Comment by chrisohaver** [comment]
It might work fine on travis because I think it operates in "headless mode"  ... i.e. not in a real branch.

**Comment by chrisohaver** [comment]
I mean "detached head" mode ...

**Comment by miekg** [comment]
that's fine. thanks!

**Comment by miekg** [comment]
Now the bigger question... do we want this? And making *forward*  the new proxy - which is a big change.
While leaving proxy around obviously.

**Comment by miekg** [comment]
Once I'll merge 'include-forward' I'll rebase.

One question though: Each `upstream` creates a proxy that healtchcecks that upstream (aggressively) - there is no code yet that dedups these healthchecks. Should we healthcheck each of these upstreams, or just go without it? WDYT @johnbelamaric

**Comment by johnbelamaric** [comment]
What do you mean by de-dups? How are there dups? You mean because the same upstream host may be listed in multiple upstreams? Or something else?

Ideally I think we should only health check if we don't have any user queries coming through. If we are seeing successfully queries flowing, there doesn't seem to be a need for an artificial health check. If we see a bunch of error responses then maybe we start health checking once we mark it unhealthy. Or is that what we did in proxy and we decided it was too complex, and we should just simplify and make it always health check. I am losing track!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Forward (#144..." ]
>What do you mean by de-dups? How are there dups? You mean because the same upstream host may be listed in multiple upstreams? Or something else?

If we have multiple upstream statement that all have an idential IP:Port, each 
we get its own HC goroutine - which can add up.

>Ideally I think we should only health check if we don't have any user queries 
>coming through. If we are seeing successfully queries flowing, there doesn't 
>seem to be a need for an artificial health check. If we see a bunch of error 
>responses then maybe we start health checking once we mark it unhealthy. Or is 
>that what we did in proxy and we decided it was too complex, and we should just 
>simplify and make it always health check. I am losing track!

Yes, indeed adds a bunch of complexity, it makes sense to keep the healtchecking 
code simple. The inband checking in *forward* is simplfying things enormously. 

One of the problems is that if an nameserver on the internet (i.e. beyond the 
proxy) time outs, it looks like our upstream is failing - this is biting *proxy* 
currently. I.e. this would trigger a healthcheck but our upstream is probably 
fine.

Throttling healtcheck queries bases on current load is an interesting idea 
though, but we also allow healthchecks to disabled in *forward*, which could 
mean we can trigger the same failure mode (i.e. marking something down and never 
marking it healthy again)

Trigger on an upstream's error (even though that may not be *our* upstream's 
fault) and then stopping once it is concidered healthy can work - this should 
also be enabled by default; to avoid corner cases.

I'll ponder this a bit and update the current 'include-forward' PR.

/Miek

--
Miek Gieben

**Comment by UladzimirTrehubenka** [comment]
Miek, you also should change in /core/dnsserver/server.go function NewServer():
```
if stack.Name() == "chaos" || stack.Name() == "proxy" {
    s.classChaos = true
}
```
replace with
```
if stack.Name() == "chaos" || stack.Name() == "proxy" || stack.Name() == "forward" {
    s.classChaos = true
}
```

**Comment by miekg** [comment]
Oh nice find @UladzimirTrehubenka. yes.

Pretty terrible and manual way of doing things, but may be good enough for now.

**Comment by miekg** [comment]
closing this, maybe int the future

**Pull request closed without merging**
