### PR TITLE
Plugin/metrics - Starting/stopping tuning for the listener and HTTPServer

### PR DESCRIPTION
**Pull request by fturib**
### 1. Why is this pull request needed and what does it do?
Initial problem is:
1- plugin metrics fail to follow metric directive after 2 restarts
2- plugin metrics fail to start listener (sometime ...)

Point 1 - is fixed by modifying the interaction with uniqAddr = Unset the usage of Addr when shutdown the listener. It ensures the new metrics setup will initialize - if needed - a new uniqAddr *with its own OnStart function*

Point 2, after investigation, seems due to latency in releasing the socket on some OS platform. Works great on Mac OS. But our install on Alpine needs a delay before being able to reuse the listener.
=> add a second retry for acquiring the listener after 1sec delay, if first is failing.

NOTE: In order to show the failing point 1, I created a test in "test_reload". However I found that the service metrics was still running after listener is down (???), unless we stop the HTTP Server with Shutdown instead of Close.
I added this change in the code to have a proper closing.

### 2. Which issues (if any) are related?
#1848 (for point 2)
There is no issue created for point 1.

### 3. Which documentation changes (if any) need to be made?
I do not think it needs. only fix or tuning.

### CODE REVIEW

**Comment by fturib** [comment]
Hum.. something is wrong in my PR.
It shows the diff on files that are just coming from a merge of main.

**Comment by fturib** [comment]
I am a bit confused with the commit. And a rebase does not seems to help.
I will rebuild the diff on my code on top of a branch created from master.

**Comment by chrisohaver** [comment]
> But our install on Alpine 

Are you referring to the docker container here?  CoreDNS dropped alpine in 1.1.4.

>  will rebuild the diff on my code on top of a branch created from master.

Make sure your master isn't corrupted.

**Comment by fturib** [comment]
CorreDNS does not provide image with alpine, but our usage in IB is still based on alpine OS

**Pull request closed without merging**
