### PR TITLE
Provide access to Dnstap writer

### LINKED ISSUE #1075: Make Writer in Tapper available to enable middleware to write custom DNS tap messages
Add a GetWriter() function into Tapper interface to return the Writer object in DnsTap so that any middleware can write its own custom DNS tap messages.

### PR DESCRIPTION
**Pull request by rdrozhdzh**
Enable other plugins (middleware) to write custom DNS tap messages

 Fixes #1075

### CODE REVIEW

**Comment by johnbelamaric** [comment]
I don't think this is needed, as `Out` is exported. Also `Get` is not idiomatic in Go.

**Comment by rdrozhdzh** [comment]
Other middlewares can only get access to Tapper interface, not to Dnstap object itself. Please let me know if I missed anything

**Comment by miekg** [comment]
If you want to access the dnstap struct, something like this should work
~~~
	c.OnStartup(func() error {
		m := dnsserver.GetConfig(c).Handler("dnstap")
		if m == nil {
			return nil
		}
		if x, ok := m.(dnstap.Dnstap); ok {
			x.Out // do you thing
		}
		return nil
	})
~~~

**Comment by miekg** [comment]
bigger question is: why do we need or want this?

**Comment by rdrozhdzh** [comment]
Thank you Miek.
The idea was to allow sending customized dnstap messages along with standard ones. By customized I mean the messages which are not defined in https://github.com/dnstap/golang-dnstap/blob/master/dnstap.pb/dnstap.proto

**Comment by johnbelamaric** [comment]
Can we tweak the TapBuilder for this?

**Comment by rdrozhdzh** [comment]
TapBuilder could only construct message if it knows the definition of the message. I think it is not desirable to make dnstap middleware dependent on some external definitions

**Comment by 2buisson** [comment]
Maybe `Dnstap(tap.Dnstap)` is what you want? It could replace `Tapper.TapMessage(*tap.Message)` I agree.

**Comment by huynhmb359** [comment]
@varyoo,  not sure I understand your suggestion.   Could you please clarify and give an example?  Thnx.

**Comment by rdrozhdzh** [comment]
Oh, @varyoo, you mean the changes from your new PR? Yes, it might work, assuming that dnstap middleware references extendable Dnstap message, see PR https://github.com/dnstap/golang-dnstap/pull/14

**Comment by rdrozhdzh** [comment]
Closing this PR, since the approach proposed by @miekg can be used instead

**Pull request closed without merging**
