### PR TITLE
request: cleanup code based on staticcheck warnings

### PR DESCRIPTION
**Pull request by hwdef**
### 1. Why is this pull request needed and what does it do?
cleanup code based on staticcheck warnings

### CODE REVIEW

**Comment by miekg** [comment]
can you do this for the entirety of the codebase core + plugin + tests and just sent one big PR. Bonus points for integrating this with travis

**Comment by hwdef** [comment]
@miekg 
I fix some other files.

**Comment by hwdef** [comment]
@miekg
Cloud you please approve this PR?

**Comment by miekg** [comment]
no, travis build fails

**Comment by hwdef** [comment]
@miekg 
Someone submitted the same code as me after me and was merged,which caused my code to conflict.
This repository is not friendly,I am very disappointed.

**Comment by miekg** [comment]
yes, that happens. 

> This repository is not friendly,I am very disappointed.

yes, LOL

**Pull request closed without merging**
