### PR TITLE
Docker: drop alpine

### PR DESCRIPTION
**Pull request by miekg**
Create a multistage docker build image that uses debian to install certs
and then create the final image by using FROM: scratch. This creates a
(slightly) smaller images and drops busybox and alpine.

### CODE REVIEW

**Comment by yongtang** [comment]
How about bind-tools in alpine? dnsutils in Debian?

**Comment by nberlee** [comment]
`/etc/ssl/certs` is the minimum needed for go root ca checking. No need for the parent `/etc/ssl` directories and `/etc/ca-certificates`

**Comment by miekg** [comment]
thanks @nberlee made that change

@yongtang does it add much to have those tools in the docker image? For that to work we need to copy /usr, /lib and maybe more (that added up to 200M in a quick test I did)

**Comment by yongtang** [comment]
@miekg I am actually fine not to add those tools. I saw `bind-tools` was installed before with `alpine`, not sure the initial usage, so was asking about it.

**Comment by miekg** [comment]
@yongtang I think this change also allows us to add certs to all other images instead of only amd64, because the second stage only uses COPY instead of running actually commands, also the docker makefile part is now broken I think

**Comment by stp-ip** [comment]
Sidenote. Debugging can be done attaching to the process id. This will most likely become much more common in Kubernetes too.

**Pull request merged**
