### PR TITLE
Up to DNS version 1.1.0

### PR DESCRIPTION
**Pull request by miekg**
Upgrade to new dns lib version; that saw multiple improvements; some
patch releases are in the pipeline.

The big thing here is the removal of ErrTruncated, so we need to deal
with this slightly different in the forward plugin. It removed the
entire truncated.go logic and just checks the message for .Truncated (if
there is a message) and retries with tcp.

### 3. Which documentation changes (if any) need to be made?

### CODE REVIEW

**Comment by yongtang** [comment]
The Travis CI failed on benchmark:
```
forward/forward.go:119:14: undefined: dns.ErrTruncated
forward/truncated.go:15:12: undefined: dns.ErrTruncated
```

I believe the issue could be resolved once the PR is merged in.

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by chrisohaver** [comment]
> I believe the issue could be resolved once the PR is merged in.

I thought Travis checks PRs on top of master when testing (i.e. merged with master).

**Comment by miekg** [comment]
Hmmm, yeah that makes the benchmark thing a bit brittle (wish we had an easier way to benchmark).
I'll send a PR to disable this for the time being as we're not actually doing anything with thsese runs.

~~~
git checkout master
Warning: you are leaving 2 commits behind, not connected to
any of your branches:
  c2889fa Merge f41e4a94f6d58ee99db11a15a61600c144831368 into 39ad7e499ee4af832fac6af89bbfaf8aba8f6323
  f41e4a9 Up to DNS version 1.1.0
If you want to keep them by creating a new branch, this may be a good time
to do so with:
 git branch <new-branch-name> c2889fa
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
> old
( cd plugin; go test -run=NONE -bench=. -benchmem=true -tags 'etcd' ./... ) >> old
# github.com/coredns/coredns/plugin/forward [github.com/coredns/coredns/plugin/forward.test]
forward/forward.go:119:14: undefined: dns.ErrTruncated
forward/truncated.go:15:12: undefined: dns.ErrTruncated
make: *** [travis] Error 2
~~~

**Pull request merged**
