### PR TITLE
[plugin/kubernetes]: Fix `ignore empty_service` for ExternalName type.

### LINKED ISSUE #2688: plugin/kubernetes: ignore empty_service works incorrect for ExternalName services
CoreDNS-1.4.0
---
Corefile:
```
    .:53 {
        errors
        health
        cache 30
        kubernetes test.local {
            ttl 30
            pods verified
            fallthrough
        }
        loadbalance round_robin
        prometheus 0.0.0.0:9153
        proxy . 10.10.10.10
    }
```
Service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
    node: server1
  name: test-server1
  namespace: default
spec:
  externalName: 10-0-0-10.default.pod.test.local
  selector:
    app: test
    node: server1
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}

```
Check DNS:
```
root@test-bqlqw:/# nslookup test-server1
Server:         10.3.0.10
Address:        10.3.0.10#53

test-server1.default.svc.test.local  canonical name = 10-0-0-10.default.pod.test.local.
Name:   10-0-0-10.default.pod.test.local
Address: 10.0.0.10
```
Add ignore empty_service to Corefile:
```
    .:53 {
        errors
        health
        cache 30
        kubernetes test.local {
            ttl 30
            pods verified
            ignore empty_service   # <<<<<
            fallthrough
        }
        loadbalance round_robin
        prometheus 0.0.0.0:9153
        proxy . 10.10.10.10
    }
```
Result:
```
root@test-bqlqw:/# nslookup test-server1
Server:         10.3.0.10
Address:        10.3.0.10#53

** server can't find test-server1: NXDOMAIN
```
Another services works fine:
```
root@test-bqlqw:/# nslookup web-ui
Server:         10.3.0.10
Address:        10.3.0.10#53

Name:   web-ui.default.svc.test.local
Address: 10.0.0.177
```

### PR DESCRIPTION
**Pull request by dilyevsky**
Do not return NXDOMAIN for ExternalName Services when `ignore empty_service` option is set.

Fixes: #2688

Also:
* Update tests
* Run `gofmt -w plugin/kubernetes`
* Run `go mod tidy`

### CODE REVIEW

**Comment by chrisohaver** [comment]
Looks fine, but not sure about lumping in this many unrelated changes to a one line fix...

**Comment by johnbelamaric** [comment]
Yes, please break this into three separate PRs.

**Comment by miekg** [comment]
See https://github.com/coredns/coredns/pull/2773 for a fmt one, ran gofmt -w -s on everything

**Comment by dilyevsky** [comment]
Sorry fell off my radar. Will undo those change and re-push today

**Comment by chrisohaver** [comment]
ping @dilyevsky

**Comment by chrisohaver** [comment]
closing in favor of #2823

**Pull request closed without merging**
