### PR TITLE
plugin/kubernetes: nil check before MetaNamespaceKeyFunc

### PR DESCRIPTION
**Pull request by chrisohaver**
### 1. Why is this pull request needed and what does it do?

Avoid panic and subsequent "dead" endpoints informer by checking for nil in the index key func.
This is a _workaround_ what I suspect are two upstream bugs in the k8s api libs:
* that nil endpoints are added to the informer queue in the first place
* that the panic causes the informer to stop receiving/processing new events.

I verified that this not only avoids the panic, but it also allows the informer to process missed events, and continue processing endpoint changes after the nil endpoint is encountered. IOW, it prevents the informer from dropping dead.

### 2. Which issues (if any) are related?

#3860

### 3. Which documentation changes (if any) need to be made?

none

### 4. Does this introduce a backward incompatible change or deprecation?

no

### CODE REVIEW

**Comment by johnbelamaric** [comment]
Chris this looks good to me. Can you look into the k8s upstream issue too?

**Comment by miekg** [comment]
can we reference (any) upstream issue in a comment in the code as well?

**Comment by chrisohaver** [comment]
Actually - I'm thinking now that this may be a problem in our processor functions - not an upstream problem...  looking into it ...

**Comment by multi-io** [comment]
While we're waiting for this or an equivalent fix to be released, can we identify the coreos version where this bug came in, and would it be advisable to temporarily downgrade to a previous version? (when using coredns as the kube-dns provider in a k8s cluster)

**Comment by chrisohaver** [comment]
> Actually - I'm thinking now that this may be a problem in our processor functions - not an upstream problem... looking into it ...

Yeah - I'm more certain that this is an issue with how we handle the api object conversions. They do not handle deletion tombstones.  For now, the conversion funcs just return nil when these are encountered.  I think I see how to fix it without too much refactoring...

Closing this draft PR, there is a better fix.

**Comment by chrisohaver** [comment]
> Closing this draft PR, there is a better fix.

See #3887

**Pull request closed without merging**
