### PR TITLE
deps update k8s

### PR DESCRIPTION
**Pull request by miekg**
manual update because of conflicts in: #3677 and #3678

### CODE REVIEW

**Comment by miekg** [comment]
sigh
~~~
# k8s.io/client-go/rest
../../../../.go_workspace/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
k8s.io/apimachinery/pkg/apis/meta/v1beta1
~~~

**Comment by chrisohaver** [comment]
@miekg, I can take a stab at this if you like.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] deps update k..." ]
>@miekg, I can take a stab at this if you like.

ack, please do

**Comment by zouyee** [comment]
https://github.com/kubernetes/client-go#kubernetes-tags

**Pull request closed without merging**
