### PR TITLE
plugin/forward: check TC correctly on reply.

### PR DESCRIPTION
**Pull request by miekg**
Add test for this.

### CODE REVIEW

**Comment by miekg** [comment]
I'll work on adding another test that exercises the retry bit on TC and see what falls out of that.

**Comment by miekg** [comment]
added Forward test as well in here.

**Comment by grobie** [comment]
Thanks for working on this and adding a test!

I can confirm this fixes the panic reported in #1667. I have to admit I'd wish for a simpler implementation in general. A truncated response from an upstream server is first parsed, an internal error code gets returned with it, then the parsed response is thrown away, a new message is created based on the original request, and finally that message is compared against the original request, even though they will always be the same. I can see that you don't want to change miekg/dns anymore to not return `ErrTruncated`, but that seems to be the source of all the complication here.

It'd be great to extend the test to verify that a truncated response from an upstream server is actually returned by plugin/forward. At the moment, it's still thrown away and a custom message is returned due to the error handling in connect.go reported in #1669.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>Thanks for working on this and adding a test!
>
>I can confirm this fixes the panic reported in #1667. I have to admit I'd wish for a simpler implementation in general. A truncated response from an upstream server is first parsed, an internal error code gets returned with it, then the parsed response is thrown away, a new message is created based on the original request, and finally that message is compared against the original request, even though they will always be the same. I can see that you don't want to change miekg/dns anymore to not return `ErrTruncated`, but that seems to be the source of all the complication here.
>
>It'd be great to extend the test to verify that a truncated response from an upstream server is actually returned by plugin/forward. At the moment, it's still thrown away and a custom message is returned due to the error handling in connect.go reported in #1669.

Good points. I'll follow up with these.

**Pull request merged**
