### PR TITLE
[branched] Parse request

### PR DESCRIPTION
**Pull request by miekg**
https://github.com/coredns/coredns/pull/899 on a new branch

### CODE REVIEW

**Comment by johnbelamaric** [comment]
FYI, I tried SRV for an external service in kube-dns, and it returns an incorrect SRV record (as this one did). The question is what to do in these scenarios:

@chrisohaver @miekg 
1) There *is not* an SRV record for the name in the upstream, and port info *is not* specified in the external service definition. I think return no data.
2) There *is* an SRV record in the upstream for that name, and port info *is not* specified in the external service definition. I think return the upstream SRV (which would be the normal DNS thing to do, correct?)
3) There *is not* an SRV record for the name in the upstream, and port info *is* specified in the external service definition. I think return a synthetic SRV based on external service definition.
4) There *is* an SRV record for the name in the upstream, and port info *is* specified in the external service definition. Umm...not sure here. Probably prefer the K8s external service definition. Or maybe return both.

We probably should open up this discussion in kubernetes/dns

**Comment by chrisohaver** [comment]
@johnbelamaric, there is an open issue for how to handle SRV answers for external services: #817.

Agree on your suggestions - except for # 4.  IMO we'd probably want to merge the results of both.  In fact, that logic would apply to 1-3 as well. Just merging results of both local definitions and upstream records would be the same result as described in 1-3.

**Comment by chrisohaver** [comment]
> except for # 4

Just noticed you said "Or maybe return both." :) Yes, i agree.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] [branched] Pa..." ]
>FYI, I tried SRV for an external service in kube-dns, and it returns an incorrect SRV record (as this one did). The question is what to do in these scenarios:
>
>@chrisohaver @miekg
>1) There *is not* an SRV record for the name in the upstream, and port info *is not* specified in the external service definition. I think return no data.
>2) There *is* an SRV record in the upstream for that name, and port info *is not* specified in the external service definition. I think return the upstream SRV (which would be the normal DNS thing to do, correct?)
>3) There *is not* an SRV record for the name in the upstream, and port info *is* specified in the external service definition. I think return a synthetic SRV based on external service definition.
>4) There *is* an SRV record for the name in the upstream, and port info *is* specified in the external service definition. Umm...not sure here. Probably prefer the K8s external service definition. Or maybe return both.
>
>We probably should open up this discussion in kubernetes/dns

Yes that makes sense.

Not replying in depth here, but just a general feeling. For NSD the quote 
"Garbage in, Garbage out" worked really well. If you start to put smartness into 
the system it becomes hard to draw a line. For NSD this was mostly performance 
driven.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
Merging this (now tests don't fail in chris-miek-k8s)

**Pull request merged**
