### PR TITLE
Make CoreDNS a server type plugin for Caddy

### PR DESCRIPTION
**Pull request by miekg**
Remove code we don't need and port all middleware over.

### CODE REVIEW

**Comment by mrichmon** [comment]
LGTM.

Some Makefile targets are broken. Fixes are:

```
diff --git a/Makefile b/Makefile
index d8cf42b..c0477ac 100644
--- a/Makefile
+++ b/Makefile
@@ -8,16 +8,16 @@ DOCKER_IMAGE_NAME := $$USER/coredns


 all:
-   go build $(BUILD_VERBOSE) -ldflags="-s -w"
+   go build $(BUILD_VERBOSE) -ldflags="-s -w" ./...

 .PHONY: docker
 docker: all 
-   GOOS=linux go build -a -tags netgo -installsuffix netgo -ldflags="-s -w"
+   GOOS=linux go build -a -tags netgo -installsuffix netgo -ldflags="-s -w" ./...
    docker build -t $(DOCKER_IMAGE_NAME) .

 .PHONY: deps
 deps:
-   go get ${BUILD_VERBOSE}
+   go get ${BUILD_VERBOSE} ./...

 .PHONY: test
 test:
@@ -32,7 +32,7 @@ testk8s:

 .PHONY: testk8s-setup
 testk8s-setup:
-   go test -v ./core/setup -run TestKubernetes
+   go test -v ./middleware/kubernetes/... -run TestKubernetes

 .PHONY: clean
 clean:
```

**Comment by miekg** [comment]
Thanks for looking, appreciated.

The build is fucked in more than 1 way: this is my plan to fix it: https://forum.caddyserver.com/t/building-coredns-automatically/481/16?u=miekg

**Comment by mrichmon** [comment]
For what it’s worth, I just did:

$ go get ./…
$ go build ./…

With your changes applied to a branch and it all just worked.

I then destroyed my dev VM, built the VM again (my VM is committed to github and is provisioned via a bunch of scripts and vagrant). Then with my makefile changes did:

$ make deps
$ make
$ make docker
$ make testk8s

And then ran a couple of manual coredns tests for the kubernetes middleware.

So, it may be ugly right now. But it’s at least working.

…Michael

**Comment by miekg** [comment]
What's the exe you run? `caddy` or `coredns`?

**Comment by mrichmon** [comment]
Coredns.

## 

On the road...

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Make CoreDNS a ..." ]

> Coredns.

yeah... What happens when you delete that and rerun your tests...? :)

**Comment by mrichmon** [comment]
duh. `go clean` doesn't get as clean as I assumed.

Looks like Caddy isn't designed to support middleware that is separate from the Caddy codebase.

I tried using a `coredns.go` file that contains:

```
package main

import (
        "github.com/mholt/caddy/caddy/caddymain"
)

var run = caddymain.Run

func main() {
    run()
}
```

This provides me with a `coredns` binary with Caddy functionality. But It does not link in the coredns middleware that is available below the current directory.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Make CoreDNS a ..." ]

> duh. `go clean` doesn't get as clean as I assumed.
> 
> Looks like Caddy isn't designed to support middleware that is separate from the Caddy codebase.
> 
> I tried using a `coredns.go` file that contains:
> 
> ```
> package main
> 
> import (
>        "github.com/mholt/caddy/caddy/caddymain"
> )
> 
> var run = caddymain.Run
> 
> func main() {
>    run()
> }
> ```
> 
> This provides me with a `coredns` binary with Caddy functionality. But It does not link in the coredns middleware that is available below the current directory.

Interesting. You still need to run the `plugin_generate.go` to "fix" caddy to
call the CoreDNS middleware. After that it should work....

i.e. rename empty.go to coredns.go (copy the above stuff in) and remote
buildcaddy_generate.go

/Miek

## 

Miek Gieben

**Comment by mrichmon** [comment]
Almost. Based on binary size, this looks like the k8s libraries are compiled into `coredns` using this branch at commit: 719833a11492a18cc3e9d1ce1c56d95c2a9ab847

I can get the k8s middleware loaded using the file `conf/k8sCorefile` and the command: `./coredns -type dns -conf Corefile  -log stdout`

Would be nice if the `coredns.go` file could automatically set the "type" and "conf" file.

However, I'm seeing that DNS queries are not being resolved correctly. Looks like a SERVERFAIL status on the response. I need to debug this.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Make CoreDNS a ..." ]

> Almost. Based on binary size, this looks like the k8s libraries are compiled into `coredns` using this branch at commit: 719833a11492a18cc3e9d1ce1c56d95c2a9ab847
> 
> I can get the k8s middleware loaded using the file `conf/k8sCorefile` and the command: `./coredns -type dns -conf Corefile  -log stdout`
> 
> Would be nice if the `coredns.go` file could automatically set the "type" and "conf" file.

For the "conf", a PR to Caddy has been sent out. The type is interesting. I need
to look at that, should be relatively easy.

> However, I'm seeing that DNS queries are not being resolved correctly. Looks like a SERVERFAIL status on the response. I need to debug this.

I had some problems what that too today (but with other middleware). That turned
to be mostly stupid mistakes (from me).

Is it easy to stand up coredns+k8s _without_ k8s and get something sane out of
coredns?

/Miek

## 

Miek Gieben

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Make CoreDNS a ..." ]

> Almost. Based on binary size, this looks like the k8s libraries are compiled into `coredns` using this branch at commit: 719833a11492a18cc3e9d1ce1c56d95c2a9ab847
> 
> I can get the k8s middleware loaded using the file `conf/k8sCorefile` and the command: `./coredns -type dns -conf Corefile  -log stdout`
> 
> Would be nice if the `coredns.go` file could automatically set the "type" and "conf" file.

"type" is done and pushed.

/Miek

## 

Miek Gieben

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Make CoreDNS a ..." ]

> However, I'm seeing that DNS queries are not being resolved correctly. Looks like a SERVERFAIL status on the response. I need to debug this.

Any luck?

/Miek

## 

Miek Gieben

**Comment by mrichmon** [comment]
> Is it easy to stand up coredns+k8s _without_ k8s and get something sane out of
> coredns?

The `contrib/kubernetes/testscripts/start_k8s_with_services.sh` script startups up kubernetes in docker containers together with a few k8s services. The only dependency is on a working docker installation on the host.

After running the start script, `coredns` started with the conf/k8sCorefile will allow you to resolve queries such as:
- `webserver.demo.coredns.local`
- `*.demo.coredns.local`

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Make CoreDNS a ..." ]

> > Is it easy to stand up coredns+k8s _without_ k8s and get something sane out of
> > coredns?
> 
> The `contrib/kubernetes/testscripts/start_k8s_with_services.sh` script startups up kubernetes in docker containers together with a few k8s services. The only dependency is on a working docker installation on the host.

Nice.

> After running the start script, `coredns` started with the conf/k8sCorefile will allow you to resolve queries such as:
> - `webserver.demo.coredns.local`
> - `*.demo.coredns.local`

The middleware is chained in and the query reaches the hander.go in kubernetes.

(For some reason it (docker/k8s) does not start on my laptop so I couldn't take
a closer look)

/Miek

## 

Miek Gieben

**Comment by mrichmon** [comment]
Yeah, lots of debug prints. Call during query resolution is entering controller::GetServiceList() and then something off is happening in the line `svcList, err := dns.svcLister.List()`

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Make CoreDNS a ..." ]

> Yeah, lots of debug prints. Call during query resolution is entering controller::GetServiceList() and then something off is happening in the line `svcList, err := dns.svcLister.List()`

interesting, I didn't get that far. Note this code _hasn't_ been touched by the
refactor.

**Comment by mrichmon** [comment]
> interesting, I didn't get that far. Note this code _hasn't_ been touched by the
> refactor.

Agreed. However, this code is using a number of background threads/channels. Previously when I ran the k8s middleware with the argument '-v 100' there would be periodic log messages from the k8s framework processing background notification events.

I suspect that something in the changes or Caddy may have altered the thread processing. But this is just a hunch.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Make CoreDNS a ..." ]

> > interesting, I didn't get that far. Note this code _hasn't_ been touched by the
> > refactor.
> 
> Agreed. However, this code is using a number of background threads/channels. Previously when I ran the k8s middleware with the argument '-v 100' there would be periodic log messages from the k8s framework processing background notification events.
> 
> I suspect that something in the changes or Caddy may have altered the thread processing. But this is just a hunch.

That _area_ did change a bit, because the caddy.OnStartup (and friends) has
changed (a little). You might want to focus there. This would ke
kubernetes/setup.go

/Miek

## 

Miek Gieben

**Comment by mrichmon** [comment]
> That _area_ did change a bit, because the caddy.OnStartup (and friends) has
> changed (a little). You might want to focus there. This would ke
> kubernetes/setup.go

Exactly that.

A quick hack got things working:

```
    err = kubernetes.StartKubeCache()
    if err != nil {
        return err
    }
    //c.OnStartup(kubernetes.StartKubeCache)
```

Now to work out why OnStartup isn't doing what I expected.

**Comment by mrichmon** [comment]
Fixed. Merging changes into this branch.

**Comment by miekg** [comment]
Pushed some, re-enabled all tests in tests/ dir - still failing once - will clean that up shortly

**Comment by miekg** [comment]
@mrichmon something still fails: https://travis-ci.org/miekg/coredns/builds/153673204
(and I can't test on my laptop because (as said) the whole k8s does not come up :(  )

**Comment by mrichmon** [comment]
@miekg I'm on it.

**Comment by mrichmon** [comment]
This appears to be the same problem as earlier today where the KubeCache goroutines are not being started when the server starts up. Tests use different code paths to start the server.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Make CoreDNS a ..." ]

> This appears to be the same problem as earlier today where the KubeCache goroutines are not being started when the server starts up. Tests use different code paths to start the server.

Hmmm, I would have hoped by using caddy.Start this would be all using the normal
Caddy startup sequence and thus the same on.Startup stuff. In fact I can't see
why it wouldn't...?

**Comment by mrichmon** [comment]
> Caddy startup sequence and thus the same on.Startup stuff. In fact I can't see
> why it wouldn't...?

I'm reading the comments at the top of mholt/caddy/caddy.go

Looks like steps 1 & 2 are not performed by the coredns/test/server.go::CoreDNSServer(...) function.

I'm having trouble finding a way to set the Caddy serverType to "dns". This appears to be necessary based on the implementation of LoadCaddyfile().

Still looking.

**Comment by miekg** [comment]
Ah. Then it makes sense we need to do some of those steps as well. I can
check this when I get to the airport

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Make CoreDNS a ..." ]

> Looks like steps 1 & 2 are not performed by the coredns/test/server.go::CoreDNSServer(...) function.
> 
> I'm having trouble finding a way to set the Caddy serverType to "dns". This appears to be necessary based on the implementation of LoadCaddyfile().

I plug in the normal registration to register "dns" at the top of
test/server.go. This enabled the dns server type.

Also, I'm looking at caddy.Start, that calls `startWithListenerFds`, which
does run on the startup functions. And _if_ there is an error it is returned,
which should be seen in the tests...

/Miek

## 

Miek Gieben

**Comment by miekg** [comment]
I'm inclined to merge this even with the failing tests.... Just to get this PR over with...

**Comment by miekg** [comment]
actually fuck it

**Pull request merged**
