### PR TITLE
Introduce go vendor management using 'glide' tool (https://github.com/coredns/coredns/issues/610)

### PR DESCRIPTION
**Pull request by mstaneuka**

### CODE REVIEW

**Comment by johnbelamaric** [comment]
So, what would the process be for updating all the vendor code? Maybe we should have a make target that updates all vendor code.

What do we have to do if we wanted to add another package?

**Comment by yongtang** [comment]
I could see there are so many subpackges for `k8s.io/client-go`. That means updating it will have to go through so many lines in config file, not even to mention the vendoring code?

Do we need to include sub packages level? Could we just list `client-go`?

**Comment by mstaneuka** [comment]
> @johnbelamaric  So, what would the process be for updating all the vendor code? Maybe we should have a make target that updates all vendor code.

Generally it seems very hard to update glide.yaml automatically. What I see in other projects - vendor usually updated on demand either as a part of feature's PR or to fix some version specific issues. However some core dependencies could be updated from time to time.

Perhaps having reproducible environment is more important than keep in sync with latest version of every package we are using...

> @johnbelamaric  What do we have to do if we wanted to add another package?

We could either add some scripts similar to https://github.com/coreos/etcd/blob/master/scripts/updatedep.sh or add instructions e.g. to the README. I prefer not to use any scripts and use glide directly.

**Comment by mstaneuka** [comment]
> @yongtang I could see there are so many subpackges for k8s.io/client-go. That means updating it will have to go through so many lines in config file, not even to mention the vendoring code?
>
>Do we need to include sub packages level? Could we just list client-go?

If I'm correct originally ```subpackages``` has been added to get rid of transitive dependencies fetch for a subpackages we don't really use. E.g.
```
- package: github.com/foo
  subpackages:
  - bar
``` 
may lead to skipping deps fetch for  github.com/foo/spam (if github.com/foo/bar doesn't use github.com/foo/spam).

What I understand currently glide uses some code scanning to resolve such cases. So yes, we can remove  ```subpackages```. At lest it doesn't make any changes in the vendor

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Introduce go ..." ]
>> @johnbelamaric  So, what would the process be for updating all the vendor code? Maybe we should have a make target that updates all vendor code.
>
>Generally it seems very hard to update glide.yaml automatically. What I see in other projects - vendor usually updated on demand either as a part of feature's PR or to fix some version specific issues. However some core dependencies could be updated from time to time.
>
>Perhaps having reproducible environment is more important than keep in sync with latest version of every package we are using...
>
>> @johnbelamaric  What do we have to do if we wanted to add another package?
>
>We could either add some scripts similar to https://github.com/coreos/etcd/blob/master/scripts/updatedep.sh or add instructions e.g. to the README. I prefer not to use any scripts and use glide directly.

I'm in favor of vendoring (reluctantly :) ). How anyone any ideas how `go dep`
will do this? Get we play with that, when is it ready?

**Comment by mstaneuka** [comment]
Closing PR as vendoring was covered by https://github.com/coredns/coredns/pull/654

**Pull request closed without merging**
