### PR TITLE
Add benchmark result to GitHub PR

### PR DESCRIPTION
**Pull request by yongtang**
Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
benchmark                       old ns/op     new ns/op     delta
BenchmarkCacheResponse-2        3610          4176          +15.68%
BenchmarkFileLookupDNSSEC-2     44813         44172         -1.43%
BenchmarkFileParseInsert-2      776157        783933        +1.00%
BenchmarkFileLookup-2           6675          14987         +124.52%
BenchmarkCache-2                103           138           +33.98%
BenchmarkMinimalTTL-2           84.0          144           +71.43%
BenchmarkRequestDo-2            2.66          2.66          +0.00%
BenchmarkRequestSize-2          3.04          3.04          +0.00%
BenchmarkRequestScrub-2         5715          5744          +0.51%
BenchmarkCoreServeDNS-2         430           794           +84.65%

benchmark                       old allocs     new allocs     delta
BenchmarkCacheResponse-2        29             29             +0.00%
BenchmarkFileLookupDNSSEC-2     194            194            +0.00%
BenchmarkFileParseInsert-2      678            678            +0.00%
BenchmarkFileLookup-2           64             64             +0.00%
BenchmarkCache-2                0              0              +0.00%
BenchmarkMinimalTTL-2           0              0              +0.00%
BenchmarkRequestDo-2            0              0              +0.00%
BenchmarkRequestSize-2          0              0              +0.00%
BenchmarkRequestScrub-2         99             99             +0.00%
BenchmarkCoreServeDNS-2         5              5              +0.00%

benchmark                       old bytes     new bytes     delta
BenchmarkCacheResponse-2        512           512           +0.00%
BenchmarkFileLookupDNSSEC-2     6720          6720          +0.00%
BenchmarkFileParseInsert-2      116289        116290        +0.00%
BenchmarkFileLookup-2           2064          2064          +0.00%
BenchmarkCache-2                0             0             +0.00%
BenchmarkMinimalTTL-2           0             0             +0.00%
BenchmarkRequestDo-2            0             0             +0.00%
BenchmarkRequestSize-2          0             0             +0.00%
BenchmarkRequestScrub-2         5808          5808          +0.00%
BenchmarkCoreServeDNS-2         160           160           +0.00%

**Comment by yongtang** [comment]
@miekg Looks like it works, though I am using my own token to post the message. Do we have a coredns bot that can be used to post the message? The bot only needs a `public_repo` right in the setting for the token.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] [WIP] Add ben..." ]
>@miekg Looks like it works, though I am using my own token to post the message. Do we have a coredns bot that can be used to post the message? The bot only needs a `public_repo` right in the setting for the token.

Nice. Can't we make a token just for this?

**Comment by yongtang** [comment]
There is a `coredns-cibot` https://github.com/coredns-cibot though I don't have access to this machine account. /cc @chrisohaver

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] [WIP] Add ben..." ]
>There is a `coredns-cibot` https://github.com/coredns-cibot though I don't have access to this machine account. /cc @chrisohaver

I think we can just create another secret. Le'me check

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] [WIP] Add ben..." ]
>There is a `coredns-cibot` https://github.com/coredns-cibot though I don't have access to this machine account. /cc @chrisohaver

you can create multiple github token on https://github.com/settings/tokens
for the time being use a peronal one with few powers?

**Comment by yongtang** [comment]
Yes multiple tokens are possible. The comment only need `public_repo` access. I would prefer to use a bot to post the comment. Otherwise it will looks like my comments are all over the places.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] [WIP] Add ben..." ]
>Yes multiple tokens are possible. The comment only need `public_repo` access. I would prefer to use a bot to post the comment. Otherwise it will looks like my comments are all over the places.
>

ah, yes. I see, it's *you* who's posting. Yes that's suboptimal, we have corbot 
running on drone (github.com/miekg/dreck), that could do this, but still it 
needs access to the benchmark text.

/Miek

--
Miek Gieben

**Comment by yongtang** [comment]
@chrisohaver If you have the `coredns-cibot` credential, you can create a token with `public_repo` access, then in Travis CI you can replace `GITHUB_TOKEN` with the token you create. Then everything should work.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] [WIP] Add ben..." ]
>@miekg Looks like it works, though I am using my own token to post the message. Do we have a coredns bot that can be used to post the message? The bot only needs a `public_repo` right in the setting for the token.

Just linking to the right build from the details would work as well. You need to 
need callback into github then. But not sure if you can do this.

**Comment by chrisohaver** [comment]
>  If you have the coredns-cibot credential, you can create a token with public_repo access, then in Travis CI you can replace GITHUB_TOKEN with the token you create. Then everything should work.

Done

**Comment by miekg** [comment]
Prolly need to put a warning on the CPU benchmarks:

"The CPU benchmarks are performed on Travis VMs and vary widly between runs, you 
can't trust them. The memory benchmarks are OK"


>benchmark                       old ns/op     new ns/op     delta
>BenchmarkCacheResponse-2        3851          4103          +6.54%
>BenchmarkFileLookupDNSSEC-2     44949         39587         -11.93%
>BenchmarkFileParseInsert-2      708788        799236        +12.76%
>BenchmarkFileLookup-2           6710          14836         +121.10%
>BenchmarkCache-2                103           132           +28.16%
>BenchmarkMinimalTTL-2           83.6          159           +90.19%
>BenchmarkRequestDo-2            2.65          2.65          +0.00%
>BenchmarkRequestSize-2          3.03          3.02          -0.33%
>BenchmarkRequestScrub-2         6180          5843          -5.45%
>BenchmarkCoreServeDNS-2         444           812           +82.88%
>
>benchmark                       old allocs     new allocs     delta
>BenchmarkCacheResponse-2        29             29             +0.00%
>BenchmarkFileLookupDNSSEC-2     194            194            +0.00%
>BenchmarkFileParseInsert-2      678            678            +0.00%
>BenchmarkFileLookup-2           64             64             +0.00%
>BenchmarkCache-2                0              0              +0.00%
>BenchmarkMinimalTTL-2           0              0              +0.00%
>BenchmarkRequestDo-2            0              0              +0.00%
>BenchmarkRequestSize-2          0              0              +0.00%
>BenchmarkRequestScrub-2         99             99             +0.00%
>BenchmarkCoreServeDNS-2         5              5              +0.00%
>
>benchmark                       old bytes     new bytes     delta
>BenchmarkCacheResponse-2        512           512           +0.00%
>BenchmarkFileLookupDNSSEC-2     6720          6720          +0.00%
>BenchmarkFileParseInsert-2      116289        116289        +0.00%
>BenchmarkFileLookup-2           2064          2064          +0.00%
>BenchmarkCache-2                0             0             +0.00%
>BenchmarkMinimalTTL-2           0             0             +0.00%
>BenchmarkRequestDo-2            0             0             +0.00%
>BenchmarkRequestSize-2          0             0             +0.00%
>BenchmarkRequestScrub-2         5808          5808          +0.00%
>BenchmarkCoreServeDNS-2         160           160           +0.00%
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/coredns/coredns/pull/2123#issuecomment-424172956
/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
> Prolly need to put a warning on the CPU benchmarks:

If we're looking for reproducible CPU benchmarks, we could run this as part of the coredns/ci jobs, which run the tests on a physical server.

**Review by chrisohaver — APPROVED** [review]
lgtm

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add benchmark..." ]
>> Prolly need to put a warning on the CPU benchmarks:
>
>If we're looking for reproducible CPU benchmarks, we could run this as part of the coredns/ci jobs, which run the tests on a physical server.

good idea, we have that setup anyway; looking in travis this runs in two 
minutes.

**Pull request merged**
