### PR TITLE
Use strings.ToLower instead of manual implementation

### LINKED ISSUE #3291: strings.ToLower in core/dnsserver/server.go
Implement this:

https://github.com/miekg/dns/pull/1010

in core/dnsserver/server.go. This code is faster and less lines of code.

### PR DESCRIPTION
**Pull request by erbesharat**
### 1. Why is this pull request needed and what does it do?
Use strings.ToLower instead of manual implementation cause it's faster and has fewer lines of code.

### 2. Which issues (if any) are related?
fixes #3291 

### 3. Which documentation changes (if any) need to be made?
Nothing

### 4. Does this introduce a backward incompatible change or deprecation?
No

### CODE REVIEW

**Comment by miekg** [comment]
sorry, this is not correct, a lot more code can be deleted.

**Comment by miekg** [comment]
This might have been tricker than I anticipated, see #3304 for my attempt.

**Comment by erbesharat** [comment]
@miekg I should've read the code more carefully. When I tried to remove the first for loop some of the coverage tests in `/tests` started to fail and I thought it's necessary to keep it. Should we close this PR and merge yours instead?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Use strings.T..." ]
> Should we close this PR and merge yours instead?

that's the easiest way forward, I think. The alternative is that you roughly 
implement the same, which seems a bit of an overkill :)

**Comment by stp-ip** [comment]
Closing in favor of #3304

**Pull request closed without merging**
