### PR TITLE
middleware/whoareyou: add

### PR DESCRIPTION
**Pull request by artbin**
Add a new middleware that tells you coredns IP, port and transport.

### CODE REVIEW

**Comment by miekg** [comment]
Thanks!

But what does this add beyond the `whoami` middleware?

**Comment by artbin** [comment]
_whoami_ returns client IP, _whoareyou_ returns server IP.
_whoareyou_ allows you to create zero config environment, for example when dns server and http server working on 1 host.

**Comment by miekg** [comment]
I missed that. Note that the functionality you're looking for is called NSID https://tools.ietf.org/html/rfc5001 and we should probably implement that instead of this middleware.

Q: what information does this give you that you don't already know? Port is I think known. IP address can be retrieved or is already known. Transport maybe? But that also controlled by the client?

**Comment by artbin** [comment]
The module creates a list of all the addresses of the host, when the request comes from the client, it is necessary to compare the address of the client to one or more server addresses - locally or globally routable address? ipv4 or ipv6?

When you make changes in the configuration of network interfaces you do not need to edit the configuration of the coredns.

**Comment by artbin** [comment]
To obtain the address for the domain name http client sends a request to the dns server on port 53, the response returns dns server address. At this address http server listens to port 80. The client attempts to connect to http server on tcp protocol on port 80.

**Comment by miekg** [comment]
It would have been better to first open an issue that you were doing this, instead of sending the PR and only then having a discussion about it.

I think this middleware should live out-of-tree (there aren't good guidelines for that though #275). Nor is there an automatic way to build a coredns with this middleware.

**Comment by miekg** [comment]
Just as a general comment: I like how this PR has code, tests and documentation. Well done.

**Pull request closed without merging**
