### PR TITLE
fuzz: some cleanups

### PR DESCRIPTION
**Pull request by miekg**

### CODE REVIEW

**Comment by miekg** [comment]
this clears out any explicit plugin calling, just putting a fuzz.go in your plugin will enable the fuzzing.

(there needs to be a core fuzzing as well, and one for the corefile contents)

**Comment by yevgenypats** [comment]
@miekg this looks good! also can you bump the fuzzit version to 2.4.28 I made it a little less verbose (it spams the travis logs a bit).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] fuzz: some cl..." ]
>@miekg this looks good! also can you bump the fuzzit version to 2.4.28 I made it a little less verbose (it spams the travis logs a bit).

Where can I file feature request for fuzzit.dev?

**Comment by yevgenypats** [comment]
https://github.com/fuzzitdev/fuzzit

**Pull request merged**
