### PR TITLE
Moving TransferParse from file to its own package

### PR DESCRIPTION
**Pull request by bradbeam**
### 1. What does this pull request do?
Minor refactor of file.TransferParse to it's own package to prevent cyclic dependencies on the file plugin. 

### 2. Which issues (if any) are related?
N/A

### 3. Which documentation changes (if any) need to be made?
N/A

### CODE REVIEW

**Comment by miekg** [comment]
Thanks for splitting the PR - makes a lot easier.

Why do we hit the cyclec dep? file has bit from k8s?

Also might be nicer to name the new package 'parse' and the TranserParse function just Transfer, then it reads parse.Transfer.
We can also stuff other parse thingies in it later.

**Comment by bradbeam** [comment]
The main driver was to reduce the inter plugin dependencies. I'm fine with the rename.

**Comment by miekg** [comment]
I'm a bit worried about all those inter deps as well. After rename, lgtm

**Comment by bradbeam** [comment]
Renamed, should be good to go

**Comment by miekg** [comment]
Ok, gofmt and/or golint to make travis happy is still needed.

**Comment by johnbelamaric** [comment]
@chrisohaver something broke in the CI:

```
...
Successfully tagged coredns:latest
The push refers to a repository [localhost:5000/coredns]
Get http://localhost:5000/v2/: dial tcp [::1]:5000: getsockopt: connection refused
Makefile:16: recipe for target 'deploy-k8s' failed
make: *** [deploy-k8s] Error 1
# Clean up
sh ./build/kubernetes/minikube_teardown.sh
./build/kubernetes/minikube_teardown.sh: 6: kill: No such process

There is a newer version of minikube available (v0.24.1).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v0.24.1

To disable this notification, run the following:
minikube config set WantUpdateNotification false
Deleting local Kubernetes cluster...
Errors occurred deleting machine:  Error deleting host: minikube: Error loading host from store: Host does not exist: "minikube"
registry
registry
```

**Comment by chrisohaver** [comment]
@johnbelamaric, Looks like it may be a dockerd issue - i'll try restarting it...

**Comment by chrisohaver** [comment]
Restarting dockerd fixed the CI failure.

**Pull request merged**
