### PR TITLE
Up release to 1.2.0

### PR DESCRIPTION
**Pull request by miekg**
Set the version to 1.2.0, in preparation for our first, completely
automated release.

See #1954

Signed-off-by: Miek Gieben <miek@miek.nl>

### CODE REVIEW

**Comment by miekg** [comment]
lots of @greenpau for PRs lately. double checking the randomization in dreck

**Comment by miekg** [comment]
~~~
			rand.Seed(int64(time.Now().Nanosecond()))
			rand := rand.Intn(len(withoutPuller))
~~~
*should* be sufficient

**Review by greenpau — APPROVED** [review]

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Up release to..." ]
>greenpau approved this pull request.

/merge

**Comment by greenpau** [comment]
> lots of @greenpau for PRs lately. double checking the randomization in dreck

@miekg , I don't mind 😄 keeps me aware of the code base in rewrite 😃

**Pull request merged**
