### PR TITLE
Revert "plugin/kubernetes: Reduce memory usage: Use keys instead of indexes"

### PR DESCRIPTION
**Pull request by chrisohaver**
Reverts coredns/coredns#2167

Inexplicably, these changes increased memory usage when merged with the custom store solution.

### CODE REVIEW

**Review by fturib — APPROVED** [review]
LGTM.
It is kind of sad to revert here, there are good points (using keys instead new index, optim on the transfer, ...)

**Comment by miekg** [comment]
you're branch is not clean; you reverting something else as well

**Comment by fturib** [comment]
the other revert is empty ...
and the revert content is automatically computed from the initial PR.

**Comment by chrisohaver** [comment]
> you're branch is not clean; you reverting something else as well

I reverted it directly from the github website.  Clicking on "revert".  So it should be clean.
Perhaps the original PR was not clean.

**Comment by chrisohaver** [comment]
> It is kind of sad to revert here

Yes - it makes no sense at all.  Removing 2 redundant indexes increases memory use?  But, we are under a time crunch... so it will probably remain a mystery.

**Comment by miekg** [comment]
re: revert: i don't know, but it looks weird. Please fix.

without a proper pprof setup we will also be in the guessing game so that should somehow get supported or we need to do our own scale tests

**Comment by miekg** [comment]
oh, you rebased! I think this might be hard then let me see locally.

**Comment by miekg** [comment]
no, git revert 974ed086  just works.

**Comment by chrisohaver** [comment]
> oh, you rebased! 

Should I not rebase going forward?

**Pull request closed without merging**
