### PR TITLE
New cache implementation and prefetch handing in mw/cache

### PR DESCRIPTION
**Pull request by miekg**

### CODE REVIEW

**Comment by miekg** [comment]
@johnbelamaric PTAL. This PR does it all: new cache impl (`pkg/cache`) updates all users to the new cache. And adds prefetching to the *cache* middleware. The only thing missing (provided travis doesn't barf again) is a good test, which I will add soon.

**Comment by miekg** [comment]
Now with super hacky test

**Comment by miekg** [comment]
Some non-conclusive load testing on localhost:
CoreDNS running on 1053 from *master* branch, 3 concurrent perf-tests running in 3 other windows: `make TIME=10 queryperf`:
* each of them sees query loss: `[Timeout] Query timed out: msg id 40`
* leading to: `Queries per second:   3.986686 qps`

Doing *this* branch:
* no query loss
* all 3 perf-tests report back: `Queries per second:   52841.739172 qps` (with some minor differences)

**Comment by miekg** [comment]
@chrisohaver could you take a look at this PR? Thanks
(it's kinda huge - sorry 'bout that)

**Review by chrisohaver — APPROVED** [review]
Looks good

**Comment by SuperQ** [comment]
Nice!

**Comment by corny** [comment]
Is there any protection against DOS and cache poisoning?

**Pull request merged**
