### PR TITLE
feat: resolve externalname services which contain an IP address

### LINKED ISSUE #2324: Core DNS is not resolving external ip
We have a kubernetes service that points to an external service ip. External service IP is the ec2 instance internal IP address where the `mysql` service is running at 3306
```$ kubect get svc -n letmetry | grep -e NAME -e mysql
NAME                 TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)                       AGE
mysql                ExternalName   <none>           172.31.21.116   3306/TCP                      20m
```

- When using CORE DNS, the external IP service do not resolve
```
/ # nslookup mysql.letmetry
Server:    100.64.0.10
Address 1: 100.64.0.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'mysql.letmetry'
```

- When using KUBE DNS, the external IP service resolves
```
/ # nslookup mysql.letmetry.svc.cluster.local.
Server:    100.64.0.10
Address 1: 100.64.0.10 kube-dns.kube-system.svc.cluster.local

Name:      mysql.letmetry.svc.cluster.local.
Address 1: 172.31.21.116 ip-172-31-21-116.ap-south-1.compute.internal
```

Please suggest why this is happening.
The logs of CORE DNS when this request is made - 
```100.96.109.30:50382 - [19/Nov/2018:14:56:25 +0000] 3 "AAAA IN mysql.letmetry. udp 32 false 512" NXDOMAIN qr,rd,ra 108 100.419µs
100.96.109.30:41248 - [19/Nov/2018:14:56:25 +0000] 4 "AAAA IN mysql.letmetry.default.svc.cluster.local. udp 58 false 512" NXDOMAIN qr,rd,ra 151 110.391µs
100.96.109.30:42034 - [19/Nov/2018:14:56:25 +0000] 5 "AAAA IN mysql.letmetry.svc.cluster.local. udp 50 false 512" NXDOMAIN qr,rd,ra 143 91.647µs
100.96.109.30:41174 - [19/Nov/2018:14:56:25 +0000] 6 "AAAA IN mysql.letmetry.cluster.local. udp 46 false 512" NXDOMAIN qr,rd,ra 139 93.808µs
100.96.109.30:34985 - [19/Nov/2018:14:56:25 +0000] 7 "AAAA IN mysql.letmetry.ap-south-1.compute.internal. udp 60 false 512" NXDOMAIN qr,rd,ra 60 1.458123ms
100.96.109.30:45287 - [19/Nov/2018:14:56:25 +0000] 8 "A IN mysql.letmetry. udp 32 false 512" NXDOMAIN qr,rd,ra 108 102.671µs
100.96.109.30:36956 - [19/Nov/2018:14:56:25 +0000] 9 "A IN mysql.letmetry.default.svc.cluster.local. udp 58 false 512" NXDOMAIN qr,rd,ra 151 91.6µs
100.96.109.30:51749 - [19/Nov/2018:14:56:25 +0000] 10 "A IN mysql.letmetry.svc.cluster.local. udp 50 false 512" NXDOMAIN qr,rd,ra 143 92.572µs
100.96.109.30:54959 - [19/Nov/2018:14:56:25 +0000] 11 "A IN mysql.letmetry.cluster.local. udp 46 false 512" NXDOMAIN qr,rd,ra 139 87.971µs
100.96.109.30:42924 - [19/Nov/2018:14:56:25 +0000] 12 "A IN mysql.letmetry.ap-south-1.compute.internal. udp 60 false 512" NXDOMAIN qr,rd,ra 60 1.420079ms
```

## System info

- It is a default installation of Core DNS with kops. No custom configuration was made. We just tried to replace kube dns with core dns using kops and are stuck here.
- `image: gcr.io/google_containers/coredns:1.1.3`
- kubernetes version: `1.9.8`
- kops version: `1.10.0`
- CoreFile
```
Corefile: |-
    .:53 {
        errors
        log
        health
        kubernetes cluster.local. in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
    }
```

### PR DESCRIPTION
**Pull request by sylr**
Fix #2324

### CODE REVIEW

**Review by chrisohaver — CHANGES_REQUESTED** [review]
Please read comments in #2324 to see why this is invalid.

**Comment by sylr** [comment]
I have, I understand the spec says it should be a CNAME but since kubernetes does not enforce it and since kube-dns resolves it I don't see why it would be a problem that coredns does as well.

**Comment by chrisohaver** [comment]
Another way of looking at it:

ExternalName services cannot contain an IP address.  They only can contain FQDNs.  Things get confusing when you use a purely numeric FQDN, because it can _look_ like an IPv4 address (but in this case they are FQDNs, not IP addresses).

**Comment by sylr** [comment]
I don't understand how you can confuse an IP and a FQDN. I'm not aware of any all numeric TLD.

**Comment by chrisohaver** [comment]
> I don't understand how you can confuse an IP and a FQDN. I'm not aware of any all numeric TLD.

I agree in that I think Kubernetes validation could/should be fixed [here](https://github.com/kubernetes/apimachinery/blob/master/pkg/util/validation/validation.go#L141) (specifically to screen out numeric TLDs).

**Pull request closed without merging**
