### PR TITLE
Add source graph used by badge

### PR DESCRIPTION
**Pull request by yongtang**
### 1. What does this pull request do?

We are used by 10+ other projects now 👍 . Think it makes sense to add this badge.

### 2. Which issues (if any) are related?

N/A

### 3. Which documentation changes (if any) need to be made?

N/A

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by johnbelamaric** [comment]
Seems like this is more geared toward libraries. Would make more sense in miekg/dns rather than here.

**Comment by miekg** [comment]
It should be possible to use coredns as a lib as well. But I see your point.

**Comment by johnbelamaric** [comment]
10 is a low number of "users". So I don't think it reflects that well because I think it can be misunderstood. These 10 are probably the various external plugins, which is interesting, but doesn't reflect adoption or usage.

**Comment by miekg** [comment]
Ack. Feel free to revert.

**Comment by yongtang** [comment]
It is not necessary a fair comparison to libraries though it is still a good indicator. For example, caddy is used by 121 projects by the same metric. That is roughly proportional to the number of stars/forks compared with CoreDNS.

Not a big deal anyway so feel free to revert.

**Pull request merged**
