### PR TITLE
WIP: add debian packaging

### PR DESCRIPTION
**Pull request by miekg**
Uses https://github.com/goreleaser/nfpm, nfpm pkg create a debian
foo.deb that can be installed.

nfpm can be used as a lib (and goreleaser uses it). We can do the
minimal thing add a little Go binary to create deb and maybe rpms.

Signed-off-by: Miek Gieben <miek@miek.nl>

### CODE REVIEW

**Comment by miekg** [comment]
@yongtang something like this seems very sensible

**Comment by miekg** [comment]
have to think a bit where we want to store the additional files postinstall and the systemd service file should live. They could technically live in another repository which has pros and cons.

**Comment by yongtang** [comment]
I think having files in this repo (coredns) makes sense, if we want to have deb as part of the coredns release. This effectively promotes deb to first class citizen.

**Comment by miekg** [comment]
going to do this outside the main coredns/coredns repo, because it's cleaner to keep this out.

**Pull request closed without merging**
