### PR TITLE
Bump version to 1.7.0

### PR DESCRIPTION
**Pull request by yongtang**
Bump version to 1.7.0

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Bump version ..." ]
>@yongtang requested your review on: coredns/coredns#3782 Bump version to 1.7.0 as a code owner.

let's hold until we're ready to release.

**Comment by yongtang** [comment]
@miekg  Sure 👍

**Comment by yongtang** [comment]
I will just merge this PR for now. We can use #3945 to tracking remaining items before trigger the 1.7.0 release.

**Pull request merged**
