### PR TITLE
Add 1.5.1 release notes

### PR DESCRIPTION
**Pull request by miekg**
Prepare for imminent release.
Also list PRs merged in a new section to provide more detail.

### CODE REVIEW

**Comment by agdolla** [comment]
> Prepare for imminent release.
> Also list PRs merged in a new section to provide more detail.

Hi
you're missing this PR from the release notes:
https://github.com/coredns/coredns/pull/2846

it was merged also

**Comment by stp-ip** [comment]
Maybe adding the move to Caddy v1 via #2800 might be also great to add so.
Definitely should be added on the 1.6 release.

**Comment by miekg** [comment]
Thanks both, added the kubernetes PRs.

**Pull request merged**
