### PR TITLE
add CAA test

### PR DESCRIPTION
**Pull request by hawell**
### 1. Why is this pull request needed and what does it do?
we use coredns test platform for testing our dns server and we needed to verify CAA records

### 2. Which issues (if any) are related?
no related issue

### 3. Which documentation changes (if any) need to be made?
no documentation change is needed

### CODE REVIEW

**Comment by hawell** [comment]
can some one else plz review this PR? @miekg

**Comment by chrisohaver** [comment]
I presume you will you also be adding test cases in this PR?

**Review by chrisohaver — CHANGES_REQUESTED** [review]
Looks incomplete... (no test cases).

**Comment by miekg** [comment]
so *you* use coredns code for testing, and need CAA? Not totally against it, but seems weird to add code here, that sees no use.
Echo-ing Chris: need some in tree use/tests

**Comment by miekg** [comment]
Trying to cleanup PRs; this needs some work (a test that exercises this helper), otherwise I'm going to close it

**Pull request closed without merging**
