### PR TITLE
Add `go mod` support

### PR DESCRIPTION
**Pull request by yongtang**
### 1. Why is this pull request needed and what does it do?

This PR is an attempt to add `go mod` support for coredns.

### 2. Which issues (if any) are related?

n/a

### 3. Which documentation changes (if any) need to be made?

n/a

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
Looks like the `go mod` works. The CI will have to be updated, though.

**Comment by yongtang** [comment]
In order for `go mod` to work, the repo directory should not be inside `GOPATH`. For Travis we place it in a tmp path `/tmp/coredns`.
For CI, some additional changes might be needed. /cc @chrisohaver

**Comment by yongtang** [comment]
With `GO111MODULE=on ` it is not needed to exclude GOPATH though there are still some mismatch in CI.

**Comment by Xuanwo** [comment]
This may be resulted by: https://github.com/golang/go/issues/29281

**Comment by chrisohaver** [comment]
> /cc @chrisohaver not sure if there is any caching of CI in place. Is there a way to start CI without any cache?

In the CI, the go environment is re-created each time in a work directory.
Could be a Go version issue...

**Comment by chrisohaver** [comment]
Bumping to 1.11.5 got past that check sum issue. (thanks @Xuanwo)

I adjusted the Makefile, turning on Go Modules during builds and tests.

Next issue are module retrieval failures on two specific modules ...

```
../../../../pkg/mod/github.com/coredns/coredns@v1.3.1/plugin/trace/trace.go:19:2: unknown import path "github.com/DataDog/dd-trace-go/opentracing": cannot find module providing package github.com/DataDog/dd-trace-go/opentracing
../../../../pkg/mod/k8s.io/client-go@v10.0.0+incompatible/kubernetes/scheme/register.go:22:2: unknown import path "k8s.io/api/admissionregistration/v1alpha1": cannot find module providing package k8s.io/api/admissionregistration/v1alpha1
```

**Comment by Xuanwo** [comment]
`github.com/DataDog/dd-trace-go/opentracing` is not exist, maybe we need to import `gopkg.in/DataDog/dd-trace-go.v1/ddtrace/opentracer` instead, ref: https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/opentracer .

Mod `k8s.io/api/admissionregistration/v1alpha1` should be imported from  `https://github.com/kubernetes/api/tree/release-1.10` maybe.

**Comment by yongtang** [comment]
The `github.com/DataDog/dd-trace-go/opentracing` was renamed at some point, will need to change some code in CoreDNS to capture the new import. For `k8s.io/api/admissionregistration/v1alpha1`, will have to take a look. Likely some addition restrictions in go.mod.

**Comment by miekg** [comment]
would be good get this going for the next release. sick and tired of the compilation errors because of vendoring (latest victim coredns/proxy)

**Comment by stp-ip** [comment]
I have someone from my team also looking into this.

**Comment by yongtang** [comment]
/cc @miekg All CI tests passed now and this PR is ready.

There are some dependency in between ci and coredns. Once this PR is merged in I will update the ci to address it.

**Comment by miekg** [comment]
Nice! Might be worth trying an external plugin like coredns/example to see
if that works (or not)

**Comment by jamirais04** [comment]
All back me

**Comment by yongtang** [comment]
@miekg Tried go test and it works:
```
root@b45986ce27c2:/go/src/github.com/coredns/example# GO111MODULE=on go test -v ./...
=== RUN   TestExample
--- PASS: TestExample (0.00s)
=== RUN   TestSetup
--- PASS: TestSetup (0.00s)
PASS
ok  	github.com/coredns/example	0.004s
```

**Comment by yongtang** [comment]
@miekg Looks like everything is fine. To complete, I will try to:
- merge this PR first,
- then merge https://github.com/coredns/ci/pull/99
- then create a test PR to make sure everything still works (with CI test).
- if anything breaks, will revert back this PR and the PR in CI.

**Comment by yongtang** [comment]
Merge this PR and see if everything works with the other merged PR https://github.com/coredns/ci/pull/99

**Pull request merged**
