### PR TITLE
Initial adopters list

### PR DESCRIPTION
**Pull request by johnbelamaric**
Starting the adopters list.

### CODE REVIEW

**Comment by johnbelamaric** [comment]
Anyone running in prod that can have it publicly known please comment here (or push a commit!). Thanks!

**Comment by johnbelamaric** [comment]
@swestcott @ae6rt @nicorevin @oleh-ozimok @shashidharatd @creamfinance @serverwentdown @prologic

**Comment by prologic** [comment]
What do you want from me here?


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by johnbelamaric** [comment]
If you are using it in prod let me know :)

**Comment by swestcott** [comment]
@johnbelamaric We don't have SSL on our blog yet (it's being worked on), could you use `http://engineering.skybettingandgaming.com` for now?

**Comment by johnbelamaric** [comment]
Sure, will do.

**Comment by prologic** [comment]
@johnbelamaric Is "prod" considered some home-based infra that runs a bunch of sites and internal DNS?

**Comment by johnbelamaric** [comment]
I suppose...maybe list a zone or two you are hosting instead of saying it's home-based infrastructure.

**Pull request merged**
