### PR TITLE
Update various vendor dependencies

### PR DESCRIPTION
**Pull request by SuperQ**
Mostly `go get -u`, but rolled back k8s and etcd changes due to some
dependency chaining issues.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
I also had to keep zipkin behind.

**Comment by miekg** [comment]
is this with a 'go mod tidy' ?

**Comment by SuperQ** [comment]
Yes. Isn't there a CI test for go mod tidy?

**Comment by SuperQ** [comment]
There is now! :laughing:

**Review by bradbeam — APPROVED** [review]

**Comment by chrisohaver** [comment]
We auto tidy ... ala ... #3512

**Comment by SuperQ** [comment]
@chrisohaver Oh, neat, should I drop the tidy make / CI check?

**Comment by chrisohaver** [comment]
> @chrisohaver Oh, neat, should I drop the tidy make / CI check?

I don't think it's needed. The CI test asks users to fix it before merging ... but if a maintainer chooses to to ignore the failure, and merge anyways, the github workflow would correct it as it merges, IIUC.  So, essentially it becomes a check that can be ignored. So IMO, it is mostly redundant.

**Comment by SuperQ** [comment]
Dropped.

**Pull request merged**
