### PR TITLE
plugin/grpc: configure BackoffMaxDelay parameter

### PR DESCRIPTION
**Pull request by inigohu**
### 1. Why is this pull request needed and what does it do?
Possibility to configure BackoffMaxDelay.
### 2. Which issues (if any) are related?
#2387

### CODE REVIEW

**Comment by miekg** [comment]
Is this needed a user knob or can an sane default be set for DNS traffic?

**Comment by inigohu** [comment]
I wouldn't configure it by default, this should be a customization. In my case I need to reduce backoff delay for testing purpose only.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/grpc: ..." ]
>I wouldn't configure it by default, this should be a customization. In my case I need to reduce backoff delay for testing purpose only.

then it should probably not be a user visibile knob.

**Comment by inigohu** [comment]
> then it should probably not be a user visibile knob.

How can I set up this option without a visible knob?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/grpc: ..." ]
>> then it should probably not be a user visibile knob.
>
>How can I set up this option without a visible knob?

If you need it in testing you can just add to the testing code.

If you need it for *your* (external?) tests, that's a different problem. That's even more 
strongly points that this is a knob that is only useful for a very small subset 
of people and should not be there.

Maybe an exported variable you can set in code that you include in your testing 
setup or some such?

**Comment by inigohu** [comment]
> If you need it in testing you can just add to the testing code. 
> 
> If you need it for *your* (external?) tests, that's a different problem. That's even more strongly points that this is a knob that is only useful for a very small subset of people and should not be there. 
> 
> Maybe an exported variable you can set in code that you include in your testing setup or some such?

I'm running my upstream service and CoreDNS inside a docker-compose to make integration tests. I can't set any external variable or add any configuration in my tests that modifies CoreDNS.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/grpc: ..." ]
>> If you need it in testing you can just add to the testing code.
>>
>> If you need it for *your* (external?) tests, that's a different problem. That's even more strongly points that this is a knob that is only useful for a very small subset of people and should not be there.
>>
>> Maybe an exported variable you can set in code that you include in your testing setup or some such?
>
>I'm running my upstream service and CoreDNS inside a docker-compose to make integration tests. I can't set any external variable or add any configuration in my tests that modifies CoreDNS.

Sure you can, except it requires some extra work from your side.

One of principles I try to apply to coredns (and miekg/dns) is that there should 
not be a need for knobs to users can twiddle. If such a requirement exists we 
should automate it as much as possible. And only as a last resort expose 
something to a user.

**Comment by inigohu** [comment]
> One of principles I try to apply to coredns (and miekg/dns) is that there should not be a need for knobs to users can twiddle. If such a requirement exists we should automate it as much as possible. And only as a last resort expose something to a user.

I agree with those principles, but I think that if someone wants to make an end-to-end test of the backend service, should control de workflow of the test.

I've drawn the architecture of my test environment to explain my case in order to find a solution or finally close this PR.

Untitled Diagram
Backend depends on storage, so the first container to start is storage container and then, backend and CoreDNS containers.


Backend service needs to make some checks and builds before server and tests starts. Meantime, CoreDNS is already running and increasing the gRPC backoff delay connection until backend is up and ready to listen requests.

When the backend tests try to make DNS queries to CoreDNS will get an error because the gRPC backoff delay will be bigger than the DNS query timeout.

From the backend container I cannot control the CoreDNS  gRPC plugin status either, if is already connected or not.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/grpc: ..." ]
>I've drawn the architecture of my test environment to explain my case in order to find a solution or finally close this PR.
>
>Untitled Diagram
>Backend depends on storage, so the first container to start is storage container and then, backend and CoreDNS containers.
>
>
>Backend service needs to make some checks and builds before server and tests starts. Meantime, CoreDNS is already running and increasing the gRPC backoff delay connection until backend is up and ready to listen requests.
>
>When the backend tests try to make DNS queries to CoreDNS will get an error because the gRPC backoff delay will be bigger than the DNS query timeout.
>
>From the backend container I cannot control the CoreDNS  gRPC plugin status either, if is already connected or not.

This is a problem in itself and probably not only in your tests. Ideally the 
gRPC would try one-offs in-between the backoff delay to see if a upstream is 
respondning again.

A max of 5001 milleseconds of the backend delay might also work as a fix maximu, 
because anything bigger will not work anyway.

**Comment by inigohu** [comment]
> This is a problem in itself and probably not only in your tests. Ideally the gRPC would try one-offs in-between the backoff delay to see if a upstream is respondning again. 

> A max of 5001 milleseconds of the backend delay might also work as a fix maximu, because anything bigger will not work anyway.

Ok. I think the best thing will be to make a fork with those custom features.
Thanks

**Pull request closed without merging**
