### PR TITLE
Fix multiple credentials in route53

### PR DESCRIPTION
**Pull request by sharmaansh21**
1. Why is this pull request needed and what does it do?
This fix tries to address the issue in #2205 while multiple credentials in the route53 plugin will be overwritten by previous ones.

2. Which issues (if any) are related?
#2205

3. Which documentation changes (if any) need to be made?
n/a

### CODE REVIEW

**Comment by sharmaansh21** [comment]
Not sure, if this is the best way to fix this issue. I am more than happy to do requested changes. Or try some other approach if needed.

**Comment by yongtang** [comment]
The change in this PR makes sense to me, though I don't have a multi-account AWS to verify. Wondering if anyone could help to check if the fix work? /cc @SuperFunks @dilyevsky @canthefason?

**Comment by sharmaansh21** [comment]
@yongtang I can provide you access to accounts with route 53 domains if you wish to test it.

**Comment by miekg** [comment]
Managed to do some testing @sharmaanshul2102 ? Happy to merge afterwards

**Comment by sharmaansh21** [comment]
@miekg  :+1:

**Comment by sharmaansh21** [comment]
@miekg Is it possible to merge this before I start work on https://github.com/coredns/coredns/issues/2924 ? thanks!

**Comment by yongtang** [comment]
@SuperFunks @dilyevsky @canthefason anyone has a chance to test the fix?

**Comment by miekg** [comment]
I'm merging!

**Pull request merged**
