### PR TITLE
Move the rule stuff to it's own package

### PR DESCRIPTION
**Pull request by miekg**
Move to subdir rule and fix and export things that result from this.

Signed-off-by: Miek Gieben <miek@miek.nl>

### CODE REVIEW

**Comment by miekg** [comment]
probably need to redo this against your specific branch instead of master @fturib 
(can also send a diff - iff you want to use this change in the first place that is)

**Comment by fturib** [comment]
@miekg : I was out in vacation for  weeks. As suggested, I will report these changes on the main PR (#2335). And also address other comments on that PR. Thanks.
I will close this one when the report will be done (hopefully in the 2 coming days).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Move the rule..." ]
>@miekg : I was out in vacation for  weeks. As suggested, I will report these changes on the main PR (#2335). And also address other comments on that PR. Thanks.
>I will close this one when the report will be done (hopefully in the 2 coming days).

No worries.

Thanks!

**Comment by fturib** [comment]
Changes have been integrated in the last version of PR (#2335).
Hence, closing this one.

**Pull request closed without merging**
