### PR TITLE
Adding label selector support to Corefile

### PR DESCRIPTION
**Pull request by mrichmon**
This PR implements k8s label selection to allow filtering of exposed services using the k8s label selector syntax. Syntax is described at: http://kubernetes.io/docs/user-guide/labels/

@aledbf Please review for any concerns. This updates how the k8s dns controller operates.

Basic manual testing works. Automated integration test cases to follow.

### CODE REVIEW

**Comment by aledbf** [comment]
@mrichmon code LGTM

**Comment by mrichmon** [comment]
@aledbf Thanks for the review.
I'll merge after upstream stabilizes the etcd middleware.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Adding label se..." ]

> @aledbf Thanks for the review.
> I'll merge after upstream stabilizes the etcd middleware.

This should work... but sometimes doesn't :(
off-line tomorrow.. plenty of time next week to properly fix this and make a
push for becoming a server-plugin in Caddy.

**Comment by mrichmon** [comment]
@miekg The k8s code is working in my tests. So feel free to merge this if it's easier for the push to Caddy.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Adding label se..." ]

> @miekg The k8s code is working in my tests. So feel free to merge this if it's easier for the push to Caddy.

Ack, just merge if you are OK with it. I'm starting to work on the caddy push
tomorrow anyway, but I don't expect middleware to change much. If it does need
changes I will make them.

**Pull request merged**
