### PR TITLE
Check if the returned result of  forward.parseStanza() is 0

### PR DESCRIPTION
**Pull request by zouyee**
Signed-off-by: Zou Nengren <zouyee1989@gmail.com>

### 1. Why is this pull request needed and what does it do?
fix recovered from panic in server
### 2. Which issues (if any) are related?
https://github.com/coredns/coredns/issues/3735
### 3. Which documentation changes (if any) need to be made?
none
### 4. Does this introduce a backward incompatible change or deprecation?
none

### CODE REVIEW

**Comment by miekg** [comment]
thanks for picking this up; as dicussed on the bug, I'm not sure what the better option is. When I saw this PR I thought, I wish we would have had a presubmit check for this (for future occurrences). In that light, maybe we *should* make it an error if nothing is parsed by `HostPortOrFile`?

**Comment by chrisohaver** [comment]
> thanks for picking this up; as dicussed on the bug, I'm not sure what the better option is. When I saw this PR I thought, I wish we would have had a presubmit check for this (for future occurrences). In that light, maybe we _should_ make it an error if nothing is parsed by `HostPortOrFile`?

I'm leaning slightly toward making it an error, but either way is fine with me.  I think getting zero results from `HostPortOrFile` would, in virtually all reasonable cases be an invalid result.  IOW, for most usage, it's an error. The error could be a public type in the package, so in case there is some one in need of accepting a zero result, they could disregard that error.  In the unlikely future event that accepting zero results becomes a common need, we could add a new function that calls `HostPortOrFile` and  disregards the zero length.

**Comment by zouyee** [comment]
> thanks for picking this up; as dicussed on the bug, I'm not sure what the better option is. When I saw this PR I thought, I wish we would have had a presubmit check for this (for future occurrences). In that light, maybe we _should_ make it an error if nothing is parsed by `HostPortOrFile`?

In the forward plugin, it invokes HostPortOrFile to resolve the corresponding nameservers. If the file is empty or the nameserver is invalid, HostPortOrFile  will ignore the corresponding string. Therefore, when HostPortOrFile is revoked by forward plugin  returns the Error(not an IP address or file),  the caller could use the log mode instead of returning the error directly

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Check if the ..." ]
>> thanks for picking this up; as dicussed on the bug, I'm not sure what the better option is. When I saw this PR I thought, I wish we would have had a presubmit check for this (for future occurrences). In that light, maybe we _should_ make it an error if nothing is parsed by `HostPortOrFile`?
>
>I'm leaning slightly toward making it an error, but either way is fine with me.  I think
>getting zero results from `HostPortOrFile` would, in virtually all reasonable cases be an
>invalid result.  IOW, for most usage, it's an error.

I agree with that, let's make it an error is zero results would be returned.

**Pull request closed without merging**
