### PR TITLE
[WIP] Added initial scraping method

### PR DESCRIPTION
**Pull request by knrt10**
Signed-off-by: knrt10 <tripathi.kautilya@gmail.com>

Related to #3541

- Initial work for scraping. 
- Added 2 files in `metrics` folder, `scrape.go` and `scrape_test.go`.

Currently, it is returning JSON with the URL for metrics.

cc @yongtang. Also can you please tell in what format do we want the metrics to be?

### CODE REVIEW

**Comment by miekg** [comment]
I'm assuming this is for #3541 ? Can you reference that issue in your PR message? Can you *also* explain *why* this is needed and must be merged? Is your plan for #3541 describe somewhere (public) ?

**Comment by SuperQ** [comment]
This doesn't make any sense to me. We already have a standard Prometheus format metrics output. There's no need to implement JSON output. JSON output is inefficient and obsolete. It's not been supported by Prometheus for many years now.

**Comment by yongtang** [comment]
@knrt10 You don't need to scrape the metrics into json. What you need is to extract the metric and transform the "vector of metrics" into a scaling factor, so that this scaling factor could be feed into Kubernetes. The *transform* of the "vector of metrics" could initially be done in Golang, by some simple method (e.g., linear?). Later you can try to find a way to wire up external *transform* program into the pipeline. For example, maybe with keras?

Normally in machine learning, python is the first-class citizen. However, it is still possible to wire up into the Golang. Let me know if you want to have a pointer on how to achieve it.

**Comment by miekg** [comment]
nacking this PR - I don't foresee a need to add special scraping code to coredns [for this usecase]

**Pull request closed without merging**
