### PR TITLE
Small tweaks to the notes

### PR DESCRIPTION
**Pull request by miekg**
made these to the coredns.io repo as well, but this is canonical.

### CODE REVIEW

**Comment by ykhr53** [comment]
I just realised there are a few differences between the current document and the previous one.

- Every path to plugins should be */plugins/foobar* ?
- Put commas after each author name to make it more readable?

https://raw.githubusercontent.com/coredns/coredns/master/notes/coredns-1.6.5.md

**Comment by miekg** [comment]
Ack, If we going to enforce any layout for these we should write something that generates (and or checks the notes).

**Comment by ykhr53** [comment]
ok I get it. but the first one, the path for the plugins should be fixed.
It has been missing links and got 404 on the page.
https://coredns.io/2019/12/11/coredns-1.6.6-release/

**Comment by stp-ip** [comment]
Good catch.

Happy for you to fix the mentioned plugin links in a PR :)

**Comment by ykhr53** [comment]
I'm gonna open a PR in coredns/coredns and coredns/coredns.io as well 👍

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Small tweaks ..." ]
>I'm gonna open a PR in coredns/coredns and coredns/coredns.io as well 👍

you only need to do it here; I sync.py those things into the coredns.io repo

**Comment by ykhr53** [comment]
ok, I got it. thanks.

**Comment by ykhr53** [comment]
@miekg Also, could you sync bufsize/README.md to coredns.io/content/plugins/ ?
It seems not being synced to coredns.io repo, the missing link will be happened.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Small tweaks ..." ]
>@miekg Also, could you sync bufsize/README.md to coredns.io/content/plugins/ ?

all done

**Comment by ykhr53** [comment]
Thanks 😊

**Pull request merged**
