### PR TITLE
plugin/kubernetes: update serial when records change

### PR DESCRIPTION
**Pull request by chrisohaver**
### 1. Why is this pull request needed and what does it do?
Update serial when records change.
This is mostly restored functionality that was removed when watch feature was removed (#2549).

### 2. Which issues (if any) are related?
none

### 3. Which documentation changes (if any) need to be made?
none

### 4. Does this introduce a backward incompatible change or deprecation?
no

### CODE REVIEW

**Comment by chrisohaver** [comment]
@miekg, PTAL, I missed this when I reviewed #2549.  Part of what the ResourceEventHandlerFuncs were doing was updating the SOA serial when services/endpoints/pods change.  This PR restores that part.

**Comment by miekg** [comment]
this is lot of code being executed for just incrementing a SOA serial number

**Comment by chrisohaver** [comment]
> this is lot of code being executed for just incrementing a SOA serial number

Yes, it only really matters for zone transfers.   We can skip this when `transfer` is not enabled, that way we don't do the extra work unless we need to.  Would that be ok?

**Comment by miekg** [comment]
That would be better. Didn't we have something even simpler before watch
was merged?

**Comment by johnbelamaric** [comment]
Not that worked. We had something simpler at one point but it bumped the
serial way way too often. We only noticed because of watch.

**Comment by chrisohaver** [comment]
> Didn't we have something even simpler before watch was merged?

It was simpler.  Before, we updated the serial for _every_ notification received from the API.  The problem is that majority of updates we receive don't change our records (especially endpoint updates, which is a constant stream of various state changes unrelated to the name or IP of DNS records). This meant that the serial was constantly changing, even while no DNS records were changing. There does not yet exist in the k8s api, a way to subscribe to changes to certain fields only.

**Comment by miekg** [comment]
ok, and there don't seem to be a lot of memory allocation going one.

**Pull request merged**
