### PR TITLE
plugin/log: Change time format to be consistent with pkg/log

### PR DESCRIPTION
**Pull request by eugen-kleiner-mesh**
### 1. Why is this pull request needed and what does it do?
Changes time format in log plugin logs to be consistent with pkg/log
### 2. Which issues (if any) are related?
https://github.com/coredns/coredns/issues/2114

### CODE REVIEW

**Comment by miekg** [comment]
The log plugin has a runtime option to set the output, so we can't statically 
set it something as fix. We need to plugin *into* the log plugin to get the 
current format and use that.

**Comment by eugen-kleiner-mesh** [comment]
@miekg, this is the format which is used by log plugin. See:
https://github.com/coredns/coredns/blob/master/plugin/log/log.go#L61 and
https://github.com/coredns/coredns/blob/master/plugin/pkg/replacer/replacer.go#L43
Could you clarify your comment if I misunderstood something?

**Comment by eugen-kleiner-mesh** [comment]
In fact, pkg/log plugin can be remade to use the constant from pkg/format. But in this case Logger instance should be created in pkg/log.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/log: C..." ]
>This is the format which is used by log plugin. See:
>https://github.com/coredns/coredns/blob/master/plugin/log/log.go#L61 and
>https://github.com/coredns/coredns/blob/master/plugin/pkg/replacer/replacer.go#L43
>Could you clarify your comment if I misunderstood something?

My bad; you can only override the contents of the log: https://github.com/coredns/coredns/blob/master/plugin/log/README.md#log-format
not the actual logging prefix

>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/coredns/coredns/pull/2135#issuecomment-424861450
/Miek

--
Miek Gieben

**Pull request merged**
