### PR TITLE
Bump K8s dependencies

### PR DESCRIPTION
**Pull request by chrisohaver**
Signed-off-by: Chris O'Haver <cohaver@infoblox.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
The bot is taking care of this. No need to manually handle these.

**Comment by chrisohaver** [comment]
> The bot is taking care of this. No need to manually handle these.

We have run into trouble with these libraries specifically ... I think merging them in one at a time causes compilation problem sometimes - though it didn't appear to this time, so I suppose we can just merge the bot ones...

**Comment by chrisohaver** [comment]
Ah, I see - the `go mod tidy` action is covertly fixing the go.mod behind the scenes... https://github.com/coredns/coredns/actions?query=workflow%3A%22go+tidy%22

**Comment by SuperQ** [comment]
Yea, the bot seems to know how to rebase when they change.

**Pull request closed without merging**
