### PR TITLE
Delete out-of-date item in cache when get it.

### PR DESCRIPTION
**Pull request by ckcd**
### 1. Why is this pull request needed and what does it do?
In cache.get(), first it will check the cache to find the item, when get it, secondly, use ttl() to check whether the item is out-of-date, if it's OK then this item is the final answer, but if it's NOT, which means the ttl of this item is < 0, for now, the code doing nothing, I thinks it should be: delete this useless item.
As we know, cache plugin will random replace a item when the cache is full, instead of traverse the cache and find a expired item, this is for performance and avoid using to many locks. But in my situation, we already find a expired item and don't need any traverse, so we should delete the item with a little attention.

### 2. Which issues (if any) are related?
#2035 

### 3. Which documentation changes (if any) need to be made?
None.

### CODE REVIEW

**Comment by yongtang** [comment]
lgtm

**Comment by miekg** [comment]
This turns every read into a write, is that desirable?

**Comment by ckcd** [comment]
@miekg 
1. This only occurs in: query a item which is expired, so it won't affect too many read.
2. With this delete, we can reduce the scene of randomly eviction (i.e. the cache is full), so to protect useful items.

So yes, it is desirable in my opinion.
Thanks~

**Comment by grobie** [comment]
>     2\. With this delete, we can reduce the scene of randomly eviction (i.e. the cache is full), so to protect useful items.

I'm curious about this one, can you confirm that with metrics in production? I'd have expected that the Cache.get() code path is only triggered during a DNS request against this name. A cache miss would then result in a Cache.write shortly after with an up-to-date record. Therefore, this change seems to change the cache commands from "cache get (miss), next plugin, cache write" to "cache get (miss), cache delete, next plugin, cache write". What other paths would trigger a cache get+delete without an immediate write to the same location?

**Comment by ckcd** [comment]
@grobie 
Thanks for your opinion! 
I didn't notice the "cache write" before, so I think we should do delete after get a up-to-date item, I'm wrong~

**Comment by miekg** [comment]
would a separate go-routine that scans the cache and expunges items be better here?

**Comment by ckcd** [comment]
@miekg 
Sorry for reply so late,
a new goroutine may delete unuse item, but also use too many lock,
whatever I will try this method and do some test~

**Pull request closed without merging**
