### PR TITLE
Adding detail of file ISSUE_TEMPLATE

### PR DESCRIPTION
**Pull request by truongnh1992**
Describe more detail in ISSUE_TEMPLATE:
	- Operating sytem, kernel version
	- Corefile?
	- Problem explanation, logs

Co-Authored-By: Dao Cong Tien tiendc@vn.fujitsu.com
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>

### CODE REVIEW

**Comment by truongnh1992** [comment]
@pmoroney Could you help me to review this PR, please.

**Review by chrisohaver — CHANGES_REQUESTED** [review]
Most of this seems redundant with the questions already present in the template.

**Comment by pmoroney** [comment]
Also those instructions, `cat /etc/os-release`, and `uname -r`, are not OS agnostic. If someone used an OS that didn't use that file, or a non-linux OS, those commands might be confusing.

**Comment by miekg** [comment]
Better addition is adding something like:
* Does your change increase resource usage
* Does your change decrease throughput
* Are there repeatable benchmarks

**Comment by truongnh1992** [comment]
> 
> 
> Better addition is adding something like:
> 
>     * Does your change increase resource usage
> 
>     * Does your change decrease throughput
> 
>     * Are there repeatable benchmarks

Thank you. I see. I've just updated it.

**Comment by chrisohaver** [comment]
```
* Does your change increase resource usage
* Does your change decrease throughput
```

... could probably boil those 2 down to one question.

What precisely do you mean by `Are there repeatable benchmarks`?  Are you asking for benchmark tests to be included?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Adding detail..." ]
>```
>* Does your change increase resource usage
>* Does your change decrease throughput
>```
>
>... could probably boil those 2 down to one question.
>
>What precisely do you mean by `Are there repeatable benchmarks`?  Are you asking for benchmark tests to be included?

yes, are a shell-script; how can you validate the claims otherwise. This is why 
I also want some kind of framework where these things can easily plugged in, 
benchmark tests are one such thing.

**Pull request closed without merging**
