### PR TITLE
Move federation plugin to github.com/coredns/federation

### PR DESCRIPTION
**Pull request by yongtang**
This PR is part of the effort of #3041 to remove federation plugin.

This is the first step to move federation to github.com/coredns/federation

Note the github.com/coredns/federation was done through 
```
git filter-branch --subdirectory-filter plugin/federation -- --all
```

so related git history are kept.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by miekg** [comment]
what do we do with `plugin/kubernetes/federation.go`? Is there any way this can be fully deprecated?

**Comment by yongtang** [comment]
> what do we do with plugin/kubernetes/federation.go? Is there any way this can be fully deprecated?

@miekg It should be possible, although that may need some surgical moving around. Let me update the PR and see if works.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Move federati..." ]
>> what do we do with plugin/kubernetes/federation.go? Is there any way this can be fully deprecated?
>
>@miekg It should be possible, although that may need some surgical moving around. Let me update the PR and see if works.

but what I mean is, even with the code in a new repo; if we remove this 
interface into the kubernetes plugin it will stop working. So recompiling 
coredns to re-add *federation* will be more involved, because you have to patch 
more.

I'm fine with fully deprecating it, but it will be gone **gone** at some point.

**Comment by yongtang** [comment]
@miekg We could move all related logic to coredns/federation there fully. I think we only need to export `localNodeName` in Kubernetes plugin (for now, until fully deprecated). Let me see if it works.

**Comment by yongtang** [comment]
@miekg I think the PR is ready, please take a look and see if it works.

**Review by miekg — APPROVED** [review]

**Pull request merged**
