### PR TITLE
Add type to default template

### PR DESCRIPTION
**Pull request by chrisohaver**
Adds type to the default value for template:  {service}.{namespace}.{type}.{zone}
Updates tests to include type in the test queries.

### CODE REVIEW

**Comment by miekg** [comment]
Please update the tests as well. Thanks!

**Comment by chrisohaver** [comment]
Ah - there are additional test that are not in the "make test" path ... 
Any tips on how to get those working?  They fail to connect on my system when I run "make testk8s".  Looks like the tests expect kubernetes to be installed and running locally on port 8080.  But I assume it also needs to be running a test integration configuration - is this documented anywhere?

**Comment by miekg** [comment]
This is all done via scripts in the `.travis` subdir and controlled from the `.travis.yml` file

**Comment by johnbelamaric** [comment]
Looks like something just merged in K8s that removed the older client code we are using...

**Comment by yongtang** [comment]
@chrisohaver You can look into the travis.yml. Launching Kubernetes is done here:
https://github.com/miekg/coredns/blob/master/.travis.yml

```
ETCD_VERSION=2.3.1
K8S_VERSION=1.3.7
KUBECTL="docker exec hyperkube /hyperkube kubectl" 

# Invoke etcd
docker run -d --net=host --name=etcd quay.io/coreos/etcd:v$ETCD_VERSION

# Invoke Kubernetes
docker run -d --volume=/:/rootfs:ro --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:rw --volume=/var/lib/kubelet/:/var/lib/kubelet:rw --volume=/var/run:/var/run:rw --net=host --pid=host --privileged --name=hyperkube gcr.io/google_containers/hyperkube-amd64:v$K8S_VERSION /hyperkube kubelet --containerized --hostname-override=127.0.0.1 --api-servers=http://localhost:8080 --config=/etc/kubernetes/manifests $DNS_ARGUMENTS --allow-privileged --v=2

# Wait until kubectl is ready
for i in {1..10}; do $KUBECTL version && break || sleep 5; done

$KUBECTL version
$KUBECTL config set-cluster test-doc --server=http://localhost:8080
$KUBECTL config set-context test-doc --cluster=test-doc
$KUBECTL config use-context test-doc

# Wait until k8s is ready
for i in {1..30}; do $KUBECTL get nodes && break || sleep 5; done

# Test setup
.travis/kubernetes/setup_k8s_services.sh
```

**Comment by yongtang** [comment]
Oh, seems Kubernetes updates some of the client code.

**Comment by miekg** [comment]
Again... grrr

**Comment by yongtang** [comment]
See:
https://github.com/kubernetes/kubernetes/pull/35431

I am trying to see where the Client is moved. The commit has so many files deleted so still in the process of figuring out what has been changed.

**Comment by johnbelamaric** [comment]
https://github.com/kubernetes/client-go

**Comment by miekg** [comment]
Fine with merging as-is and fixing the kube stuff later...

**Comment by miekg** [comment]
Tried `client "k8s.io/client-go/kubernetes/typed/core/v1"` as the import, but didn't work, because that is a CoreClient and has a different API (although some of the same methods).
IOW: not sure if I can fix this.

We could vendor this dep - but I rather stay current with k8s' api

**Comment by miekg** [comment]
@aledbf we can also just merged this one, no?

**Comment by yongtang** [comment]
I tried to build with CoreClient:
https://github.com/miekg/coredns/compare/master...yongtang:kubenetes-fix

The code builds successfully but there is still one test error left (
https://travis-ci.org/yongtang/coredns)

```
kubernetes_test.go:77: Could not get CoreDNS serving instance: middleware/kubernetes: group  has not been registered
```

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Add type to def..." ]

> I tried to build with CoreClient:
> https://github.com/miekg/coredns/compare/master...yongtang:kubenetes-fix
> 
> The code builds successfully but there is still one test error left (
> https://travis-ci.org/yongtang/coredns)
> 
> ```
> kubernetes_test.go:77: Could not get CoreDNS serving instance: middleware/kubernetes: group  has not been registered
> ```

See #374 and other smaller PRs that got merged yesterday. Manuel did a lot of
work there.

**Comment by miekg** [comment]
Is this still relevant?

**Comment by chrisohaver** [comment]
The failed test consistently works in my local copy.  Not sure why its failing in travis.
I re-pushed the changes to give travis another go at it.

```
ubuntu@gobox:~/work/src/github.com/miekg/coredns$ go test -v ./test/metrics_test.go ./test/auto_test.go ./test/server.go
=== RUN   TestMetricsServer
--- PASS: TestMetricsServer (0.00s)
=== RUN   TestMetricsRefused
--- PASS: TestMetricsRefused (0.00s)
=== RUN   TestMetricsAuto
--- PASS: TestMetricsAuto (2.21s)
=== RUN   TestAuto
--- PASS: TestAuto (2.20s)
=== RUN   TestAutoNonExistentZone
--- PASS: TestAutoNonExistentZone (0.00s)
=== RUN   TestAutoAXFR
--- PASS: TestAutoAXFR (1.10s)
PASS
ok      command-line-arguments  5.581s

```

**Pull request merged**
