### PR TITLE
cache: split out items

### PR DESCRIPTION
**Pull request by miekg**
Make each of the structs we store smaller, this should cut back on
memory use. The included benchmark shows same *number* of allocations,
but those allocation are smaller (still need to get that data out of the
test).

Cache was already using interface{} so this slit in nicely.
### 3. Which documentation changes (if any) need to be made?

### CODE REVIEW

**Comment by miekg** [comment]
@grobie do you have time to look this over?

**Comment by grobie** [comment]
Thanks for that PR! Do you have any numbers showing the improvements in terms of memory needs?

**Comment by miekg** [comment]
Sadly no, the benchmark shows _allocations_ not bytes allocated; I can do a one-off tests, but it would be much, *much* better to have a GitHub integration that reports this (although that more than a full weeks worth to setup)

**Comment by miekg** [comment]
merge? @grobie

**Comment by miekg** [comment]
I'll probably go ahead and merge this, after I self review it once again.

**Comment by chrisohaver** [comment]
IMO, especially given the currently active issues (memory/cpu spike concerns), it would be better to quantify how much this change affects memory and cpu utilization, before merging.

**Comment by miekg** [comment]
Sure. How and where?

**Comment by chrisohaver** [comment]
Packet is a good resource for this type of testing. 

E.g. Do a load test using previous cache, measure cpu/mem.  Then do same load test using new cache, measure cpu/mem. Compare.

**Comment by chrisohaver** [comment]
code lgtm fwiw

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] cache: split ..." ]
>Packet is a good resource for this type of testing.
>
>E.g. Do a load test using previous cache, measure cpu/mem.  Then do same load test using new cache, measure cpu/mem. Compare.

Sure. Doing these one-offs don't really help. What would you need to see and 
would you be willing to commit cycles to make something better?

**Comment by chrisohaver** [comment]
By "something better" do you mean automated scale testing?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] cache: split ..." ]
>By "something better" do you mean automated scale testing?

Yes, or at least the metrics/data you're asking for. We have benchmark tests 
(this PRs adds them), but they can't be used in Travis.

Also cpu usage/global memory usage and not easy extractable.

**Comment by chrisohaver** [comment]
An automated scale testing framework/setup doesn't matter in the context of this PR (because that would take a very long time to build, and this PR will have long since been merged before the framework is complete).

IMO, it would be _better_ to quantify the affect on memory footprint and cpu ... but not _required_.  But sounds like you are saying that it's not worth the effort to do a one-off test of memory/cpu footprint, because you have already added benchmarks. ok

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] cache: split ..." ]
>An automated scale testing framework/setup doesn't matters in the context of this PR (because that would take a very long time to build, and this PR will have long since been merged before the framework is complete).

Not true, it matters and has mattered before.

You're side stepping my question.

>IMO, it would be _better_ to quantify the affect on memory footprint and cpu ... but not _required_.  But sounds like you are saying that it's not worth the effort to do a one-off test of memory/cpu footprint, because you have already added benchmarks. ok

There are benchmarks added in this pr, but they show allocations. Not sure if 
they can be made to show more.

**Comment by johnbelamaric** [comment]
On Tue, Mar 12, 2019 at 2:20 PM Miek Gieben <notifications@github.com>
wrote:

> [ Quoting <notifications@github.com> in "Re: [coredns/coredns] cache:
> split ..." ]
> >An automated scale testing framework/setup doesn't matters in the context
> of this PR (because that would take a very long time to build, and this PR
> will have long since been merged before the framework is complete).
>
> Not true, it matters and has mattered before.
>
>
I think Chris just meant that by the time we built that, this PR would have
already merged. It's still a good thing to build.

**Comment by chrisohaver** [comment]
> I think Chris just meant that by the time we built that, this PR would have
already merged.

lol.  That is what I meant ... because thats literally what I wrote. But thanks for the clarification. :)

**Comment by miekg** [comment]
Thanks. I'll take that as a 'no' then...

**Comment by grobie** [comment]
I agree with @chrisohaver and would like to see some data baking the need for this change. A one-time test showing a significant reduction of memory RSS with change compared to current mater would be helpful already. I understand the wish for an automated suite which permanently monitors that, but I don't see this as a requirement for this PR.

Without any data it's not clear whether the increased complexity is really worth it.

**Comment by miekg** [comment]
See https://github.com/coredns/coredns/pull/2694
This is already printing odd things (in master and on this branch), for total memory used (for which I need to read the actual docs of runtime)

**Pull request closed without merging**
