### PR TITLE
Update go dep

### LINKED ISSUE #1557: run dep ensure -update again
Just (Feb 23) tried it, fails on etcd
~~~
% go b
# github.com/coredns/coredns/vendor/github.com/coreos/etcd/client
vendor/github.com/coreos/etcd/client/keys.generated.go:70:6: r.WriteArrayStart undefined (type codec.encDriver has no field or method WriteArrayStart)
vendor/github.com/coreos/etcd/client/keys.generated.go:72:6: r.WriteMapStart undefined (type codec.encDriver has no field or method WriteMapStart)
vendor/github.com/coreos/etcd/client/keys.generated.go:75:6: r.WriteArrayElem undefined (type codec.encDriver has no field or method WriteArrayElem)
vendor/github.com/coreos/etcd/client/keys.generated.go:83:6: r.WriteMapElemKey undefined (type codec.encDriver has no field or method WriteMapElemKey)
vendor/github.com/coreos/etcd/client/keys.generated.go:85:6: r.WriteMapElemValue undefined (type codec.encDriver has no field or method WriteMapElemValue)
vendor/github.com/coreos/etcd/client/keys.generated.go:94:6: r.WriteArrayElem undefined (type codec.encDriver has no field or method WriteArrayElem)
vendor/github.com/coreos/etcd/client/keys.generated.go:102:6: r.WriteMapElemKey undefined (type codec.encDriver has no field or method WriteMapElemKey)
vendor/github.com/coreos/etcd/client/keys.generated.go:104:6: r.WriteMapElemValue undefined (type codec.encDriver has no field or method WriteMapElemValue)
vendor/github.com/coreos/etcd/client/keys.generated.go:113:6: r.WriteArrayElem undefined (type codec.encDriver has no field or method WriteArrayElem)
vendor/github.com/coreos/etcd/client/keys.generated.go:121:6: r.WriteMapElemKey undefined (type codec.encDriver has no field or method WriteMapElemKey)
vendor/github.com/coreos/etcd/client/keys.generated.go:121:6: too many errors
% git co .
~~~
will try again later, or tomorrow as I don't want to pin etcd to a version.

### PR DESCRIPTION
**Pull request by yongtang**
### 1. What does this pull request do?
This fix updates go dep with `dep ensure --update` as well as the following:
- Removed github.com/ugorji/go restriction in Gopkg.toml (fixes  #1557)
- Added github.com/flynn/go-shlex in Makefile (neede by Caddy, maybe removed later)

### 2. Which issues (if any) are related?
This fix fixes #1557

### 3. Which documentation changes (if any) need to be made?

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
The ci error seems to be unrelated. /cc @chrisohaver maybe ci is out of sync with coredns repo?

**Comment by fturib** [comment]
@yongtang : it is most likely a change that is wrong in the vendorization or go dep.

**Comment by chrisohaver** [comment]
CI builds from scratch in a clean work space every time.

**Comment by chrisohaver** [comment]
I see. This is a failure of compiling the tests themselves (not coredns)...  So perhaps we need to vendor caddy in the CI repo too...

**Comment by fturib** [comment]
Issue of CI is tied to Caddy that is now in 2 places : as vendor, and as src repository.

I guess adding a vendorization of Caddy (even though that is maybe partial), is enough to break the compilation:


**from compilation at deployment in CI:**
```
go test -v ./test/kubernetes/...
# github.com/coredns/ci/test/kubernetes
test/kubernetes/tools.go:117:2: cannot use server (type *"github.com/coredns/coredns/vendor/github.com/mholt/caddy".Instance) as type *"github.com/mholt/caddy".Instance in return argument
FAIL	github.com/coredns/ci/test/kubernetes [build failed]
Makefile:74: recipe for target 'test-k8s' failed
make: *** [test-k8s] Error 2


```


**from you PR:**
```
+[[projects]]
 +  name = "github.com/mholt/caddy"
 +  packages = [
 +    "onevent",
 +    "onevent/hook"
 +  ]
 +  revision = "d3f338ddab9ee24b376b5c9c51e202581e2d43ba"
 +  version = "v0.10.11"
 +
```

**Comment by miekg** [comment]
vendoring caddy also breaks plugin as they import the canonical import for caddy, not the vendored one. We can't vendor caddy.

"vgo will solve all our problems"

**Comment by yongtang** [comment]
Looks like the `ignored` rule in Gopkg.toml is broken. Will need to investigate to see why it picked up the ignored packages.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Update go dep..." ]
>Looks like the `ignored` rule in Gopkg.toml is broken. Will need to investigate to see why it picked up the ignored packages.

probably because something else deeper in that import path is also used? That's 
why originally there where three ignores to get caddy out of the way. (Maybe it 
the *on* plugin?)

**Comment by yongtang** [comment]
Both `caddy/onevent` and `golang.org/x/text` needs to be added to `ignored`. Just updated the PR.

**Comment by yongtang** [comment]
All tests passed now 🎉

**Pull request merged**
