### PR TITLE
add consul plugin

### PR DESCRIPTION
**Pull request by poppyred**

### CODE REVIEW

**Review by dilyevsky — COMMENTED** [review]
Browsing briefly this change will likely need a lot of work. Previously we've discussed that new substantial plugins will need support from at least one of maintainers. Has anything like this been discussed anywhere?

**Comment by poppyred** [comment]
It doesn't feel good

**Comment by poppyred** [comment]
move to [here](https://github.com/coredns/coredns/pull/3545)

**Comment by poppyred** [comment]
>Browsing briefly this change will likely need a lot of work. Previously we've discussed that new substantial plugins will need support from at least one of maintainers. Has anything like this been discussed anywhere?
@dilyevsky 

just a few modifications to the etcd base, adding wildcard query logic, I think maintenance costs are a little.
it is that I need and few issue, but I think that add a consul back-end very good

**Pull request closed without merging**
