### PR TITLE
kubernetes: fix the type

### PR DESCRIPTION
**Pull request by miekg**
client-go is a "empty interface" waste-land and we're missing an
integration test so we didn't catch. Try this.

Signed-off-by: Miek Gieben <miek@miek.nl>

### CODE REVIEW

**Comment by chrisohaver** [comment]
I tested this manually with services - and it works.

**Comment by miekg** [comment]
Nice. 

Can you whip up a integration test, so we at last have some defense in-depth for this?

**Review by chrisohaver — APPROVED** [review]

**Comment by miekg** [comment]
Fixes #2204

**Comment by chrisohaver** [comment]
Cant run integration tests on closed PRs...  will open a new PR.

**Comment by chrisohaver** [comment]
CI test merged

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] kubernetes: f..." ]
>CI test merged

:+1:

**Pull request merged**
