### PR TITLE
WIP: route53 cname lookup

### PR DESCRIPTION
**Pull request by sean-abbott**
(Note that this is truly raw WIP and I would squash out things like debugging statements before finalizing this.)

### 1. What does this pull request do?

This is the beginning of an implementation to allow looking up cnames via route53. Recursive solving still needs to be implemented, as do tests.

### 2. Which issues (if any) are related?
#1640 

### 3. Which documentation changes (if any) need to be made?
We would need to update the Route53 Plugin docs to reflect functioning cname lookups.

### CODE REVIEW

**Comment by miekg** [comment]
Ah, now I understand what you're trying to do here. You want to feed the an external CNAME back into CoreDNS to get it resolved?
The kubernetes plugins does this, by allowing `upstream` in the config and not other options causing it to point to `self`, see plugin/kubernetes/setup.go#L218 , you should be able to copy its use.

For this PR to be fully ready for merging we also need an update to the README and a couple of tests.

**Comment by sean-abbott** [comment]
Oh, great!  I'll take a look and see what I can do! I had linked an issue that was raised about making this sort of recursive call back into the chain automatic...should I wait for that, or is that gonna be a awhile?

**Comment by miekg** [comment]
Upstream to self should do this, the issue you mention is about doing this
by default.

**Comment by johnbelamaric** [comment]
In #1645 @chrisohaver proposed to do this cname lookup as a separate plugin, which would eliminate the need to implement it everywhere separately.

**Comment by sean-abbott** [comment]
I can't actually figure out how upstream.Lookup is being called in kubernetes and etcd. Both kubernetes and etcd implement ServiceBackend, but I can't figure out if I need to or not.

Nothing that I can find directly calls the upstream lookup, so I'm not sure how it gets called at all?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] WIP: route53 ..." ]
>I can't actually figure out how upstream.Lookup is being called in kubernetes and etcd. Both kubernetes and etcd implement ServiceBackend, but I can't figure out if I need to or not.
>
>Nothing that I can find directly calls the upstream lookup, so I'm not sure how it gets called at all?

backend_lookup.go line #124 (in master) call b.Lookup that looks up external 
addresses

**Comment by sean-abbott** [comment]
Ok, so I have this working with upstream the way that I want it to. However, the answer that I'm creating if I request a cname (i.e. `dig server.mydomain.net CNAME`, where server.mydomain.net is CNAME for something else, I write a message back to coredns using the writer and return sucess, but something rejects that message and retries the lookup.

The message I write is:
```
Writing message: ;; opcode: QUERY, status: NOERROR, id: 27824
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;ci.d-gurus.net.	IN	 CNAME

;; ANSWER SECTION:
ci.d-gurus.net.	60	IN	CNAME	internal-concourse-1936881419.us-east-1.elb.amazonaws.com

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 4096
```

I can't figure out why the writer doesn't believe my answer.

Thanks!

**Comment by sean-abbott** [comment]
Ok, so I have this working with upstream the way that I want it to. However, the answer that I'm creating if I request a cname (i.e. `dig server.mydomain.net CNAME`, where server.mydomain.net is CNAME for something else, I write a message back to coredns using the writer and return sucess, but something rejects that message and retries the lookup.

The message I write is:
```
Writing message: ;; opcode: QUERY, status: NOERROR, id: 27824
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;ci.d-gurus.net.	IN	 CNAME

;; ANSWER SECTION:
my.domain.net.	60	IN	CNAME	internal-thing-298793827.us-east-2.elb.amazonaws.com

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 4096
```

I can't figure out why the writer doesn't believe my answer.

Thanks!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] WIP: route53 ..." ]
>Ok, so I have this working with upstream the way that I want it to. However, the answer that I'm creating if I request a cname (i.e. `dig server.mydomain.net CNAME`, where server.mydomain.net is CNAME for something else, I write a message back to coredns using the writer and return sucess, but something rejects that message and retries the lookup.
>
>The message I write is:
>```
>Writing message: ;; opcode: QUERY, status: NOERROR, id: 27824
>;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
>
>;; QUESTION SECTION:
>;ci.d-gurus.net.	IN	 CNAME
>
>;; ANSWER SECTION:
>ci.d-gurus.net.	60	IN	CNAME	internal-concourse-1936881419.us-east-1.elb.amazonaws.com
>
>;; ADDITIONAL SECTION:
>
>;; OPT PSEUDOSECTION:
>; EDNS: version 0; flags: ; udp: 4096
>```
>
>I can't figure out why the writer doesn't believe my answer.

you should probably never have to ask for a CNAME directly, usually you ask for 
A, get a CNAME, follow the CNAME and return an answer that includes both CNAME 
and the resovled target with the actual address. In the above example you only
have the CNAME so the client does not know what to do with it...

**Comment by sean-abbott** [comment]
I guess my concern is that I would like coredns to respond to a given request the same way that other servers do. 

When I issue `dig my.domain.net CNAME` to route53 itself via amazon's DNS servers, I get this response:
```
; <<>> DiG 9.10.3-P4-Ubuntu <<>> my.domain.net CNAME
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52757
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;my.domain.net.			IN	CNAME

;; ANSWER SECTION:
my.domain.net.		30	IN	CNAME	internal-thing-298793827.us-east-2.elb.amazonaws.com.

;; Query time: 17 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Jun 18 10:48:42 EDT 2018
;; MSG SIZE  rcvd: 114
```

When I try to write that very same (AFAICT) message out via coredns, it acts like I didn't have a valid message that I was writing and attempts to re-do the query.

I don't necessarily have a specific use case for doing CNAME queries like this, but isn't it better, according to principle of least surprise, to maintain existing functionality?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] WIP: route53 ..." ]
>Ok, so I have this working with upstream the way that I want it to. However, the answer that I'm creating if I request a cname (i.e. `dig server.mydomain.net CNAME`, where server.mydomain.net is CNAME for something else, I write a message back to coredns using the writer and return sucess, but something rejects that message and retries the lookup.
>
>The message I write is:
>```
>Writing message: ;; opcode: QUERY, status: NOERROR, id: 27824
>;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
>
>;; QUESTION SECTION:
>;ci.d-gurus.net.	IN	 CNAME
>
>;; ANSWER SECTION:
>my.domain.net.	60	IN	CNAME	internal-thing-298793827.us-east-2.elb.amazonaws.com
>
>;; ADDITIONAL SECTION:
>
>;; OPT PSEUDOSECTION:
>; EDNS: version 0; flags: ; udp: 4096
>```
>
>I can't figure out why the writer doesn't believe my answer.

This won't be accepted because the question name doesn't return in the answer, 
answer must be:

ci.d-gurus.net.	60	IN	CNAME	internal-thing-298793827.us-east-2.elb.amazonaws.com

Some clients double check this, some don't.

**Comment by sean-abbott** [comment]
Oh, yeah, sorry, that was just me being a dumbass and not stripping an
internal url. The question name and answer name line up.

**Comment by miekg** [comment]
@dilyevsky is this needed on route53 still? (ping you as new owner and local expert on route53)

**Comment by dilyevsky** [comment]
CNAMEs are now supported by `route53` plugin (we got it for free by using `file` plugin) along with every other Route 53 query type so no.

**Pull request closed without merging**
