### PR TITLE
plugin/cache: Update README for min/default cache size fix

### PR DESCRIPTION
**Pull request by chrisohaver**
### 1. Why is this pull request needed and what does it do?
update docs for change in #2030 

### 2. Which issues (if any) are related?
#2030 

### 3. Which documentation changes (if any) need to be made?

### CODE REVIEW

**Comment by miekg** [comment]
I don't think a map will return memory anyway unless you copy all items to a new map, so the expiry of items won't help.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/cache: Upd..." ]
>
>### 1. Why is this pull request needed and what does it do?
>update docs for change in #2030
>
>### 2. Which issues (if any) are related?
>#2030
>
>### 3. Which documentation changes (if any) need to be made?
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/coredns/coredns/pull/2062

Can we incorperate the actually change to use a smaller cache here as well?

**Review by fturib — APPROVED** [review]
LGTM

**Comment by miekg** [comment]
can you cherry-pick #2030 into here? Should be one PR/commit IMO

**Comment by chrisohaver** [comment]
it was easier to cherry pick into a new PR... small change.

**Pull request closed without merging**
