### PR TITLE
Remove grpc watch functionality

### PR DESCRIPTION
**Pull request by miekg**
This was added, but didn't see any use. For a large, complex chunk of
code we should have some users of it.

Remove all watch functionally from plugins, servers and packages.

Fixes: #2548

### CODE REVIEW

**Comment by miekg** [comment]
And tests failing, because its unclear where wanted watches should be kept

**Comment by miekg** [comment]
oh, end we can't compile the protobuf anymore, something something package too old (had to comment that out to get things to compile)

**Review by chrisohaver — COMMENTED** [review]
lgtm fwiw

**Comment by chrisohaver** [comment]
Actually - i think i missed something in this change.  
Looks like updateModified is no longer called to update the modified time when objects change ... this affects zone transfers, since it is used as the serial.

**Pull request merged**
