### PR TITLE
plugin/rewrite: handle continue in response rewrite

### LINKED ISSUE #1711: plugin/rewrite:  response rewrite with continue option fails
CoreDNS 1.1.1 ...
I found that the `continue` option causes a response re-write rule to not work.

For example...
```
      rewrite continue {
        name regex test\.local kubernetes.default.svc.cluster.local
        answer name kubernetes\.default\.svc\.cluster\.local test.local
      }
```
... fails to rewrite the response ...
```
dnstools# dig test.local. -t A
;; Question section mismatch: got kubernetes.default.svc.cluster.local/A/IN
```
... while ...
```
      rewrite stop {
        name regex test\.local kubernetes.default.svc.cluster.local
        answer name kubernetes\.default\.svc\.cluster\.local test.local
      }
```
... works fine ...
```
dnstools# dig test.local. -t A

; <<>> DiG 9.11.1-P1 <<>> test.local. -t A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39949
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: bf7f5bede8bb8ece (echoed)
;; QUESTION SECTION:
;test.local.			IN	A

;; ANSWER SECTION:
test.local.		5	IN	A	10.0.0.1

;; Query time: 0 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Fri Apr 20 18:54:20 UTC 2018
;; MSG SIZE  rcvd: 67
```

### PR DESCRIPTION
**Pull request by chrisohaver**
### 1. What does this pull request do?

allows `continue` response rewrites rules to execute.

### 2. Which issues (if any) are related?

fixes #1711

### CODE REVIEW

**Comment by chrisohaver** [comment]
Manually tested with the following rules ...

```
.:5553 {
  errors
  reload 2s
  rewrite continue name regex (.*)bolx(.*)\. {1}blox{2} answer name (.*)blox(.*) {1}bolx{2}\.
  rewrite continue name regex (.*)moc(.*)\. {1}com{2} answer name (.*)com(.*) {1}moc{2}\.
  forward . /etc/resolv.conf
}
```

**Review by miekg — COMMENTED** [review]
should this have a test to exposes the bug?

**Comment by chrisohaver** [comment]
> should this have a test to exposes the bug?

Ideally yes... trying to figure out best way to test it... i think in `reverter_test.go`

**Comment by chrisohaver** [comment]
Travis isn't looking too good...  #1741

**Review by greenpau — APPROVED** [review]
@chrisohaver , LGTM 👍

**Comment by miekg** [comment]
thanks all!

**Comment by feresberbeche** [comment]
Thank you @chrisohaver

**Pull request merged**
