### PR TITLE
Add GCP Cloud DNS plugin

### PR DESCRIPTION
**Pull request by maguro**
Adds the GCP Cloud DNS plugin named gcpdns.

### 1. Why is this pull request needed and what does it do?

Adds a GCP Cloud DNS plugin.

### 2. Which issues (if any) are related?

https://github.com/coredns/coredns/issues/2822

### 3. Which documentation changes (if any) need to be made?

Plugin comes with documentation in its `README.md`

### 4. Does this introduce a backward incompatible change or deprecation?

None

### CODE REVIEW

**Comment by miekg** [comment]
I think this is being done in https://github.com/coredns/coredns/pull/3011

**Comment by maguro** [comment]
> I think this is being done in #3011

That's right.  When I posted my PR, #3011 was basically an empty plugin with no code.  As I mentioned in #2822, I had the bulk of this done before I got laid up after my surgery.

With that said, it's not carved in stone.  Any suggestions and or enhancements are most welcome!  :)

**Comment by palash25** [comment]
I wasn't even aware of this PR, I am not sure what to do now.

**Comment by yongtang** [comment]
Given PR #3011 was opened earlier anyway, I think it makes sense to at least wait some time so that @palash25 can try to finish his PR? If PR #3011 could not be completed then other similar PRs could be re-open again?

@miekg what do you think about that?

**Comment by maguro** [comment]
> I wasn't even aware of this PR, I am not sure what to do now.

Yeah, sorry about that.  I thought I had made it pretty clear that I was working on it and though lots of people mentioned that they too were working on PRs, it wasn't clear that there was any substantive work being done.  Given that I need this plugin at work, I just went ahead and did it.

With that said, I'm a big advocate of community over code and am happy to go with community consensus on this, so long as the result is a robust working plugin in the near term.

**Comment by maguro** [comment]
> Given PR #3011 was opened earlier anyway, I think it makes sense to at least wait some time so that @palash25 can try to finish his PR? If PR #3011 could not be completed then other similar PRs could be re-open again?
> 
> @miekg what do you think about that?

As I mentioned above, I'm happy to go along with how this community works, but I'll quicky point out that my plugin is complete.  The reason for this is that I had done the work a while back; something I made clear in #2822.

**Comment by idvoretskyi** [comment]
Thanks for solving this.

**Pull request closed without merging**
