### PR TITLE
plugin/forward: remove truncate logic

### PR DESCRIPTION
**Pull request by miekg**
I think this is causing problem and it will actually clash with the
scrubbing that now happens for all plugins anyway. We're assuming the
returned message will be valid even with tc being set. request.Scrub
follows that same logic.

Signed-off-by: Miek Gieben <miek@miek.nl>

### CODE REVIEW

**Comment by miekg** [comment]
cc @grobie

**Review by rdrozhdzh — DISMISSED** [review]
I see two issues here
1. function `truncated()` cleared error `dns.ErrTruncated`. With your change this error will prevent writing message to writer, i.e. `Scrub()` won't be called
2. function `truncated()` correctly handled `nil` messages in conjunction with error `dns.ErrTruncated`. `Scrub()` doesn't expect `nil` messages at all, it will panic

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>rdrozhdzh requested changes on this pull request.
>
>I see two issues here
>1. function `truncated()` cleared error `dns.ErrTruncated`. With your change this error will prevent writing message to writer, i.e. `Scrub()` won't be called
>2. function `truncated()` correctly handled `nil` messages in conjunction with error `dns.ErrTruncated`. `Scrub()` doesn't expect `nil` messages at all, it will panic

Upstream issue to remove this entire thing that requires(d) this logic: https://github.com/miekg/dns/issues/814

**Comment by rdrozhdzh** [comment]
I'm ok with such approach
One more note. Method `Forward.Forward()` doesn't write message to writer, and therefore doesn't call `Scrub()`. Outer code should take care of calling Scrub() if needed. This may affect behavior of existing code

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>I'm ok with such approach
>One more note. Method `Forward.Forward()` doesn't write message to writer, and therefore doesn't call `Scrub()`. Outer code should take care of calling Scrub() if needed. This may affect behavior of existing code

that's a very good point, and I hadn't though about it. Let me fix
some stuff there as well.

**Review by rdrozhdzh — APPROVED** [review]
LGTM
The issues were addressed in #2331 and #2346

**Pull request merged**
