### PR TITLE
Make every one an approver

### PR DESCRIPTION
**Pull request by miekg**
This is already true; as everyone listed here can 'click merge', extend
this functionally to the bot as well.

Code from dreck:
~~~
	if len(config.Reviewers) == 0 && len(config.Approvers) > 0 {
		config.Reviewers = config.Approvers
	}

~~~
This is why @dilyevsky couldn't use `/merge` (most likely; didn't check the logs)

Signed-off-by: Miek Gieben <miek@miek.nl>

### CODE REVIEW

**Review by chrisohaver — APPROVED** [review]
LGTM

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Make every on..." ]
>chrisohaver approved this pull request.
>
>LGTM

/merge

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by miekg** [comment]
hmm

/merge

**Comment by chrisohaver** [comment]
corbot doesn't like email reply comments?

**Pull request merged**
