### PR TITLE
Add option to parse resolv.conf for proxy upstreams

### PR DESCRIPTION
**Pull request by johnbelamaric**

### CODE REVIEW

**Comment by miekg** [comment]
Hehe, nice I have something fairly similar. Happy to take this one forward.

I had this in as well:

```
+                                       if err == os.ErrNotExist {
+                                               // Return original not an  IP address error.
+                                               return upstreams, fmt.Errorf("not an IP address: `%s'", h)
+                                       }
```

And of course README updates and a test please :)

**Comment by miekg** [comment]
Took this PR, added some fluff and made #354

**Comment by miekg** [comment]
Also started wiki for the release notes: https://github.com/miekg/coredns/wiki/CoreDNS-003-Release

**Comment by johnbelamaric** [comment]
Oh, didn't check mail or GitHub before making more changes.

**Comment by miekg** [comment]
No matter, looks good.

**Pull request merged**
