### PR TITLE
CI: add drone.io for arm64 verification

### PR DESCRIPTION
**Pull request by lubinsz**
Signed-off-by: Bin Lu <bin.lu@arm.com>

### 1. Why is this pull request needed and what does it do?
We want to enable arm ci for CNCF projects one by one.

### 2. Which issues (if any) are related?
None.
### 3. Which documentation changes (if any) need to be made?
README.md

### 4. Does this introduce a backward incompatible change or deprecation?
None

### CODE REVIEW

**Comment by lubinsz** [comment]
@miekg @chrisohaver @johnbelamaric 
Hi, to enable the arm ci with Drone.io needs to be allowed to access repo just as travis does.
An example could be found here: 
https://cloud.drone.io/lubinsz/coredns
I think, we should also active the repo in drone.io, such as https://cloud.drone.io/coredns/coredns
Thanks.

**Comment by miekg** [comment]
> We want to enable arm ci for CNCF projects one by one.

Why? What do you expect to find?

**Comment by lubinsz** [comment]
> > We want to enable arm ci for CNCF projects one by one.
> 
> Why? What do you expect to find?

We hope to ensure that every cncf project can be run normally on arm server.
Currently, we have already eanbled arm ci for containerd & envoy.
Please see following as reference:
https://github.com/containerd/containerd/pull/3242
https://github.com/envoyproxy/envoy/pull/6981

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CI: add drone..." ]
>> > We want to enable arm ci for CNCF projects one by one.
>>
>> Why? What do you expect to find?
>
>We hope to ensure that every cncf project can be run normally on arm server.
>Currently, we have already eanbled arm ci for containerd & envoy.
>Please see following as reference:
>https://github.com/containerd/containerd/pull/3242
>https://github.com/envoyproxy/envoy/pull/6981

Sure. Fork the repo, setup your own CI. Sync via cron (or whatever) and file 
bugs.

**Pull request closed without merging**
