### PR TITLE
Benching

### PR DESCRIPTION
**Pull request by miekg**
Run benchmarks on Travis

### CODE REVIEW

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by miekg** [comment]
I only wished I could get this to show up in a github pr comment:
~~~
/home/travis/gopath/bin/benchcmp
benchmark                       old ns/op     new ns/op     delta
BenchmarkCacheResponse-2        4498          4486          -0.27%
BenchmarkFileLookupDNSSEC-2     46482         46126         -0.77%
BenchmarkFileParseInsert-2      843729        834789        -1.06%
BenchmarkFileLookup-2           6786          15453         +127.72%
BenchmarkCache-2                99.6          149           +49.60%
BenchmarkMinimalTTL-2           84.7          142           +67.65%
BenchmarkRequestDo-2            2.93          2.94          +0.34%
BenchmarkRequestSize-2          3.30          3.29          -0.30%
BenchmarkRequestScrub-2         5830          5805          -0.43%
BenchmarkCoreServeDNS-2         443           1042          +135.21%
benchmark                       old allocs     new allocs     delta
BenchmarkCacheResponse-2        29             29             +0.00%
BenchmarkFileLookupDNSSEC-2     194            194            +0.00%
BenchmarkFileParseInsert-2      678            678            +0.00%
BenchmarkFileLookup-2           64             64             +0.00%
BenchmarkCache-2                0              0              +0.00%
BenchmarkMinimalTTL-2           0              0              +0.00%
BenchmarkRequestDo-2            0              0              +0.00%
BenchmarkRequestSize-2          0              0              +0.00%
BenchmarkRequestScrub-2         99             99             +0.00%
BenchmarkCoreServeDNS-2         5              5              +0.00%
benchmark                       old bytes     new bytes     delta
BenchmarkCacheResponse-2        512           512           +0.00%
BenchmarkFileLookupDNSSEC-2     6720          6720          +0.00%
BenchmarkFileParseInsert-2      116289        116290        +0.00%
BenchmarkFileLookup-2           2064          2064          +0.00%
BenchmarkCache-2                0             0             +0.00%
BenchmarkMinimalTTL-2           0             0             +0.00%
BenchmarkRequestDo-2            0             0             +0.00%
BenchmarkRequestSize-2          0             0             +0.00%
BenchmarkRequestScrub-2         5808          5808          +0.00%
BenchmarkCoreServeDNS-2         160           160           +0.00%
~~~
Also, look at those bullshit timings, at least the allocs are sane.

**Comment by yongtang** [comment]
@miekg I can take a look and see if the benchmark could be posted to GitHub

**Comment by miekg** [comment]
Thanks, something like this https://damien.pobel.fr/post/github-api-from-travisci/ should work, I guess.

**Comment by miekg** [comment]
for ns/ops we need something else prolly as travis is not reliable.

**Pull request merged**
