### PR TITLE
Remove grobie from maintainers

### PR DESCRIPTION
**Pull request by grobie**
I haven't been maintaining production DNS setups in quite a while and
don't have the time to review CoreDNS pull requests. Hereby I resign
from all positions in the CoreDNS project.

CoreDNS is a great project and SoundCloud still processes hundreds of
thousands of requests per second with the help of CoreDNS. Thanks a lot
for your hard work and all the best for the future.

### CODE REVIEW

**Review by SuperQ — APPROVED** [review]
LGTM. :heart:

**Review by yongtang — APPROVED** [review]
LGTM and thanks for your work! ❤️

**Comment by zouyee** [comment]
❤️

**Comment by miekg** [comment]
Sad to see you leave... Thanks for the time you've put in to make CoreDNS better!

**Review by miekg — APPROVED** [review]

**Pull request merged**
