### PR TITLE
complete transfer test case

### PR DESCRIPTION
**Pull request by zouyee**
Signed-off-by: zounengren <zounengren@cmss.chinamobile.com>

### 1. Why is this pull request needed and what does it do?
complete transfer test case

### 2. Which issues (if any) are related?
none

### 3. Which documentation changes (if any) need to be made?
none

### 4. Does this introduce a backward incompatible change or deprecation?
none

### CODE REVIEW

**Comment by chrisohaver** [comment]
Many of the changes in this PR are unrelated to the transfer test cases.

**Comment by yongtang** [comment]
@zouyee Can you update the PR based on comment from @chrisohaver ? Could split into PRs with single focus.

**Review by yongtang — APPROVED** [review]
lgtm

**Pull request merged**
