### PR TITLE
WIP: Crazy idea: install certs on startup

### PR DESCRIPTION
**Pull request by miekg**

### CODE REVIEW

**Comment by miekg** [comment]
@yongtang how crazy/stupid is this?

**Comment by yongtang** [comment]
I think it makes sense in many situations. Though sometimes user may prefer not to start an outbound connection when they launch coredns. So maybe we could make it optional?

**Comment by yongtang** [comment]
On a second thought, maybe we could ask user to mount the certs directory in the host to the directory in coredns container? Haven't tried it but I think it might be possible.

**Comment by miekg** [comment]
I like your idea as this would side step of a lof problems. Let me experiment with that.

**Comment by johnbelamaric** [comment]
Yes, I think that is much better. It also makes it easy to use your own CA certs.

**Pull request closed without merging**
