### PR TITLE
middleware/proxy: make it scale

### PR DESCRIPTION
**Pull request by miekg**

### CODE REVIEW

**Comment by miekg** [comment]
work-in-progess . Do not merge (yet)

**Comment by miekg** [comment]
@mrichmon @johnbelamaric do you guys have a setup the can actual benchmark the proxy? Current master, this PR and skydns would be cool?
I lack the machine and network to do this properly and using localhost makes the linux kernel bypass all socket io, resulting in a bad test.

The added benchmark in `proxy_test.go` does show a 100% increase in speed.

**Comment by miekg** [comment]
Can't be merged until test coverage is up.

**Comment by johnbelamaric** [comment]
Yeah, we can do some benchmarks, we have some tools for that and plenty of VM capacity at least. I will discuss with @chrisohaver on Monday. Might be a couple days though based on other stuff on our plates.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/prox..." ]

> Yeah, we can do some benchmarks, we have some tools for that and plenty of VM capacity at least. I will discuss with @chrisohaver on Monday. Might be a couple days though based on other stuff on our plates.

cool. Thank you

**Comment by chrisohaver** [comment]
Hi @miekg ,
I did benchmarks for skydns, coredns, and coredns w/ this PR.
Unfortunately, the performance appears to be negatively affected by the changes.  

I tested by running a tool on a separate system which runs dns queries as fast as it can, in 10 threads, for 30 seconds.
coredns and skydns were set up with all default configs, except for proxy configuration.

Here are the results ...

### coredns + PR
- Elapsed Time (s):             30.005
- Requests:                 650568
- Replies:                  650568
- Timeouts:                 0
- Requests/Second:          21681.707
- Latency Min/Max/Avg (ms): 0.414/53.230/11.525

### coredns
- Elapsed Time (s):             30.005
- Requests:                 1009588
- Replies:                  1009588
- Timeouts:                 0
- Requests/Second:          33647.043
- Latency Min/Max/Avg (ms): 0.405/31.431/7.424

### skydns
- Elapsed Time (s):             30.005
- Requests:                 1153277
- Replies:                  1153277
- Timeouts:                 0
- Requests/Second:          38436.775
- Latency Min/Max/Avg (ms): 0.342/27.132/6.499

### direct to nameserver
- Elapsed Time:             30.003
- Requests:                 1672745
- Replies:                  1672742
- Timeouts:                 3
- Requests/Second:          55752.911
- Latency Min/Max/Avg (ms): 2.026/19.909/4.462

**Comment by miekg** [comment]
Hola... Interesting. CoreDNS wise I think I can explain this: out of the box (current code) does a lot more than SkyDNS. CoreDNS+PR probably spins on getting a socket.

Wrt to SkyDNS, things become interesting. Because... this is not what we see in the wild, but that is with adding docker.

**Comment by miekg** [comment]
This PR still cleans the proxy code quite a bit, killing the socket pooling and just allocating a new one is a pretty trivial change at this point.

**Comment by miekg** [comment]
Btw: super awesome those benchmarks! Any change we can cronjob this and export/graph it somewhere?

**Comment by johnbelamaric** [comment]
I wonder if we can do it in Travis? We could push the test tool to a docker image and maybe we can pull it and run the test in CI.

**Comment by johnbelamaric** [comment]
In that issue above, there is a lot of discussion around caching. I believe the tests above are just for proxy. Is there builtin cache of that data or if we enable caching will the proxied results be cached? Because the test is only running against like 3 A records.

**Comment by miekg** [comment]
If you enable the cache (in CoreDNS) these requests will be cached, in SkyDNS you can't do that. 

Raw proxy benchmarking is the benchmark we want.

These requests are traversing a (non localhost) network, are they?

We could do this in travis, but you need 2 machines (VMs) to setup and then bench. Also VMs might skew the results, because: VMs

**Comment by johnbelamaric** [comment]
Right, getting two VMs may be a hassle. This test is done with VMs in our OpenStack lab. The client VM and CoreDNS/SkyDNS VM (CoreDNS/CoreDNS+PR/SkyDNS were run on the same VM, one at a time) are on the same compute node, but the IPs used are floating IPs, so what is happening is the packets are going out to the network, being NAT'd on a network node, and hair-pinning back to the compute node. In other words, it hits a physical network and a virtual router.

The DNS server they are proxying TO is on a different compute node and is also accessed via a floating IP.

**Comment by chrisohaver** [comment]
@miekg , This test was done purely on VMs ... though they were done on a generally inactive local open stack cloud. I ran the tests within minutes of each other - and they didn't have significant performance variability between runs.  So, I think it was a fair apples to apple comparison.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/prox..." ]

> @miekg , This test was done purely on VMs ... though they were done on a generally inactive local open stack cloud. I ran the tests within minutes of each other - and they didn't have significant performance variability between runs.  So, I think it was a fair apples to apple comparison.

Ack and OK.

**Comment by miekg** [comment]
Using a server that directly does: `Queries per second:   13259.364298 qps`. Both client and server are located in NL. (it fluctuates a bit; I expect the server does RRL or something).

With CoreDNS as a proxy I get:
* `Queries per second:   7938.770849 qps`

Sometimes I goes to 15kqps but not often. This is with CoreDNS from master (without this reworked branch).

**Comment by miekg** [comment]
Doing a test (over the internet) to a .nl nameserver, I get directly:

```
Queries per second:   12625.701282 qps
```

Sometimes lower (I suspect RRL or something)

Using the proxy (from master, without this branch):

```
Queries per second:   6383.047678 qps
```

When queries fail, we mark the backend as fails, this can be handy, but kills the throughput of course

**Comment by miekg** [comment]
This branch: slight improvement: `Queries per second:   6536.355203 qps`
(i.e. simpler code in CoreDNS)

**Comment by miekg** [comment]
Taking cpu profile:

```
      flat  flat%   sum%        cum   cum%
    2810ms 16.76% 16.76%     3050ms 18.19%  syscall.Syscall
     730ms  4.35% 21.11%      730ms  4.35%  runtime.adjustpointers
     730ms  4.35% 25.46%     1920ms 11.45%  runtime.pcvalue
     570ms  3.40% 28.86%      570ms  3.40%  runtime.readvarint
     540ms  3.22% 32.08%      730ms  4.35%  runtime.scanobject
     540ms  3.22% 35.30%      540ms  3.22%  syscall.RawSyscall
     520ms  3.10% 38.40%      520ms  3.10%  runtime.usleep
     510ms  3.04% 41.44%      920ms  5.49%  runtime.mallocgc
     400ms  2.39% 43.83%      970ms  5.78%  runtime.step
     350ms  2.09% 45.92%     3380ms 20.16%  runtime.gentraceback
```

**Comment by miekg** [comment]
`top -cum`

```
(pprof) top -cum
0.30s of 16.77s total ( 1.79%)
Dropped 213 nodes (cum <= 0.08s)
Showing top 10 nodes out of 187 (cum >= 3.97s)
      flat  flat%   sum%        cum   cum%
         0     0%     0%     11.58s 69.05%  runtime.goexit
     0.04s  0.24%  0.24%      9.85s 58.74%  github.com/miekg/dns.(*Server).serve
         0     0%  0.24%      9.45s 56.35%  github.com/miekg/dns.(*ServeMux).ServeDNS
     0.05s   0.3%  0.54%      9.32s 55.58%  github.com/miekg/coredns/core/dnsserver.(*Server).ServeDNS
     0.03s  0.18%  0.72%      9.21s 54.92%  github.com/miekg/coredns/middleware/errors.(*errorHandler).ServeDNS
     0.04s  0.24%  0.95%      9.18s 54.74%  github.com/miekg/coredns/middleware/errors.errorHandler.ServeDNS
     0.02s  0.12%  1.07%      9.05s 53.97%  github.com/miekg/coredns/middleware/proxy.(*Proxy).ServeDNS
     0.07s  0.42%  1.49%      9.02s 53.79%  github.com/miekg/coredns/middleware/proxy.Proxy.ServeDNS
     0.04s  0.24%  1.73%      5.83s 34.76%  github.com/miekg/coredns/middleware/proxy.(*Client).ServeDNS
     0.01s  0.06%  1.79%      3.97s 23.67%  runtime.morestack
```

**Comment by miekg** [comment]
Redoing with a more random list (public-domain-lists/opendns-random-domains.txt), to avoid single-inflight: 6122.948812 qps.
So this halves the qps (which can be acounted for seeing the work that CoreDNS does).

**Pull request merged**
