### PR TITLE
Ignore vscode settings file

### PR DESCRIPTION
**Pull request by zouy414**
Signed-off-by: ZouYu <zouy.fnst@cn.fujitsu.com>

### 1. Why is this pull request needed and what does it do?
Ignore vscode settings file
### 2. Which issues (if any) are related?
None
### 3. Which documentation changes (if any) need to be made?
None
### 4. Does this introduce a backward incompatible change or deprecation?
None

### CODE REVIEW

**Comment by stp-ip** [comment]
Thanks for the PR.

This needs a bit of discussion in general. Using this PR as initial reasoning.

Overall it is the sentiment that adding gitignore options for individual editor choices shouldn't be done. With these coming up more and more we should once and for all take a stance. Either we merge and keep or we don't allow this and remove the options we already have.

cc. @miekg @yongtang (referenced as you previously merged the most of those)

In my view they are not hard PRs to merge, but without a clear yes/no policy one might argue it we should be open to merging every gitignore PR specific to an editor.

**Comment by stp-ip** [comment]
Sidenote: https://github.com/coredns/coredns/pull/2628

**Comment by SuperQ** [comment]
In Prometheus, I think we made the decision to not sprinkle editor file exceptions into our git ignores. 

We do exclude built binaries and build-related output. But nothing for specific editors.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Ignore vscode..." ]
>In Prometheus, I think we made the decision to not sprinkle editor file
>exceptions into our git ignores.
>
>We do exclude built binaries and build-related output. But nothing for specific
>editors.

yes! I want to do the same here

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Ignore vscode..." ]
>In Prometheus, I think we made the decision to not sprinkle editor file
>exceptions into our git ignores.
>
>We do exclude built binaries and build-related output. But nothing for specific
>editors.

see #3820

/close

**Pull request closed without merging**
