### PR TITLE
Governance: Clarify definition of "Transparent and accessible"

### PR DESCRIPTION
**Pull request by chrisohaver**
### 1. Why is this pull request needed and what does it do?

Clarify the principles per discussion in #2220.

Comment: https://github.com/coredns/coredns/pull/2220#discussion_r232325844

### CODE REVIEW

**Comment by chrisohaver** [comment]
+1

**Review by johnbelamaric — APPROVED** [review]

**Comment by fturib** [comment]
Following the Governance, we need a vote for theses changes.
It is time for training the vote mechanism :)

**Review by yongtang — APPROVED** [review]

**Comment by fturib** [comment]
+1

**Comment by yongtang** [comment]
@fturib vote technically needs time and has restrictions. Let's instead consider this PR as part of the GOVERNANCE.md update in 11/12/2018.

**Review by rajansandeep — APPROVED** [review]
+1

**Comment by fturib** [comment]
@yongtang : I am ok with your proposition.

**Comment by yongtang** [comment]
The coredns repo change is pretty clear. For organization change, I would consider cncf-related activities (e.g., level, involvement, etc) are part of the "coredns organization changes" as it does have an impact to coredns.

**Pull request merged**
