### PR TITLE
 plugin/etcd: make the address of upstream optional

### LINKED ISSUE #2099: upstream is optional in etcd
The upstream in etcd is optional (according to the README), but it is not allowed in the setup.

### PR DESCRIPTION
**Pull request by jiachengxu**
### 1. Why is this pull request needed and what does it do?
- fix #2099 
- Add 2 tests for upstream in etcd plugin. 
### 2. Which issues (if any) are related?
#2099 
### 3. Which documentation changes (if any) need to be made?
N/A

### CODE REVIEW

**Comment by jiachengxu** [comment]
HI @miekg, I remember that we have the same problem in plugin/route53(see https://github.com/coredns/coredns/pull/2050#discussion_r216756944), should I fix it here or open a new separate PR?

**Review by chrisohaver — APPROVED** [review]
LGTM

**Comment by chrisohaver** [comment]
> should I fix it here or open a new separate PR?

IMO, Which ever you prefer.

**Comment by miekg** [comment]
/merge

Thanks Chris

**Comment by miekg** [comment]
Small PRs are preferred.

**Pull request merged**
