### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cricketliu**
Minor textual cleanup.

### CODE REVIEW

**Comment by miekg** [comment]
uhm, where is this DCO check coming from?

**Comment by cricketliu** [comment]
On Sep 5, 2019, at 11:41 AM, Miek Gieben <notifications@github.com<mailto:notifications@github.com>> wrote:

uhm, where is this DCO check coming from?

I don't even know what a DCO check is!  Dynamic Creative Optimization?  Seems like that doesn't relate to docs.

cricket

**Comment by miekg** [comment]
developer certificate of origin - i.e. you didn't copy this code from somewhere else.

signing off your commits "fixes" this - but we've never had this check, so ??

**Comment by johnbelamaric** [comment]
I see it in the org github apps. Not sure how it got there

@yongtang @stp-ip @caniszczyk did one of you install this DCO app?

**Comment by johnbelamaric** [comment]
Looking at GitHub it was just installed 20 minutes or so ago...

**Comment by yongtang** [comment]
Not aware of it. Is this part of the CNCF or a new feature from GitHub?

**Comment by stp-ip** [comment]
Don't have the access to install any Github Apps so definitely not me ;)

**Comment by caniszczyk** [comment]
FYI we enabled it after a project wide audit, CoreDNS should have the DCO bot enabled (or equivalent) due to the CNCF IP Policy

**Pull request merged**
