### PR TITLE
make sure client CA and auth type are set if CA is explicitly specified.

### PR DESCRIPTION
**Pull request by jinmeiib**
### 1. Why is this pull request needed and what does it do?

The current implementation of the tls plugin doesn't require client
certificate even if the CA parameter of the plugin configuration is
explicitly specified.  And, as a result, client authentication is
impossible.

It's not very clear whether it's intentional, but it doesn't seem to
make sense to allow the user to specify "CA" if the server doesn't
even request a client certificate.  So I assume at least the first
point is unintentional.

The change in this pull request is one easy way to fix it.  It now also
makes sure the client certificate is validated with the specified CA;
if it doesn't validate, the server won't accept the connection.

There may be other way to address these problems.  The change in this
PR is rather to demonstrate the issue and its cause.

### 2. Which issues (if any) are related?

No.  I've not filed a separate github issue on this.

### 3. Which documentation changes (if any) need to be made?

README.md of the tls plugin will probably have to be updated to
clarify the effect of parameter 'CA'.  I'd also note that the current
description about the use of system CAs can be misleading, since the
server doesn't request client's certificate or validate it if
parameter 'CA' is omitted.

### 4. Does this introduce a backward incompatible change or deprecation?

Yes, depending on the user's expectation.  Previously, even if
parameter CA was specified and the client wasn't configured with a
valid certificate, TLS connections from the client would be accepted.
Such connection attempts will now be rejected.

If this compatibility issue is a concern, we may have to extend the
configuration syntax to have another parameter that specifies the
certification validation policy.

### CODE REVIEW

**Comment by johnbelamaric** [comment]
I agree this is necessary. The original intent was to validate the client cert, and so this is really a bug fix. However, I am concerned about two things:

1) The change in behavior is dramatic.
2) We should offer a way to have the system CAs validate the cert, this change won't allow that.

So...how about instead we:

1) Add a `client_auth` option with values corresponding to [tls.ClientAuthType](https://golang.org/pkg/crypto/tls/#ClientAuthType) `none` (default), `request`, `require`, `verify_if_given`, `require_and_verify`.
2) This would be added in version 1.6.0 - include a release note that in version 1.7.0, the default will change to `require_and_verify` if the CA is configured.

Then, what I'd really like to see (separate PR) is if `metadata` is enabled, then add some TLS-related metadata that can be used in logging and firewall/policy plugins, see: https://github.com/coredns/coredns/issues/2426#issuecomment-454141924. That makes `request` meaningful, because we can log - otherwise it's useless.

**Comment by jinmeiib** [comment]
It makes sense to introduce an option to specify the client auth policy (as noted in the PR description I was aware of the concern).  Would you like me to update the code in this PR as such?  If so, do you mean the syntax of the tls plugin now looks like this?

```
tls CERT KEY [CA] {
  [client_auth none|request|require|verify_if_given|require_and_verify]
}
```

As for the `metadata` thing, that's actually another trouble I had while trying to use client authentication.  For now I have a workaround of extracting the TLS connection state from `dns.ResponseWriter`, but providing a generic way makes a lot more sense.

**Comment by johnbelamaric** [comment]
Yes, that is correct, please implement that syntax change. Thanks!!

**Comment by jinmeiib** [comment]
I've just pushed some new commits with the suggested changes.  I'd appreciate it if you could review it.

**Comment by jinmeiib** [comment]
Hi @johnbelamaric 
If you have time, could you re-review the latest change?  I've realized a CI test failure, but it doesn't seem to be related to my change.  If there's anything else I should have done and you could point it out, I'd appreciate it very much. (I'm not particularly in a hurry, but I wanted to make sure I've done what I was supposed to do).

**Comment by johnbelamaric** [comment]
/lgtm
/approve

Please though add a release note indicating that the default will change in 1.7

**Pull request merged**
