### PR TITLE
plugin/rewrite: add handling of TTL field rewrites

### PR DESCRIPTION
**Pull request by greenpau**
Resolves: #1981

### 1. Why is this pull request needed and what does it do?

This PR allows the rewriting of TTL field in DNS answers.

### 2. Which issues (if any) are related?

#1981 

### 3. Which documentation changes (if any) need to be made?

Add a section for TTL rewrites in the plugin's README.md

### CODE REVIEW

**Comment by greenpau** [comment]
@chrisohaver , I noticed Travis integration test did run. Is this the expected behavior for WIP PRs?

**Comment by chrisohaver** [comment]
Yeah - tests still run on WIPs... it's free/cheap.... and useful depending on which stage of developing the PR you are in.

**Comment by greenpau** [comment]
@chrisohaver , @makinje16 , please review if you can.

**Comment by greenpau** [comment]
@johnbelamaric , congrats on your new position 🚀 👍 . I reassigned reviewers being conscious of you might be busy with on-boarding. Nevertheless, if you can review this one, please do 😄

**Review by chrisohaver — COMMENTED** [review]
Looks good.  One concern I have though is that this new TTL rewrite rule is, essentially, an *answer* rewrite (it's re-writing TTLs in the response)...  but its syntax follows *query* rewrite syntax.

**Comment by greenpau** [comment]
> One concern I have though is that this new TTL rewrite rule is, essentially, an answer rewrite (it's re-writing TTLs in the response)... but its syntax follows query rewrite syntax.

@chrisohaver , you are correct. However, there is not TTL in the request. That's why I am thinking making it `rewrite ttl` is less confusing than `rewrite answer ttl`. What is the syntax you propose?

@miekg , what is your thought on the above?

Whatever you guys decide is fine by me. I will implement any syntax, as long as there is a consensus 😃

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/rewrit..." ]
>> One concern I have though is that this new TTL rewrite rule is, essentially, an answer rewrite (it's re-writing TTLs in the response)... but its syntax follows query rewrite syntax.
>
>@chrisohaver , you are correct. However, there is not TTL in the request. That's why I am thinking making it `rewrite ttl` is less confusing than `rewrite answer ttl`. What is the syntax you propose?
>
>@miekg , what is your thought on the above?
>
>Whatever you guys decide is fine by me. I will implement any syntax, as long as there is a consensus 😃

Haven't followed this PR in detail. I care about simplicity and consistency (for 
the user). So if it is not confusing it's fine by me; if it needs (a lot) of 
extra docs so explain, we should probably revisit.

**Comment by greenpau** [comment]
@chrisohaver , the current syntax is simple enough, no confusion. Let’s go with it?

**Comment by chrisohaver** [comment]
The existing answer re-write is a bit unusual anyways ... Given that, maybe its a bad idea to try to be consistent with it.  So, your initial syntax may be best.

To be consistent with the existing answer name rewrite, the syntax would be something like...

```
rewrite [continue|stop] name regex STRING answer ttl TTL
```
or in the pseudo 2 rule format ...
```
rewrite [continue|stop] {
    name regex STRING 
    answer ttl TTL
}
```

perhaps adding a `match` keyword would make it less ambiguous to parse...

```
rewrite [continue|stop] match name regex STRING answer ttl TTL
```
or in the pseudo 2 rule format ...
```
rewrite [continue|stop] {
    match name regex STRING 
    answer ttl TTL
}
```
Whichever way, it should also be documented in the **Syntax** section, and not just in a separate section added to the end.

**Comment by chrisohaver** [comment]
IMO, We should probably re-think the syntax on answer name re-writes...

The only use case is to restore names to original after a qname re-write.  In that sense, there should be no need to specify the query name string 4 times.  Two should be sufficient, e.g. ...

```
rewrite [continue|stop] name regex STRING STRING answer name restore
```

Or - we just always make it restore the name on a name re-writes by default.
Then we can deprecate, and eventually remove the answer name rewrite syntax.

**Comment by greenpau** [comment]
@chrisohaver , let’s keep this PR separate from the bigger thing. I understand what you are saying, but it should have its own issue and its own PR (linked to this one by reference).

What are you proposing to change in this one, lines and suggestions? I will follow. I cannot think in abstact here.

**Comment by chrisohaver** [comment]
> let’s keep this PR separate from the bigger thing. I understand what you are saying, but it should have its own issue and its own PR (linked to this one by reference).

Obviously.  Yes, I agree.

**Comment by greenpau** [comment]
@chrisohaver , like the “match name” proposal, but let’s cover it in a separate issue.

**Comment by chrisohaver** [comment]
> What are you proposing to change in this one, lines and suggestions? I will follow. I cannot think in abstact here.

Please also document the new option in the Syntax section of the README (i.e. in the "FIELD" section, which starts at line [19](https://github.com/coredns/coredns/pull/2048/files#diff-e805684cc3e7aef334b3ac12d4a47319R19)).

**Comment by greenpau** [comment]
> Please also document the new option in the Syntax section of the README (i.e. in the "FIELD" section, which starts at line 19).

@chrisohaver , done.

**Review by chrisohaver — APPROVED** [review]

**Pull request merged**
