### PR TITLE
plugin/forward: various cleanup

### PR DESCRIPTION
**Pull request by miekg**
Fix documentation and remove the unused From method.

Signed-off-by: Miek Gieben <miek@miek.nl>

### CODE REVIEW

**Comment by rdrozhdzh** [comment]
@miekg, the method Forward.From() was requested in #1762, and added in #1766. It may be still needed.
@fturib, @ekleiner, could you confirm?

**Comment by miekg** [comment]
Ah yes, damn, I remember.  Something, something that needed this. If there are no in-tree users of exported functions this is not sustainable (and there is no backwards compatibility guarantee)

**Comment by fturib** [comment]
@rdrozhdzh : thank you for reminding these requests.
After check in our ATEPMonitor plugin, I think we are not using it anymore.

@miekg : what do you mean by "in-tree users of exported functions" ? I mean, how should we code the functions we need to be public for external plugins such a way they will not be deleted in refactoring ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>@rdrozhdzh : thank you for reminding these requests.
>After check in our ATEPMonitor plugin, I think we are not using it anymore.
>
>@miekg : what do you mean by "in-tree users of exported functions" ? I mean, how should we code the functions we need to be public for external plugins such a way they will not be deleted in refactoring ?
>

We can't be expected to maintain some sort of backwards compatibility for 
(probably, accidentally) export functions *in* plugins.

And now you tell me you actually don't need (nor use) those functions anyway, 
which just proofs my point.

/Miek

--
Miek Gieben

**Pull request merged**
