### PR TITLE
Add Kubernetes auth providers

### PR DESCRIPTION
**Pull request by johnbelamaric**
### 1. Why is this pull request needed and what does it do?
With the merge of the #2053, we can now use a kubeconfig file for out-of-cluster Kubernetes integrations. However, the different auth providers were not included in that PR. Add them, which requires adding new vendored libraries. Also add auto-pruning in Gopkg.toml.

### 2. Which issues (if any) are related?
None

### 3. Which documentation changes (if any) need to be made?
None, these are the standard providers that client-go supports, so users will expect them to work already with #2053.

### CODE REVIEW

**Comment by miekg** [comment]
Can you split the comments in a 'code added'/'dep updated'? Both commits now contain a lot of changed files.

**Comment by johnbelamaric** [comment]
Rebased on #2151 and also split code change and dep update into two separate commits.

**Review by chrisohaver — APPROVED** [review]
LGTM, once the vendor issues are cleared up.

**Comment by johnbelamaric** [comment]
I do not understand. This built for me on Friday.

**Pull request merged**
