### PR TITLE
plugin/pkg/up: make default intervals shorter

### PR DESCRIPTION
**Pull request by miekg**
I think 15 min is too high, make this lower to react faster.

### CODE REVIEW

**Comment by miekg** [comment]
cc @RickyRajinder

**Review by yongtang — APPROVED** [review]
LGTM

**Review by rickywraith — APPROVED** [review]

**Comment by rickywraith** [comment]
This would also require the README to be updated

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/pkg/up..." ]
>This would also require the README to be updated

duh, of course :-) will do

/Miek

--
Miek Gieben

**Pull request merged**
