### PR TITLE
WIP: Migrate k8s middleware to client-go

### PR DESCRIPTION
**Pull request by aledbf**
do not merge

### CODE REVIEW

**Comment by aledbf** [comment]
@miekg just in case I didn't forget this PR. I'm waiting for https://github.com/kubernetes/client-go/issues/27 and https://github.com/kubernetes/client-go/issues/24

**Comment by johnbelamaric** [comment]
I think I have this just about working with #379

**Comment by miekg** [comment]
You guys fight it out :) I'm out for diner

**Comment by miekg** [comment]
think this is now not needed anymore as I merged #379. (more fixes welcome of course)

**Pull request closed without merging**
