### PR TITLE
startup: add logo

### PR DESCRIPTION
**Pull request by miekg**
As discussed in #3225, lets add a little logo. This PR incorperates this
in the startup text. It also removes the logging output as this outputs
identical lines of text, but for no clear reason. This means --quiet now
means "no output on startup at all".

Currently it looks like this:

~~~
.:1053
   ______                ____  _   _______
  / ____/___  ________  / __ \/ | / / ___/	~ CoreDNS-1.6.2
 / /   / __ \/ ___/ _ \/ / / /  |/ /\__ \ 	~ linux/amd64, go1.12.9,
/ /___/ /_/ / /  /  __/ /_/ / /|  /___/ /
\____/\____/_/   \___/_____/_/ |_//____/
~~~

We have 2 lines extra on the right if we need to print more (no ideas
come to mind currently).

### CODE REVIEW

**Comment by thaJeztah** [comment]
perhaps put the version information on their own line after the logo, for easier `grep`-ing and for small terminals?

(perhaps put the logo on stderr to allow redirecting it)

**Comment by miekg** [comment]
Quite like the way it looks now (otherwise I wouldn't have made it like
this). Can potentially add a pipe symbol before the version string as an
anchoring point?

Your terminal needs to be very narrow for this to look bad though

**Review by chrisohaver — APPROVED** [review]

**Comment by mrueg** [comment]
ASCII logos could cause issues and difficulties in terms of accessibility. Has this been tested on screenreaders / other devices?

**Comment by towolf** [comment]
Redis does this:
```
# By default Redis shows an ASCII art logo only when started to log to the
# standard output and if the standard output is a TTY. Basically this means
# that normally a logo is displayed only in interactive sessions.
#
# However it is possible to force the pre-4.0 behavior and always show a
# ASCII art logo in startup logs by setting the following option to yes.
always-show-logo yes
```

Why? Because multi-line logos look shitty in logging systems where one line is taken to be one message.

**Pull request merged**
