### PR TITLE
plugin/kubernetes: Remove multi API endpoint option

### PR DESCRIPTION
**Pull request by chrisohaver**
### 1. Why is this pull request needed and what does it do?

Removing multi k8s api connections option per #1464.

### 2. Which issues (if any) are related?
#1464

### 3. Which documentation changes (if any) need to be made?
included

### CODE REVIEW

**Comment by chrisohaver** [comment]
This change deprecates an option (multiple api endpoints).
I don't know the precise process for that.

* First merge/release a deprecation notice?
* Then merge this and release, adjusting version as appropriate?

**Comment by yongtang** [comment]
I haven't looked into multiple secure https endpoint, but multiple http endpoint was fine and I were using that feature (with multiple http).

Could the coredns-ci be a certificate issue? I couldn't see enough context from coredns-ci.

**Comment by chrisohaver** [comment]
It has been a while since I originally raised this issue, so I don't recall the details.
I could not get multiple api endpoints to work over a secure connection when testing in a local cluster.
The CI does successfully test a single endpoint over a secure connection, so the certs used by the CI in that test at least are valid. 

We could instead leave things as is, and document that we don't support secure connections for multiple api endpoints.

The code in `getClientConfig()` appears to assume an insecure connection, with "http://" hard coded in a couple of spots.

It may be easier to fix this than to deprecate, but the original bug wasn't getting any attention.
Also, no one else has raised this issue, and it would be IMO unusual for people to use this with an insecure connection, so I concluded that no one was actively using this feature.

**Comment by yongtang** [comment]
Do you have a setup or test with certificate that could expose the issue? I always had some trouble (not even specific to multiple https endpoint) for certificate with k8s api, but I could look into the multiple https endpoint issue if a setup or test with valid cert is available.

**Comment by chrisohaver** [comment]
There is a commented out test in the CI (in `test/kubernetes/excluster_test.go`)... but...

It should be easier to test locally.  I use minkube, and frequently test coredns builds running locally on my laptop configured to connect to the minikube cluster from outside of the cluster. For example, this kubernetes plugin config works for me...

```
    kubernetes cluster.local {
      endpoint https://192.168.99.100:8443
      tls /Users/cohaver/.minikube/client.crt /Users/cohaver/.minikube/client.key /Users/cohaver/.minikube/ca.crt
    }
```

If you cannot set up minikube locally, then you can open a PR in the ci repo to uncomment the test (but don't merge yet).  You can then run that integration test on a coredns repo PR by making a comment containing `/integration-ciprXX`, where XX is the number of the CI PR (as I have done in this PR above https://github.com/coredns/coredns/pull/2429#issuecomment-451209278).

**Comment by miekg** [comment]
for backwards incompat changes:
* first announce
* remove code; leave option (don't break configs)
* remove option

See 3 releases in total

**Comment by miekg** [comment]
lovely to see a LOC reduction here ,btw.

**Comment by yongtang** [comment]
Depending on how certificate was issued or the common name field of the certificate, additional implementation work might be needed to have https load balancing.

At the time the feature was implemented we were still using golang 1.9 so there were quite a few limitations for http(s) proxy.

I think reporting error on multiple https endpoints while allowing http endpoints would be the short term fix.

Will take another look and extend the support for http(s).

**Comment by yongtang** [comment]
Added PR #2438 for now.

**Comment by miekg** [comment]
how btw, is a http only endpoint useful? Is that even allowed? I mean, before we even fix this functionality, if you can't really use it now in k8s, we better remove it. (Why? It uses pkg/healthcheck, the only other user is *proxy*, I want to get rid of proxy (and pkg/healthcheck)

**Comment by miekg** [comment]
https://github.com/coredns/coredns/wiki/CoreDNS-1.3.1-Release

We are not/we are removing this in a future version? If we want to do something in an upcoming version it would be good to announce now, otherwise we need to wait another for another release.

**Comment by yongtang** [comment]
@miekg A http only (single) endpoint is legitimate as localhost access through http is common. Multiple http endpoints for HA is less common nowadays, compared with a couple of years ago when that was implemented, as a lot of things has evolved.

Of course, in-cluster deployment is always possible, but in-cluster deployment is not always easy to debug and fix if you hit an issue. For production usage, many choose out-of-cluster deploy for reliability reasons.

For out-of-cluster deploy, from CoreDNS's point of view, it is possible to achieve HA even without multiple endpoints of api servers.

A configuration is to deploy coredns on the same host for every api server. So there is a 1:1 mapping of api server and coredns. Outside of api servers, you could deploy the coredns and set multiple upstream coredns servers that are located on api servers. The HA and load balancing is achieved through coredns itself now.

So multiple k8s endpoints usage is less common. The http endpoint still has its usage.

**Comment by chrisohaver** [comment]
IMO:

**single https endpoint**: useful in conjunction with kubernetai plugin, wherein a coredns instance is connecting to other clusters.

**single http endpoint**: useful for local development and debugging kubernetes, since it's easy to debug a coredns running on on your local system.

**multiple https endpoint** : Currently does not work. Perhaps useful in conjunction with kubernetai plugin, if a remote cluster employs HA.

**multiple http endpoint**: I think unlikely this would get much use outside of sandboxes/POCs

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>IMO:
>
>**single https endpoint**: useful in conjunction with kubernetai plugin, wherein a coredns instance is connecting to other clusters.
>
>**single http endpoint**: useful for local development and debugging kubernetes, since it's easy to debug a coredns running on on the local host.
>
>**multiple https endpoint** : perhaps useful in conjunction with kubernetai plugin, if a remote cluster employs HA.
>
>**multiple http endpoint**: I think unlikely this would get much use outside of sandboxes/POCs

Seems that we could then remove the code that implements the multiple endpoints 
and noone will be off for the worse? Healthchecking a single endpoint also 
doesn't make a lot of sense, so that can go too? WDYT?

I want to kick out a 1.3.1 soonish and it would be good to get some kind of 
deprecation notice in there. See https://github.com/coredns/coredns/wiki/CoreDNS-1.3.1-Release
for the WIP notes.

**Comment by miekg** [comment]
done in #2454

**Pull request closed without merging**
