### PR TITLE
Don't crash during test when message is nil

### PR DESCRIPTION
**Pull request by chrisohaver**
### 1. What does this pull request do?

Fail test gracefully instead of crashing if message being validated is nil.

### CODE REVIEW

**Comment by miekg** [comment]
I rather not have this in these generic helpers. Why and where are these given a nil msg?

**Comment by chrisohaver** [comment]
You don't think its better to fail the test gracefully?

**Comment by miekg** [comment]
Which tests? You're amending the helper functions not the tests that call/use these

**Comment by chrisohaver** [comment]
OK

**Pull request closed without merging**
