### PR TITLE
plugin/rewrite: fix flow control logic for all rule types

### PR DESCRIPTION
**Pull request by greenpau**
Resolves: #1307

### 1. What does this pull request do?

Fixes flow control logic, i.e. stop and continue, for class and type rewrite rules.

### 2. Which issues (if any) are related?

#1307 

### 3. Which documentation changes (if any) need to be made?

N/A

### CODE REVIEW

**Comment by greenpau** [comment]
@johnbelamaric , please review.

**Comment by johnbelamaric** [comment]
Thanks, nice. Would you mind adding tests for:

- these without stop/continue
- a test that shows stopping/continuing for each

**Comment by greenpau** [comment]
> these without stop/continue

@johnbelamaric , what do you mean?

**Comment by greenpau** [comment]
> a test that shows stopping/continuing for each

@johnbelamaric , 👍

**Comment by johnbelamaric** [comment]
I mean that we shouldn't have to specify stop or continue, it should default to stop. Maybe there is already a test for that.

**Comment by greenpau** [comment]
> I mean that we shouldn't have to specify stop or continue, it should default to stop.

@johnbelamaric, If you are talking about rule creation, then, yes. The “stop” is the default.

If you are talking about rewrite test, then stop and continue are the must, because that is how the function is getting invoked.

Can you please point me to the sections of _test code where you see an opportunity to do testing. Line numbers :-)

**Comment by johnbelamaric** [comment]
Ok, looks like creation is good. My other point was that we must not have had tests for the stop/continue behavior since it wasn't working. So, adding some "continue" rules in here:

https://github.com/greenpau/coredns/blob/01a9ed501e275ac7fe82222b5c0ef987b54c8269/plugin/rewrite/rewrite_test.go#L152

and having some tests that have multiple rules applied.

**Comment by greenpau** [comment]
> My other point was that we must not have had tests for the stop/continue behavior since it wasn't working.

@johnbelamaric , 👍 will add the tests 🔢

**Comment by greenpau** [comment]
@johnbelamaric , please see if I captured your intent with the tests I added.

**Comment by johnbelamaric** [comment]
Awesome, thanks.

**Pull request merged**
