### PR TITLE
Fix corefile usage

### PR DESCRIPTION
**Pull request by stp-ip**

### CODE REVIEW

**Comment by miekg** [comment]
this will *now* work because we lazily start. It was failing the TestReadme test because the zone files don't exist.

Wish we could do the same for kubernetes config tests :/

**Comment by miekg** [comment]
think you need
~~~
diff --git a/test/example_test.go b/test/example_test.go
index 852143fe..9136db30 100644
--- a/test/example_test.go
+++ b/test/example_test.go
@@ -2,14 +2,15 @@ package test
 
 const exampleOrg = `; example.org test file
 $TTL 3600
-example.org.           IN      SOA     sns.dns.icann.org. noc.dns.icann.org. 2015082541 7200 3600 1209600 3600
-example.org.           IN      NS      b.iana-servers.net.
-example.org.           IN      NS      a.iana-servers.net.
-example.org.           IN      A       127.0.0.1
-example.org.           IN      A       127.0.0.2
-short.example.org.     1       IN      A       127.0.0.3
-*.w.example.org.        IN      TXT     "Wildcard"
-a.b.c.w.example.org.    IN      TXT     "Not a wildcard"
-cname.example.org.      IN      CNAME   www.example.net.
-service.example.org.    IN      SRV     8080 10 10 example.org.
+@              IN      SOA     sns.dns.icann.org. noc.dns.icann.org. 2015082541 7200 3600 1209600 3600
+@              IN      NS      b.iana-servers.net.
+@              IN      NS      a.iana-servers.net.
+@              IN      A       127.0.0.1
+@              IN      A       127.0.0.2
+short  1       IN      A       127.0.0.3
+
+*.w        3600 IN      TXT     "Wildcard"
+a.b.c.w    IN      TXT     "Not a wildcard"
+cname      IN      CNAME   www
+service    IN      SRV     8080 10 10 @
 `
~~~
this works on master

**Comment by stp-ip** [comment]
Not working for me yet, but will take another look.

**Comment by miekg** [comment]
the importance of README testing. This is uncovering bugs :/

**Comment by miekg** [comment]
see #3052 for the fix

**Pull request closed without merging**
