### PR TITLE
Oss-fuzz ideal integration

### PR DESCRIPTION
**Pull request by catenacyber**
### 1. Why is this pull request needed and what does it do?
This is needed for oss-fuzz _ideal_ integration cf https://google.github.io/oss-fuzz/advanced-topics/ideal-integration/

It adds 2 GitHub workflows 
- CIFuzz cf https://google.github.io/oss-fuzz/getting-started/continuous-integration/
- One workflow to check that we do not break the fuzz targets build

### 2. Which issues (if any) are related?
None

### 3. Which documentation changes (if any) need to be made?
None

### 4. Does this introduce a backward incompatible change or deprecation?
No

This was inspired by https://github.com/miekg/dns/pull/1091
The build fuzz targets workflow is not yet tested

### CODE REVIEW

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Oss-fuzz ideal in..." ]
>1. Why is this pull request needed and what does it do?
>
>This is needed for oss-fuzz ideal integration cf https://google.github.io/
>oss-fuzz/advanced-topics/ideal-integration/

why is another fuzzing thing needed? What does this add, what's the benefit?

**Comment by catenacyber** [comment]
> why is another fuzzing thing needed? What does this add, what's the benefit?

I would not say this is another fuzzing.
These are still the same fuzz targets
But now, the fuzz targets are also run by CIFuzz on each Pull Request when oss-fuzz runs only the master branch (soothes can prevent a bug of being merged)

Is this clearer ?

**Comment by miekg** [comment]
ack thanks. I don't think that really adds any additional benefit, but it does add more things you potentially need to wait on. The current way of fuzzing is good enough imo

**Comment by catenacyber** [comment]
Ok for CIfuzz.

And what about the first commit only ?
https://github.com/coredns/coredns/pull/3902/commits/db1478a69719352d041505c20454edfbb8c35747

This checks that fuzz targets keep consistent with the rest of the code

**Pull request closed without merging**
