### PR TITLE
WIP: plugin/sign: add README for DNSSEC

### PR DESCRIPTION
**Pull request by miekg**
Talk about how DNSSEC options would look like, if implemented.

Signed-off-by: Miek Gieben <miek@miek.nl>

### CODE REVIEW

**Comment by miekg** [comment]
I forgot who else is interested in this; but this is an initial dump of what I'm planning to add to the file plugin.

**Comment by johnbelamaric** [comment]
1) why not a separate plugin for this?
2) could coredns-keygen also be a plugin or is that nonsensical?

**Comment by miekg** [comment]
Potentially it can. Only needs access to the zone files and keys.

On keygen: we can't have a main function in plugins.

**Comment by miekg** [comment]
yep, separate plugin is, in fact, very easy to do. Propose the name *sign* for this, as *dnssec* is already taken.
Need to copy and paste some things from the *dnssec* plugin into this one and code a bit, but looks fairly easy.

Added benefit; I think this will now work out of the box with the *auto* plugin as well.

**Comment by miekg** [comment]
coredns-keygen can be completely kept outside the main repo.

**Comment by miekg** [comment]
closing for now, while I work on this.

**Pull request closed without merging**
