### PR TITLE
Presubmit

### PR DESCRIPTION
**Pull request by miekg**
Add presubmits to the build, i.e. little scripts that run first and catch obvious things.

### CODE REVIEW

**Comment by miekg** [comment]
adds example script the checks for the right context to be used.

**Review by yongtang — APPROVED** [review]
Tested my self with the output looks good:
```
$ make check
** presubmit/context
plugin/forward/connect.go
** presubmit/context: please use std lib's 'context' instead
go get -u github.com/alecthomas/gometalinter
gometalinter --install golint
Installing:
```

LGTM.

**Comment by yongtang** [comment]
Actually, it is not failing the build yet, only print a warning. Should the command return a error code to fail?

**Comment by miekg** [comment]
yep, wanted to error; le'me check

**Review by yongtang — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
