### PR TITLE
Benchmark for k8s services

### PR DESCRIPTION
**Pull request by bradbeam**
got curious about some of the k8s perf issues and thought I'd take a shot at putting together a little benchmark for it. unsure on the usefulness or if it's the right approach, but figured it was worth an attempt. 

kicking this test off with `go test -bench=. -benchmem -memprofile memprofile.out -cpuprofile profile.out` and reviewing the memprofile, 

```
$ go tool pprof memprofile.out
Type: alloc_space
Time: Sep 19, 2018 at 9:47pm (CDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 1669.92MB, 98.48% of 1695.64MB total
Dropped 65 nodes (cum <= 8.48MB)
Showing top 10 nodes out of 18
      flat  flat%   sum%        cum   cum%
  954.29MB 56.28% 56.28%   954.29MB 56.28%  github.com/coredns/coredns/plugin/kubernetes.APIBench.GetNamespaceByName
  191.51MB 11.29% 67.57%   693.52MB 40.90%  github.com/coredns/coredns/plugin/etcd/msg.Path
     134MB  7.90% 75.48%   229.01MB 13.51%  github.com/miekg/dns.SplitDomainName
   95.50MB  5.63% 81.11%    95.50MB  5.63%  path.(*lazybuf).append (inline)
      95MB  5.60% 86.71%       95MB  5.60%  github.com/miekg/dns.Split
   92.50MB  5.46% 92.17%    92.50MB  5.46%  path.(*lazybuf).string (inline)
      85MB  5.01% 97.18%       85MB  5.01%  strings.Join
   20.54MB  1.21% 98.39%    20.54MB  1.21%  github.com/coredns/coredns/plugin/kubernetes.generateEndpoints
    1.57MB 0.093% 98.48%    19.58MB  1.15%  github.com/coredns/coredns/plugin/kubernetes.generateSvcs
         0     0% 98.48%   954.29MB 56.28%  github.com/coredns/coredns/plugin/kubernetes.(*APIBench).GetNamespaceByName
```

i hardcoded it for a 8192 / `/19` endpoint test since it was 'easiest' to go with a cidr notation and the /20 was under 5k endpoints to try to get some data close to the 5k node test.

### CODE REVIEW

**Comment by miekg** [comment]
lgtm (and looks already useful). suspect there is a bunch of low hanging (memory) fruit that can be very easily optimized.

**Comment by miekg** [comment]
also, we don't run any of the benchmarks during CI, we should change that or setup a separate one for benching

**Comment by fturib** [comment]
@bradbeam : it is a great contribution !

I think that we may need to define a plan for the usage of this tool.
It definitively will be useful for validating the drift of perf release after release (benchmark at CI).

Can it be use to troubleshoot/tune the current consumption of memory we have on the scale perf e2e test of k8s ?
I mean: 
-  are we thinking the main consumer is still in the code if we use this benchAPI ?
- can we 'calibrate' this tools against the points we found  at 500 and 2k nodes (and the corresponding services and endpoint coded in the e2e load-scale test) ? 

@chrisohaver : do you have opinion on these questions ?

**Comment by bradbeam** [comment]
I was hoping to gear it towards helping to troubleshoot the current issue at hand ( no reason it couldn't be extended further ). I know we're wanting to reproduce this test environment, but I'm hoping that we can simulate enough locally to gain insight about hot areas local to coredns. 

I'm expecting we'll want to hit `k.ServeDNS` specifically to get a full picture of the resolution path for k8s.  I'm hoping that offers up a larger picture of the performance characteristics of the k8s plugin.

**Comment by bradbeam** [comment]
Just made that switch for using servedns, 
```
$ go test -bench=. -benchmem -memprofile memprofile.serve -cpuprofile profile.out 
goos: darwin
goarch: amd64
pkg: github.com/coredns/coredns/plugin/kubernetes
BenchmarkFindServicesAll-8         	    5000	    294713 ns/op	    1572 B/op	      29 allocs/op
BenchmarkFindServicesClusterIP-8   	    5000	    330475 ns/op	    1604 B/op	      32 allocs/op
BenchmarkFindServicesExternal-8    	    5000	    273942 ns/op	    1571 B/op	      29 allocs/op
BenchmarkFindServicesHeadless-8    	    5000	    281030 ns/op	    1571 B/op	      29 allocs/op
PASS
ok  	github.com/coredns/coredns/plugin/kubernetes	6.318s
```

```
$ echo "top" | go tool pprof memprofile.serve
Type: alloc_space
Time: Sep 20, 2018 at 9:38am (CDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) Showing nodes accounting for 123.71MB, 89.48% of 138.27MB total
Dropped 38 nodes (cum <= 0.69MB)
Showing top 10 nodes out of 62
      flat  flat%   sum%        cum   cum%
   43.56MB 31.51% 31.51%    45.06MB 32.59%  github.com/coredns/coredns/plugin/kubernetes.generateEndpoints
   18.51MB 13.39% 44.89%    18.51MB 13.39%  github.com/coredns/coredns/plugin/kubernetes.getExternalSvc
   18.01MB 13.02% 57.92%    18.01MB 13.02%  github.com/coredns/coredns/plugin/kubernetes.getClusterIPSvc
   17.01MB 12.30% 70.22%    17.01MB 12.30%  github.com/coredns/coredns/plugin/kubernetes.getHeadlessSvc
   10.50MB  7.60% 77.81%    29.50MB 21.34%  github.com/coredns/coredns/plugin/kubernetes.Kubernetes.ServeDNS
    5.50MB  3.98% 81.79%     5.50MB  3.98%  github.com/miekg/dns.Split
    3.50MB  2.53% 84.32%     3.50MB  2.53%  github.com/coredns/coredns/plugin.SOA
    3.13MB  2.26% 86.58%    56.65MB 40.97%  github.com/coredns/coredns/plugin/kubernetes.generateSvcs
    2.50MB  1.81% 88.39%     6.50MB  4.70%  github.com/coredns/coredns/plugin/etcd/msg.Path
    1.50MB  1.08% 89.48%     1.50MB  1.08%  strings.Join
```

**Comment by bradbeam** [comment]
Going to try taking a different approach. 

It looks like the better way to do this is to create a new dns controller using the client-go/fake client and then populate information there. We'll see how it goes.

**Comment by chrisohaver** [comment]
Thanks Brad!  I really appreciate the help.  Would be great to have this run in the CI to track over time.

> Can it be use to troubleshoot/tune the current consumption of memory we have on the scale perf e2e test of k8s ?

I don't _think_ so. Regarding the e2e load tests (that ones that prompted pulling CoreDNS out of 1.12), I strongly suspect that the scaling issues we saw in k8s are due to the size of the API cache/stores, which are not exercised in this benchmark.  Counterintuitively, those e2e tests load tests do not create any DNS query load (the "load" is load creation/destruction of services and endpoints).  The stress on CoreDNS in those tests is (almost?) exclusively receiving and storing service and endpoint add/update/deletes from the Kubernetes API into the service/endpoint stores.

**Comment by bradbeam** [comment]
Alright, swapped things out and using fake.Clientset and ServeDNS. I think this should be a reasonable test of things ( with the exception of having a single dns question being asked ). 

In the first test ( no time specified ), locally I observed ~55mb usage. 
```
$ go test -bench=. -benchmem -memprofile memprofile.serve -cpuprofile profile.out 
goos: darwin
goarch: amd64
pkg: github.com/coredns/coredns/plugin/kubernetes
BenchmarkController-8   	  500000	      2987 ns/op	    1600 B/op	      30 allocs/op
PASS
ok  	github.com/coredns/coredns/plugin/kubernetes	19.988s
```

```
 $ echo "top" | go tool pprof memprofile.serve
Type: alloc_space
Time: Sep 20, 2018 at 11:20am (CDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) Showing nodes accounting for 808.64MB, 78.40% of 1031.40MB total
Dropped 35 nodes (cum <= 5.16MB)
Showing top 10 nodes out of 58
      flat  flat%   sum%        cum   cum%
  255.58MB 24.78% 24.78%   792.60MB 76.85%  github.com/coredns/coredns/plugin/kubernetes.Kubernetes.ServeDNS
     135MB 13.09% 37.87%      135MB 13.09%  github.com/miekg/dns.Split
   84.01MB  8.14% 46.01%    84.01MB  8.14%  github.com/coredns/coredns/plugin.SOA
      78MB  7.56% 53.58%   109.50MB 10.62%  github.com/miekg/dns.SplitDomainName
   64.01MB  6.21% 59.78%   160.01MB 15.51%  github.com/coredns/coredns/plugin.BackendError
   63.03MB  6.11% 65.89%    67.53MB  6.55%  github.com/coredns/coredns/vendor/k8s.io/api/core/v1.(*Service).DeepCopy
   36.01MB  3.49% 69.39%    54.51MB  5.29%  github.com/coredns/coredns/vendor/k8s.io/api/core/v1.(*Endpoints).DeepCopy
   32.50MB  3.15% 72.54%      125MB 12.12%  github.com/coredns/coredns/plugin/etcd/msg.Path
      32MB  3.10% 75.64%       32MB  3.10%  github.com/miekg/dns.sprintName
   28.50MB  2.76% 78.40%    28.50MB  2.76%  github.com/miekg/dns.(*Msg).SetReply (inline)
```

Next, I ran the bench for 1m and observed it go to ~69mb then stabilized. 
```
$ go test -bench=. -benchmem -memprofile memprofile.serve -cpuprofile profile.out  -benchtime 1m
goos: darwin
goarch: amd64
pkg: github.com/coredns/coredns/plugin/kubernetes
BenchmarkController-8   	30000000	      3202 ns/op	    1600 B/op	      30 allocs/op
PASS
ok  	github.com/coredns/coredns/plugin/kubernetes	124.664s
```

```
 $ echo "top" | go tool pprof memprofile.serve
Type: alloc_space
Time: Sep 20, 2018 at 11:39am (CDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) Showing nodes accounting for 44985.88MB, 94.40% of 47655.77MB total
Dropped 70 nodes (cum <= 238.28MB)
Showing top 10 nodes out of 34
      flat  flat%   sum%        cum   cum%
15708.27MB 32.96% 32.96% 47341.44MB 99.34%  github.com/coredns/coredns/plugin/kubernetes.Kubernetes.ServeDNS
 7555.77MB 15.85% 48.82%  7555.77MB 15.85%  github.com/miekg/dns.Split
 5231.83MB 10.98% 59.80%  5231.83MB 10.98%  github.com/coredns/coredns/plugin.SOA
 4727.19MB  9.92% 69.71%  6655.74MB 13.97%  github.com/miekg/dns.SplitDomainName
 4206.58MB  8.83% 78.54% 10383.93MB 21.79%  github.com/coredns/coredns/plugin.BackendError
 1902.57MB  3.99% 82.53%  7168.23MB 15.04%  github.com/coredns/coredns/plugin/etcd/msg.Path
 1869.56MB  3.92% 86.46%  1869.56MB  3.92%  github.com/miekg/dns.(*Msg).SetReply (inline)
 1854.06MB  3.89% 90.35%  1854.06MB  3.89%  github.com/miekg/dns.sprintName
  981.03MB  2.06% 92.41%   981.03MB  2.06%  github.com/coredns/coredns/vendor/k8s.io/apimachinery/pkg/util/sets.String.List
  949.03MB  1.99% 94.40%   949.03MB  1.99%  strings.Join
```

**Comment by miekg** [comment]
#2121 runs these benchmarks now on travis (useful for memory, not the ns/ops). Itching to get this in. Is it ready to be merged soon?

**Comment by bradbeam** [comment]
I think it should accomplish what we want with using the client_go/fake package so we can actually use the dns server properly. 
Yeah it's about 98% done. Looks like i need to get the deps sorted out for client-go/fake.

**Comment by bradbeam** [comment]
Not sure I handled the dep update properly; ran dep ensure and it seemed to pull in quite a bit of updates dependencies. Left it as a secondary commit so we can back out if needed.

**Comment by bradbeam** [comment]
Should be good to go assuming the dep portion was handled correctly.

**Comment by miekg** [comment]
Can you run `dep prune` as well, may also resolve the merge conflict.

**Comment by bradbeam** [comment]
Updated

**Pull request merged**
