### PR TITLE
using promauto package to ensure all created metrics are properly registered

### LINKED ISSUE #4024: check if metric is registererd
See https://github.com/coredns/coredns/pull/4021 We seem to be forgetting to *register* metrics (too often).

The exiting metrics naming test (`test/metric_naming_test.go`) should be extended to test for this as well - at least assuming it's easy enough to do so

### PR DESCRIPTION
**Pull request by zouyee**
### 1. Why is this pull request needed and what does it do?
check if metric is registererd 

### 2. Which issues (if any) are related?
fix #4024

### 3. Which documentation changes (if any) need to be made?
none
### 4. Does this introduce a backward incompatible change or deprecation?
none

### CODE REVIEW

**Review by miekg — APPROVED** [review]
thanks!

**Comment by SuperQ** [comment]
Nice. There are a number of additional `MustRegister()` instances that can probably be removed.

**Comment by miekg** [comment]
oh yeah, was wondering that during review, but:
~~~
lugin/dnssec/setup.go:		metrics.MustRegister(c, cacheSize, cacheHits, cacheMisses)
plugin/forward/setup.go:		metrics.MustRegister(c, RequestCount, RcodeCount, RequestDuration, HealthcheckFailureCount, SocketGauge, MaxConcurrentRejectCount)
plugin/reload/setup.go:			metrics.MustRegister(c, reloadInfo, failedCount)
plugin/acl/setup.go:		metrics.MustRegister(c, RequestBlockCount, RequestAllowCount)
plugin/hosts/setup.go:		metrics.MustRegister(c, hostsEntries)
plugin/hosts/setup.go:		metrics.MustRegister(c, hostsReloadTime)
plugin/grpc/setup.go:		metrics.MustRegister(c, RequestCount, RcodeCount, RequestDuration)
plugin/metrics/register.go:// MustRegister registers the prometheus Collectors when the metrics plugin is used.
plugin/metrics/register.go:func MustRegister(c *caddy.Controller, cs ...prometheus.Collector) {
plugin/metrics/register.go:		x.MustRegister(c)
plugin/metrics/metrics.go:// MustRegister wraps m.Reg.MustRegister.
plugin/metrics/metrics.go:func (m *Metrics) MustRegister(c prometheus.Collector) {
plugin/health/setup.go:		metrics.MustRegister(c, HealthDuration)
plugin/template/metrics.go:		metrics.MustRegister(c, templateMatchesCount, templateFailureCount, templateRRFailureCount)
plugin/kubernetes/setup.go:		metrics.MustRegister(c, DnsProgrammingLatency)
plugin/autopath/setup.go:		metrics.MustRegister(c, autoPathCount)
plugin/cache/setup.go:		metrics.MustRegister(c,
plugin/dns64/setup.go:		metrics.MustRegister(c, RequestsTranslatedCount)
~~~

**Comment by miekg** [comment]
maybe we can add a smaller test in presubmit_test that check for MustRegister (instead of the Makefile test added here?)?

**Comment by zouyee** [comment]
> maybe we can add a smaller test in presubmit_test that check for MustRegister (instead of the Makefile test added here?)?

The `promauto` functions contains the registration function, the `MustRegister` method could be removed or discarded?

**Review by SuperQ — APPROVED** [review]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
