### PR TITLE
middleware/autopath: new

### PR DESCRIPTION
**Pull request by miekg**
Abstract the autopath functionality into it's own middleware. This does server side search path expansion.

Note: there is still a lot to copy, I'm trying to use git for most things to keep the attribution correct.

### CODE REVIEW

**Comment by miekg** [comment]
It's not working and no tests, but it should give a general feel of having this functionality live outside the kubernetes middeware
/cc @chrisohaver @johnbelamaric

**Comment by johnbelamaric** [comment]
This can't do the same as the K8s auto path. The K8s auto path needs to look up the search path based on the *client source IP*. Each pod will have a search path that depends on the namespace in which the pod lives.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/au..." ]
>This can't do the same as the K8s auto path. The K8s auto path needs to look up the search path based on the *client source IP*. Each pod will have a search path that depends on the namespace in which the pod lives.

Damn. But that might still be doable, as it is just a way to get the searchpath 
for this request. Would be nice if there was a way to call into middleware - but 
that has complication as well. But that gets ugly as well :(

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/au..." ]
>This can't do the same as the K8s auto path. The K8s auto path needs to look up the search path based on the *client source IP*. Each pod will have a search path that depends on the namespace in which the pod lives.

But I "somehow" get this list, it should work fine, no?

**Comment by johnbelamaric** [comment]
Yes, I think so. @chrisohaver ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/au..." ]
>Yes, I think so. @chrisohaver ?

Then I have an even whackier idea: Implement this is a standalone middleware 
(which nobody is allowed to use? dunno). Wrap the kubernetes middleware in the
autopath middleware before we instantiate the kubernetes middleware. Add some 
special code that retrieve the domain search list from k8s before calling the 
ServeDNS from kubernetes. This should mean, all this special casing is kept
outside the kubernetes middleware and we may spin this off as another 
middleware; it also makes the testing easier (as said before).

**Comment by chrisohaver** [comment]
Conceptually perhaps. Less efficient though, since all incoming queries are checked for inclusion in every domain in the path.

**Comment by chrisohaver** [comment]
the goal is to make this _less_ complex, right?

**Comment by chrisohaver** [comment]
Can you expand on how this would make testing easier? (testing of what, and how)

**Comment by johnbelamaric** [comment]
Here's another idea. I think we could proceed with what we have for 009. It's a working PR. We can then look at how this fits in back with the policy piece. Not to pull another thing in, but there is some real overlap here.

Today, the policy integration at https://github.com/infobloxopen/themis/tree/master/contrib/coredns/policy is focused on looking at individual queries and deciding to allow, block, or redirect them. It can use the basic query data or edns0 data to make those decisions. We ALSO have plans to eventually allow an integration with K8s to allow K8s meta-data (for example, labels on the pod making the query) to be used in these kind of policy decisions. The search path is really just another piece of meta-data in this case. So, as we move forward on enabling the gathering of that meta-data for policy, it could also be re-used in an auto path middleware.

In a kind-of-sort-of related idea, we could actually use the policy stuff to determine not just whether to allow, block, or redirect (to another IP) a query, we could actually allow it to determine the downstream middleware chain. Sort of a programmable "fall through".

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/au..." ]
>the goal is to make this _less_ complex right?

This would mean no code changes in the kubernetes middleware. 

Re: testing: stand alone middleware: write Corefile, fire up CoreDNS, send 
queries; no need for k8s at all.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/au..." ]
>Here's another idea. I think we could proceed with what we have for 009. It's a working PR. We can then look at how this fits in back with the policy piece. Not to pull another thing in, but there is some real overlap here.
>
>Today, the policy integration at https://github.com/infobloxopen/themis/tree/master/contrib/coredns/policy is focused on looking at individual queries and deciding to allow, block, or redirect them. It can use the basic query data or edns0 data to make those decisions. We ALSO have plans to eventually allow an integration with K8s to allow K8s meta-data (for example, labels on the pod making the query) to be used in these kind of policy decisions. The search path is really just another piece of meta-data in this case. So, as we move forward on enabling the gathering of that meta-data for policy, it could also be re-used in an auto path middleware.
>
>In a kind-of-sort-of related idea, we could actually use the policy stuff to determine not just whether to allow, block, or redirect (to another IP) a query, we could actually allow it to determine the downstream middleware chain. Sort of a programmable "fall through".

that's a very nice idea, but we do have to be a bit careful not to reinvent a 
mini-coredns in each middleware :-)

I agree with 009, let's release. I'll whack a bit on this PR to see it pans out.

**Pull request closed without merging**
