### PR TITLE
Improvements in the documentation (README.md)

### PR DESCRIPTION
**Pull request by cekbote**
Signed-off-by: Chanakya-Ekbote <ca10@iitbbs.ac.in>

Why is this pull request needed and what does it do?

It improves the documentation as discussed with @yongtang

### CODE REVIEW

**Comment by cekbote** [comment]
@yongtang Apologies for the mess. I think you can find all the changes in this. :)

**Comment by yongtang** [comment]
@Chanakya-Ekbote There are trailing whitespaces in the README.md:
```
--- FAIL: TestTrailingWhitespace (0.01s)
479    presubmit_test.go:28: file "/home/travis/gopath/src/github.com/coredns/coredns/README.md" has trailing whitespace at line 93, text: "dig @127.0.0.1 -p 53 www.example.com "
480    presubmit_test.go:28: file "/home/travis/gopath/src/github.com/coredns/coredns/README.md" has trailing whitespace at line 99, text: "The configuration of CoreDNS is done through a file named `Corefile`. When CoreDNS starts, it will "
481    presubmit_test.go:28: file "/home/travis/gopath/src/github.com/coredns/coredns/README.md" has trailing whitespace at line 100, text: "look for the `Corefile` from the current working directory. A `Corefile` for CoreDNS server that listens "
482FAIL
```

Can you remove those trailing whitespaces?

**Comment by cekbote** [comment]
> 
> 
> @Chanakya-Ekbote There are trailing whitespaces in the README.md:
> 
> ```
> --- FAIL: TestTrailingWhitespace (0.01s)
> 479    presubmit_test.go:28: file "/home/travis/gopath/src/github.com/coredns/coredns/README.md" has trailing whitespace at line 93, text: "dig @127.0.0.1 -p 53 www.example.com "
> 480    presubmit_test.go:28: file "/home/travis/gopath/src/github.com/coredns/coredns/README.md" has trailing whitespace at line 99, text: "The configuration of CoreDNS is done through a file named `Corefile`. When CoreDNS starts, it will "
> 481    presubmit_test.go:28: file "/home/travis/gopath/src/github.com/coredns/coredns/README.md" has trailing whitespace at line 100, text: "look for the `Corefile` from the current working directory. A `Corefile` for CoreDNS server that listens "
> 482FAIL
> ```
> 
> Can you remove those trailing whitespaces?

Just did :)

**Review by yongtang — APPROVED** [review]
LGTM, Thanks for the PR!

**Comment by cekbote** [comment]
> LGTM

Cool thank you for all your help :)

**Pull request merged**
