### PR TITLE
Implement notifies for transfer plugin

### PR DESCRIPTION
**Pull request by miekg**
* Fix all plugins to use the new implementation (this is backwards
  incompatible)
* Implement notifies in transfer
* Make file and auto do notifies using transfer

This copied stuff from #3452. It leave out (PR is long enough as it is) the notify source port PR: #3420. That can and should probably bo cherry-picked in .

### 3. Which documentation changes (if any) need to be made?

transfer/README.md is updated and the plugins implementing `Transferer` have seen updates as well.

### 4. Does this introduce a backward incompatible change or deprecation?
Yes, this rips out the old code transferring and also makes the Corefile parsing a fatal error.

### CODE REVIEW

**Comment by miekg** [comment]
also need to check what happens when a plugin gets hit TypeAXFR and how they respond. AXFR fallback for IXFR may need work, the *file* plugin did something special there.

**Comment by chrisohaver** [comment]
I suppose this supersedes the various open PRs that implement parts of this?
e.g. #3732 #3452 #3420 #3419

I don't think #3929 is addressed here (implemented in #3420).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Implement not..." ]
>I suppose this supersedes the various open PRs that implement parts of this?
>e.g. #3732 #3452 #3420 #3419

oh sorry, I missed those. Let me review with my new knowledge (happy to drop this PR)

/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
> happy to drop this PR

No, that's not necessary.  I was just verifying whether or not these were intended to replace, or to expand upon any of the existing related PRs.  I'll close my PRs, and we can move forward with this one.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Implement not..." ]
>    happy to drop this PR
>
>No, that's not necessary. I was just verifying whether or not these were
>intended to replace, or to expand upon any of the existing related PRs. I'll
>close my PRs, and we can move forward with this one.

left a bunch of comments on those. Some stuff is better there than here. I can probably
trim this back down to *just* the notifies and merge your other PRs?

**Comment by chrisohaver** [comment]
> left a bunch of comments on those. Some stuff is better there than here. I can probably
trim this back down to *just* the notifies and merge your other PRs?

I think the easiest way forward (least amount of total work), would be to pull aspects of those PRs that you like into this one, rather than the other way around.   The implementation in this PR is naturally fresh in your mind.  The prior PRs have been sitting around for 4 - 8 months... I have lost some familiarity ...  some have collected merge conflicts. etc.

**Comment by miekg** [comment]
I have rebased and merged this branch, so I can't easliy squashed.

This implements notifies and fixed a bunch of bugs in transfer along the way. All supporting plugin explicitly implement ixfr to axfr fallback.

**Comment by miekg** [comment]
this acl checking is problematic with this plugin (i've changed it here, but it's still wrong)

~~~
org {
    auto {
        directory /etc/coredns/zones/org
    }
 
    transfer {
        to *
        to 10.240.1.1
    }
}
~~~
so *transfer* has `org` in it's auth list. An axfr for example.org won't match (in the current code, it did before). Moving that back to `Matches` would fix it, but this is also valid:
~~~
org {
    auto {
        directory /etc/coredns/zones/org
    }
 
    transfer example.org {
        to *
        to 10.240.1.1
    }

    transfer sub.example.org {
        to 10.240.1.2
    }
}
~~~
The key problem is that matching the ACL is different that matching the authoritativeness of the zone which is done with ErrNotAuthoritative.

**Comment by miekg** [comment]
*maybe* `Matches` was the right thing to do, left me see if I can test this properly

removing upstream stuff *in this PR* was stupid, I'll revert that.

**Comment by miekg** [comment]
ok PTAL, a build from this branch is now serving coredns.io, accoding to the logging it's all working nicely

**Review by chrisohaver — APPROVED** [review]

**Comment by chrisohaver** [comment]
>  It leave out (PR is long enough as it is) the notify source port PR: #3420.

FYI, #3420 was not simply a notify source port PR it was an entire implementation of notify (hence its length), created in November 2019.  The notify source port issue had only recently been raised, and I added that case to the PR only recently.

**Review by yongtang — APPROVED** [review]

**Comment by chrisohaver** [comment]
This was a backward incompatible change. Probably should have held on to it before merging right away in case any other critical bugs come up before next release.   With this merged, I think Next release Needs to be 1.8.0 ?

On Jul 7, 2020, at 3:38 PM, Yong Tang <notifications@github.com> wrote:

﻿

Merged #3972<https://urldefense.com/v3/__https://github.com/coredns/coredns/pull/3972__;!!JYsgTRAg6ZQ!ZP4DugOLWxwDV0vhWUGgPZJngg05c1M2tbIiN4Kfd8dDolWJmHtMmTl4t_JwPJRe$> into master.

**Comment by yongtang** [comment]
Ah yes that might be a concern. We normally release minor versions every several months, and release patch versions every couple of weeks. The 1.7.0 was released only 3 weeks ago.

Maybe we can go directly to 1.8.0 in the next round?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Implement not..." ]
>Ah yes that might be a concern. We normally release minor versions every
>several months, and release patch versions every couple of weeks. The 1.7.0 was
>released only 3 weeks ago.
>
>Maybe we can go directly to 1.8.0 in the next round?

we can revert this for the time being? No matter what else we end up merging, if this goes
in we need to make it a 1.8.0 release. It's not as bad as it's sounds unless you use zone
transfers. I.e. for k8s this would most likely be a drop-in replacement.

**Comment by johnbelamaric** [comment]
In the meantime, can we build translation support into the migrate tool, if we haven't already?

**Comment by chrisohaver** [comment]
> In the meantime, can we build translation support into the migrate tool, if we haven't already?

Should be easy to add once it's released in CoreDNS.

**Pull request merged**
