### PR TITLE
Update 1.7.0 release note date

### PR DESCRIPTION
**Pull request by yongtang**
This PR Update 1.7.0 release note date, to change from March to June (current).

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by chrisohaver** [comment]
Are we releasing today?

**Comment by yongtang** [comment]
@chrisohaver The pending item (https://github.com/coredns/coredns/issues/3945#issuecomment-643491869)

- [x] Bump version to 1.7.0 (PR #3782)
- [x] Man page update (PR #3946)
- [x] Release note (PR #3947 and #3949)
- [ ] Release (TODO)

We could release if feeling comfortable.

**Comment by chrisohaver** [comment]
OK.  I suppose the date on the notes does not need to match the exact day of release.

**Review by chrisohaver — APPROVED** [review]

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Update 1.7.0 rele..." ]
>This PR Update 1.7.0 release note date, to change from March to June (current).

Thanks for pushing this all out. I've pulled down and updated the website - this _is_
automated as we're waiting to put all this on netifly.

Good to see the the  coredns(-release) bus factor != 1 and all the automation just working
as it's intended to be :-)

Thanks all!

**Comment by miekg** [comment]
On that note; current John and me have access to the twitter account `@corednsio` (FYI)

**Pull request merged**
