### PR TITLE
Fix k8s client

### PR DESCRIPTION
**Pull request by johnbelamaric**
This is a hack to fix the build. I still need to test the k8s middleware functionality but it passes the unit tests.

### CODE REVIEW

**Comment by johnbelamaric** [comment]
Miek - looks like we need to implement vendoring for the k8s client code so we can clean up this hack.

**Comment by yongtang** [comment]
It seems test failed again:

```
=== RUN   TestKubernetesIntegration
E1103 18:29:22.471883   24301 reflector.go:370] k8s.io/client-go/1.5/tools/cache/reflector.go:109: expected type *api.Endpoints, but watch event object had type *v1.Endpoints
--- FAIL: TestKubernetesIntegration (10.02s)
    kubernetes_test.go:126: Expected '1' A records in response. Instead got '0' A records. Test query string: 'mynginx.demo.coredns.local.'
    kubernetes_test.go:129: Expected '1' records in answer section. Instead got '0' records in answer section. Test query string: 'mynginx.demo.coredns.local.'
...
```

**Comment by miekg** [comment]
I'm not opposing vendoring. But given the churn in k8s will we be looking
at monthly sync-to-latest?

**Comment by yongtang** [comment]
Kubernetes released 1.3.0 in July 1st and 1.4.0 in Sept 26th (2-3month). That is the major version only.

**Comment by johnbelamaric** [comment]
We would vendor the client-go library, locking it to the release-1.5 stable branch. So not much change. That will support K8s 1.3-1.5.

**Comment by miekg** [comment]
Well they say in the docs that you should... So lets. Just use the official
supported usecase by dropping stuff in a vendor dir?

**Comment by johnbelamaric** [comment]
Ok. Functionally this isn't quite working, going to figure that out first.

**Comment by johnbelamaric** [comment]
I don't think these SRV tests really make sense. Shouldn't the query be for something like:

`_http._tcp.mynginx.default.cluster.local`

not

`mynginx.default.cluster.local`

?

**Comment by miekg** [comment]
In general: for service discovery we don't adhere to the srv rfcs. So the
names are different and more sane IMHO.

**Comment by johnbelamaric** [comment]
Ok, so it looks like the data in kubernetes_test is wrong, because it actually starts two services in the demo namespace but is only expecting one in the test. So it's a test issue. Fix coming shortly.

**Comment by johnbelamaric** [comment]
Ok, all the k8s tests pass now. The failure is in Metrics and I believe unrelated to this PR.

**Comment by miekg** [comment]
ok, let me fix the cache stuff today.

**Comment by miekg** [comment]
How do you build this? I keep getting:

```
% go get -u 
package github.com/miekg/coredns/vendor/k8s.io/client-go/1.5/tools/cache: github.com/miekg/coredns is a custom import path for https://github.com/miekg/coredns, but /home/miek/g/src/github.com/miekg/coredns is checked out from ssh://git@github.com/miekg/coredns
package github.com/miekg/coredns/vendor/k8s.io/client-go/1.5/tools/clientcmd: github.com/miekg/coredns is a custom import path for https://github.com/miekg/coredns, but /home/miek/g/src/github.com/miekg/coredns is checked out from ssh://git@github.com/miekg/coredns
```

**Comment by miekg** [comment]
Ok, need to remove the old imports....

anyway this also break `go test ./...`

**Pull request merged**
