### PR TITLE
pkg/tls: remove InsecureSkipVerify=true flag

### PR DESCRIPTION
**Pull request by miekg**
pkg/tls: remove InsecureSkipVerify=true flag

CWE-295 code scanning alert flag this. Seems OK to just remove it.

### CODE REVIEW

**Comment by miekg** [comment]
....and foobared this PR

**Comment by miekg** [comment]
rebase -i HEAD~3: drop some commits; rebase master and voila a pristine PR :)

**Comment by johnbelamaric** [comment]
Huh. Seems like it could break some people but it's a terrible thing to have in there.

/approve

**Comment by johnbelamaric** [comment]
or is it

/lgtm

**Comment by miekg** [comment]
I'll make 'dreck' give more feedback when commands fail, like this merge (this is because travis hasn't tested this yet)

**Pull request merged**
