### PR TITLE
Adding wildcard support

### PR DESCRIPTION
**Pull request by mrichmon**
- Wildcard lookup working for namespaces and services.
- Basic integration tests for live kubernetes system implemented in tests/kubernetes_test.go. (First, manually launch kubernetes and test services.)

### CODE REVIEW

**Comment by aledbf** [comment]
@mrichmon a couple of question about the kubernetes middleware (and code):
- why are you using `fmt.Println("[debug]` and not just add `errors stdout` and `log stdout` in a Corefile?
- did you tried to use the kubernetes API instead of manual requests against the api-server?

In particular `"k8s.io/kubernetes/pkg/controller/framework".NewInformer`

I've been using your previous PR with the mentioned changes [here](https://github.com/aledbf/coredns/blob/k8s-cleanup/middleware/kubernetes/controller.go)

**Comment by mrichmon** [comment]
@aledbf Great to hear that someone is using this work. Any information you can tell me about your use would help me build support in my company for continuing this work.

With regard to your comments:
- I am viewing this as still very much a prototype. So using fmt.Printf is a short-term convenience to support debugging. These print statements are starting to be removed in this recent PR.
- I have used the k8s notification API in another project. For the CoreDNS work, I agree that the notification API would be useful. My initial focus is on getting SkyDNS-equivalent functionality from the perspective of the DNS client. Once I have the client-facing functionality in place I will focus on improving the performance of kubernetes data access. My plan is to build out an in-memory cache of the k8s data and will likely use the notification API to update that cache.

My guess is that this change to how I interface with kubernetes will be implemented in the next couple of weeks.

**Comment by aledbf** [comment]
@mrichmon I've been working here https://github.com/aledbf/coredns/tree/k8s-cleanup using #181 as starting point.(the code uses the k8s notification API)
Last night implemented the `PTR` support and now is possible to swap `kube-dns` with this to get basic dns support.
I'm interested in coredns because it allows me to customize things like forward dns (using middleware/proxy) and cache.

This is the yaml file to configure coredns

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-configmap
  namespace: kube-system
data:
  corefile: |
    .:53 {
      kubernetes coredns.local {
      }
      #cache 160 coredns.local
      errors stdout
      log stdout
    }
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    version: v20
  name: kube-dns-v20
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v20
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        kubernetes.io/cluster-service: "true"
        version: v20
    spec:
      containers:
      - args:
        - -conf=/cfg/corefile
        - -logtostderr
        image: aledbf/kube-coredns:0.5
        imagePullPolicy: IfNotPresent
        name: kube-dns
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /cfg
      - args:
        - -cmd=nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
        - -port=8080
        image: gcr.io/google_containers/exechealthz:1.0
        imagePullPolicy: IfNotPresent
        name: healthz
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
      dnsPolicy: Default
      volumes:
        - name: config-volume
          configMap:
            name: coredns-configmap
```

and this the output

```
old-mbp:~ aledbf$ kubectl logs  --namespace kube-system kube-dns-v20-dnvpc -c kube-dns|more
Activating privacy features...
controller %v &{0xc820416b40 {corefile [{ 2 kubernetes} { 2 coredns.local.} { 2 {} { 3 }}] -1 0} 0x4c3040 0 0 [.:53] <nil>}

.:53
127.0.0.1 - [14/Jul/2016:07:15:03 +0000] "A IN kubernetes.default.svc.cluster.local. udp false 512" NOERROR 70 986.899µs
127.0.0.1 - [14/Jul/2016:07:15:03 +0000] "PTR IN 1.0.3.10.in-addr.arpa. udp false 512" NOERROR 61 240.587µs
127.0.0.1 - [14/Jul/2016:07:15:05 +0000] "A IN kubernetes.default.svc.cluster.local. udp false 512" NOERROR 70 92.028µs
127.0.0.1 - [14/Jul/2016:07:15:05 +0000] "PTR IN 1.0.3.10.in-addr.arpa. udp false 512" NOERROR 61 245.367µs
127.0.0.1 - [14/Jul/2016:07:15:07 +0000] "A IN kubernetes.default.svc.cluster.local. udp false 512" NOERROR 70 115.001µs
127.0.0.1 - [14/Jul/2016:07:15:07 +0000] "PTR IN 1.0.3.10.in-addr.arpa. udp false 512" NOERROR 61 103.66µs
127.0.0.1 - [14/Jul/2016:07:15:09 +0000] "A IN kubernetes.default.svc.cluster.local. udp false 512" NOERROR 70 99.583µs
127.0.0.1 - [14/Jul/2016:07:15:09 +0000] "PTR IN 1.0.3.10.in-addr.arpa. udp false 512" NOERROR 61 82.15µs
127.0.0.1 - [14/Jul/2016:07:15:11 +0000] "A IN kubernetes.default.svc.cluster.local. udp false 512" NOERROR 70 142.948µs
127.0.0.1 - [14/Jul/2016:07:15:11 +0000] "PTR IN 1.0.3.10.in-addr.arpa. udp false 512" NOERROR 61 60.133µs
127.0.0.1 - [14/Jul/2016:07:15:13 +0000] "A IN kubernetes.default.svc.cluster.local. udp false 512" NOERROR 70 114.869µs
127.0.0.1 - [14/Jul/2016:07:15:13 +0000] "PTR IN 1.0.3.10.in-addr.arpa. udp false 512" NOERROR 61 98.22µs
```

**Comment by miekg** [comment]
Please continue this discussion :-)
I'm happy to merge this as-is, if it makes cleanups/consolidation easier.

Really cool to see the CoreDNS can already be used in k8s!

**Comment by miekg** [comment]
@aledbf welcome back! :)

**Comment by mrichmon** [comment]
My suggestion is:
1. merge this PR,
2. continue this discussion,
3. I'll continue work focusing on the SkyDNS functionality. Then I'll investigate merging the ideas that @aledbf has in his fork.

**Comment by aledbf** [comment]
@miekg thanks :)

**Comment by aledbf** [comment]
@mrichmon [here's](https://github.com/aledbf/coredns/tree/k8s-cleanup-190) the code with my changes after this PR

[This is the log with PTR records working](https://gist.github.com/aledbf/c3fc68cb182d9e2b6628ef0c9a3db931)

**Comment by mrichmon** [comment]
@aledbf I'm seeing an error with the k8s-cleanup-190 branch when I try "go get". Any immediate thoughts before I dig into debugging?

Errors are:

```
/vagrant/go-coredns-aledbf/src/github.com/miekg/coredns $ go get
# k8s.io/kubernetes/pkg/api/v1
../../../k8s.io/kubernetes/pkg/api/v1/conversion.go:248: undefined: autoConvert_api_PodStatusResult_To_v1_PodStatusResult
../../../k8s.io/kubernetes/pkg/api/v1/conversion.go:289: undefined: autoConvert_v1_PodStatusResult_To_api_PodStatusResult
../../../k8s.io/kubernetes/pkg/api/v1/conversion.go:304: undefined: autoConvert_api_PodTemplateSpec_To_v1_PodTemplateSpec
../../../k8s.io/kubernetes/pkg/api/v1/conversion.go:346: undefined: autoConvert_v1_PodTemplateSpec_To_api_PodTemplateSpec
../../../k8s.io/kubernetes/pkg/api/v1/conversion.go:363: undefined: autoConvert_api_PodSpec_To_v1_PodSpec
../../../k8s.io/kubernetes/pkg/api/v1/conversion.go:382: undefined: autoConvert_v1_PodSpec_To_api_PodSpec
../../../k8s.io/kubernetes/pkg/api/v1/conversion.go:405: undefined: autoConvert_api_Pod_To_v1_Pod
../../../k8s.io/kubernetes/pkg/api/v1/conversion.go:477: undefined: autoConvert_v1_Pod_To_api_Pod
../../../k8s.io/kubernetes/pkg/api/v1/conversion.go:493: undefined: autoConvert_api_ServiceSpec_To_v1_ServiceSpec
../../../k8s.io/kubernetes/pkg/api/v1/conversion.go:502: undefined: autoConvert_v1_Secret_To_api_Secret
../../../k8s.io/kubernetes/pkg/api/v1/conversion.go:502: too many errors
```

**Comment by aledbf** [comment]
Please update your k8s fork. They removed the autogenerated code and that
introduced this error.

**Comment by mrichmon** [comment]
Hmm, weird that go get didn't pull down that head of the k8s repo. Pulling the updated code fixed those errors.

I have been able to replicate successful testing of `make test` with @aledbf's patches in my environment. With the k8s integration tests (`make testk8s`) I've found some segfaults. I will need to debug today.

To replicate the k8s setup for the integration tests, look at middleware/kubernetes/test/README.md

**Comment by mrichmon** [comment]
@aledbf Are you ok with me using your code as the starting point of integrating with the k8s notification API?
I'm planning on merging your "190" branch into my dev branch and attributing the code to you.

**Comment by aledbf** [comment]
> Are you ok with me using your code as the starting point of integrating with the k8s notification API?

Off course :)

**Comment by mrichmon** [comment]
@aledbf Do you have any pointers to how to connect to the kubernetes api
from inside the cluster and outside the cluster? The code changes in your
branch look like they will only work if CoreDNS is running in the
kubernetes cluster.

I'm trying to work out a way to allow CoreDNS to work correctly both inside
k8s, and when running outside k8s. I haven't found any good examples or
docs for the golang k8s library.

A second, issue I'm facing with merging your code is that the CoreDNS
binary ends up being ~58M with the kubernetes client library. In
comparison, the binary was ~21M before the kubernetes client library.

...Michael

**Comment by aledbf** [comment]
> Do you have any pointers to how to connect to the kubernetes api
> from inside the cluster and outside the cluster? The code changes in your
> branch look like they will only work if CoreDNS is running in the
> kubernetes cluster.

Right now I'm changing the how the connection is stablished against a k8s cluster [here](https://github.com/kubernetes/contrib/pull/1467)
This removes the limitation and only requires the env variable:
`KUBERNETES_MASTER=http://<master ip>:<port>`

> I haven't found any good examples or
> docs for the golang k8s library.

I think this can help https://godoc.org/k8s.io/kubernetes/pkg/kubectl/cmd/util#DefaultClientConfig

> A second, issue I'm facing with merging your code is that the CoreDNS
> binary ends up being ~58M with the kubernetes client library

This because of the go dependencies in current implementation.
I think this could change after kubernetes/kubernetes#9147

**Comment by mrichmon** [comment]
Continuing to hack on the code, it might be useful to look at my current
working branch where I have integrated your changes:
https://github.com/Infoblox-CTO/coredns/tree/july22-2016

I'll take a look at the link to the kubectl DefaultClientConfig on
Wednesday.

Thanks,
Michael Richmond

**Comment by mrichmon** [comment]
@aledbf I have fixed the Travis CI script to fix the build problems that were introduced with the k8s.io dependency. (The Travis execution environment is a little weird.) This means that travis-ci is working on the HEAD of https://github.com/Infoblox-CTO/coredns/tree/july22-2016 branch.

However, the k8s.io integration tests are failing consistently failing on my local machine and when running in Travis-CI. I think this is because the Kubernetes.dnsController == nil at runtime.

**Pull request merged**
