### PR TITLE
Setup functions

### PR DESCRIPTION
**Pull request by miekg**
Proposal for #2394

### CODE REVIEW

**Comment by miekg** [comment]
More descriptive error messages might be a thing. May need an extension of the Types to include a directive that can be used when erroring.

**Comment by miekg** [comment]
this may also be overkill and doing it simpler in setup functions might be better.

**Review by fturib — COMMENTED** [review]
I think we de not need the Value structure - because the only one that can use it is the one that already ask for the Parse with a defined Type.

= >Parse should return []interface{}

And the caller can just translate into the right type.

```
vals, err := cs.Parse(c, cs.Int{0, -1, 2})
if err != nil {
}
e.drop = uint64(vals[0])
```

**Review by fturib — COMMENTED** [review]
I will be maybe more easy to split into 2 kinds of tools:
- check the number of parameters
- parse the value of each parameters depending the expected type and possible values.

We may rather need a set of simple helpers  that simplify the job:
```
args, err = ensureRemainingArgs(c, min, max)
myint, err := parseNum(args[0], 0, 32766, "delay of the xxx")
mydur,err  := parseDuration(arg[1], 10*Time.ms, 4*Time.Hour, "needed time for xxx")
```

**Comment by miekg** [comment]
thanks for reviewing. I'll close this; nice exercise on what Go can do, doesn't help in readability at all.

**Pull request closed without merging**
