### PR TITLE
[WIP] plugin/forward: gRPC support

### PR DESCRIPTION
**Pull request by inigohu**
### 1. Why is this pull request needed and what does it do?
To support gRPC connection in forward plugin

### 2. Which issues (if any) are related? 
#1476 

### 3. Which documentation changes (if any) need to be made?
Forward plugin documentation.

### 4. Does this introduce a backward incompatible change or deprecation?
It shouldn't be

### CODE REVIEW

**Comment by inigohu** [comment]
Here is my first approach of how implement a gRPC proxy in Forward plugin. The idea is the same as I mentioned in #1476 issue. Create a proxy interface that satisfied **gRPC** and **DNS** proxies, as well as **DoH** proxy in the future.

Here I attach a schema that helps me visualizing the new structure of the plugin.
coredns-forward-new 1

Here is the forward plugin's new workflow.
coredns-forward-new 2


/cc @glerchundi

**Comment by miekg** [comment]
Thanks. Before I take a look I want to pose the question: how realistic is
it to make this a new plugin that only does gRPC forwarding?

I slightly concerned with making forward as complex as proxy was, which
will hamper future refactoring, etc.

**Comment by miekg** [comment]
I'm really on two thoughts here, hence my question.

One thing in favour of doing a new plugin is TLS config which now applies
to the entire proxy. And there a bunch of options that make no sense for
gRPC and DoH

**Comment by inigohu** [comment]
> how realistic is it to make this a new plugin that only does gRPC forwarding?

Is a good option and looks good to me. That would simplified de forward plugin implementation without mixing different proxies configurations like the TLS configuration as you mentioned.

I can make you a proposal of a plugin with just gRPC connection.

Which would be the name of the plugin? _gRPC-forward_?
Should be in this repository o maybe an external plugin?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] [WIP] plugin/..." ]
>> how realistic is it to make this a new plugin that only does gRPC forwarding?
>
>Is a good option and looks good to me. That would simplified de forward plugin implementation without mixing different proxies configurations like the TLS configuration as you mentioned.
>
>I can make you a proposal of a plugin with just gRPC connection.
>
>Which would be the name of the plugin? _gRPC-forward_?

I think we can just name it grpc (I like short name for this)

>Should be in this repository o maybe an external plugin?

Useful enough to include by default.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
closing in favor of #2667

**Pull request closed without merging**
