### PR TITLE
middleware/etcd: rename etcd to backend

### PR DESCRIPTION
**Pull request by VioletRainbows**
This a smaller commit reduce the size of the PRs. It is not the complete work.

Next steps:
- seprarate etcd and backend struct
- move etcd to it's own package

### CODE REVIEW

**Comment by VioletRainbows** [comment]
Would you prefer this being on a separate branch, or is master fine?

**Comment by miekg** [comment]
Doing the entire move, PR by PR on a separate branch and merge into master? SGTM, but I actually have no idea how to do this in/via github? (should I create a branch for that?)

**Comment by VioletRainbows** [comment]
If you create a new branch, I can modify this PR so that it will be merged into said new branch.

**Comment by miekg** [comment]
https://github.com/coredns/coredns/tree/backend-work now exists, it took this PR as a starting point.

**Pull request closed without merging**
