### PR TITLE
middleware/metrics: cleanup

### PR DESCRIPTION
**Pull request by miekg**

### CODE REVIEW

**Comment by miekg** [comment]
@yongtang this touches quite a lot, could you have a glance over?

**Comment by yongtang** [comment]
Thanks @miekg will take a look today.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/metr..." ]

> Thanks @miekg will take a look today.

cool. I've updated it (again) as I had an idea this morning. I've done
away with globally registring middleware, you can get that data from 
the server's config as well.

I'll only expect some cleanups. Note the middleware.Handler interface now
includes a Name() method.

Thanks again.

**Comment by yongtang** [comment]
LGTM. Thanks.

**Pull request merged**
